### ISSUE TITLE
Error dialing peer   moule=p2p err="auth failure: conn.ID () dialed ID () mismatch"

### ISSUE THREAD

**Issue by bala223344** [maticnetwork/heimdall#1008]
**Heimdall version** (use `heimdall version` or `git rev-parse --verify HEAD` if installed from source):  0.3.4

**Environment**: aws ec2
- **OS** (e.g. from /etc/os-release): ubuntu 22.04
- **Install tools**:
- **Others**:

**What happened**: 
   module=p2p err="auth failure: conn.ID (a7e0947e2000ed5881c8bcdb8b7250e5dfc04789) dialed ID (44691aa040233..e5adc0b43f8e) mismatch"
ERROR[2023-06-17|02:47:31.725] Failed to reconnect to peer. Beginning exponential backoff module=p2p addr=44691aa040233..e5adc0b43f8e@18.143.66.230:26656 elapsed=2m3.3960971s

**What you expected to happen**:
connect the sentry from validator

**Have you tried the latest version**: yes/no
yes
**How to reproduce it** (as minimally and precisely as possible):

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:
pex = true
seed_mode = false
private_peer_ids = "e63525e556f89...cb549e91ef201cd5138"

**node command runtime flags**:
/home/ubuntu/go/bin/heimdalld start
**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**:
when I try to telnet it always ends up with some junk chars and closing itself.
 telnet 0.0.0.0 26656
Trying 0.0.0.0...
Connected to 0.0.0.0.
Escape character is '^]'.
! ������]�f�Oe���<�叱3��xƒ   UConnection closed by foreign host.

**Comment by neoromantique** [comment]
I am getting same results, both when starting fresh and when using snapshot.

**Comment by manav2401** [comment]
This is a common p2p issue in heimdall. Can you try adding the sentry's peer id in the `persistent_peers` field in heimdall's config?

**Comment by bala223344** [comment]
I have got this info which was finally helpful resolving this. 
https://forum.polygon.technology/t/bor-heimdall-mainnet-upgrade-v0-3-0-action-required/10691

**Comment by AmardeepSambaru** [comment]
Iam also facing the same issue.

I setup the Validator node, followed the offical doc and edit the all config file and everything.
After that i restart the Validator heimdall service. it is showing the "Error dialing peer" "mismatch"

Failed to reconnect to peer. Beginning exponential backoff module=p2p addr=302b7472bb225c3d2acb4d6xxxxxxxxxxxxx4a3@xx.xxx.xx.xx:26656

can any one help me.
Thank you.
