### ISSUE TITLE
cant sync from snapshot

### ISSUE THREAD

**Issue by nivshitrit** [maticnetwork/heimdall#1013]
**Heimdall version** (use `heimdall version` or `git rev-parse --verify HEAD` if installed from source): 0.3.4

**Environment**: bash
- **OS** (e.g. from /etc/os-release): linux
- **Install tools**: kubernetes
- **Others**:

**What happened**: im trying to sync from snapshot on polygon-mumbai
i have downloaded the snapshot from here : https://snapshots.polygon.technology/
and then mounted it in `heimdall-home/data`, i then extracted the content of the download .txt file using this command:
`aria2c -x6 -s6 -i snapshot.txt
`
after running `unsafe-reset-all`, i did `init` again, then `start` again, but heimdall starts syncing from block zero.

**What you expected to happen**:
i expected it to start from some block that is closer to our current date

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible):
heimdall start --chain=mumbai --home=/heimdall-home

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:
```
INFO [2023-06-25|07:48:47.414] starting ABCI with Tendermint                module=main 
INFO [2023-06-25|07:48:47.415] Config file /heimdall-home/config/heimdall-config.toml already exists. Skip writing default heimdall config. module=cmd/heimdalld 
INFO [2023-06-25|07:48:47.415] Found genesis file /heimdall-home/config/genesis.json, skipping writing genesis file
 module=cmd/heimdalld 
DEBUG[2023-06-25|07:48:47.426] Invalid ETH RPC timeout provided, falling back to default value timeout=5s
DEBUG[2023-06-25|07:48:47.426] Invalid BOR RPC timeout provided, falling back to default value timeout=5s
```
after this it just starts syncing from block height 0

**Config (you can paste only the changes you've made)**:
the only changes i did was to set an etherum rpc url, and bor rpc url, which is irrelevant to this case
**node command runtime flags**:

**Comment by Raneet10** [comment]
Hi @nivshitrit did you follow the instructions here: https://wiki.polygon.technology/docs/operate/snapshot-instructions-heimdall-bor/ for downloading the snapshot ? Actually we have refactored the mechanism for downloading snapshots so it could be possible you're trying to do it the old way. Let me know if this helps!

**Comment by Raneet10** [comment]
Hey @nivshitrit closing this. Feel free to reopen if the issue reoccurs. Thanks!
