### ISSUE TITLE
heimdall in mumbai testnet doesn't connect to any seeds

### ISSUE THREAD

**Issue by rufin0615** [maticnetwork/heimdall#1023]
**Heimdall version** (use `heimdall version` or `git rev-parse --verify HEAD` if installed from source):
0.3.4

**Environment**:
- **OS** (e.g. from /etc/os-release): Amazon Linux 2023
- **Install tools**:
- **Others**:

**What happened**:
heimdall in mumbai testnet doesn't connect to any seeds

**What you expected to happen**:
connect and sync normally

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible):
Just follow this guide (binary and docker)
https://wiki.polygon.technology/docs/pos/operate/node/full-node-deployment

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:
```txt
ERROR[2023-07-21|04:22:22.694] Couldn't connect to any seeds                module=p2p 
ERROR[2023-07-21|04:22:50.692] Error dialing seed                           module=p2p err="dial tcp 54.147.31.250:26656: i/o timeout" seed=e72c0466a02ea43b2198bd3a9454b87a3ef0d77e@54.147.31.250:26656
ERROR[2023-07-21|04:22:51.693] Error dialing seed                           module=p2p err="dial tcp 34.226.134.117:26656: i/o timeout" seed=b302d1ddb21102e794b524d05152a7834da05bd1@34.226.134.117:26656
ERROR[2023-07-21|04:22:52.694] Error dialing seed                           module=p2p err="dial tcp 18.213.200.99:26656: i/o timeout" seed=9dfc12d9f39257cefc3d57a4d7302586e59a994e@18.213.200.99:26656
```

**Config (you can paste only the changes you've made)**:
```
sed -i 's|^seeds =.*|seeds = "e72c0466a02ea43b2198bd3a9454b87a3ef0d77e@54.147.31.250:26656,b302d1ddb21102e794b524d05152a7834da05bd1@34.226.134.117:26656,9dfc12d9f39257cefc3d57a4d7302586e59a994e@18.213.200.99:26656"|g' /var/lib/heimdall/config/config.toml
```

**node command runtime flags**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**:

**Comment by milc0x** [comment]
I also suffer from this issue when restarting heimdall process.
I noticed that blocks in mumbai testnet stopped producing yesterday.
Although the issue has been recovered, I wonder if the seed nodes of heimdall changed at that time.
If seed nodes were changed, please provide the new nodes to make heimdall sync normally.

**Comment by Raneet10** [comment]
Hey @rufin0615 @milc0x sorry that you faced this issue! We'll check internally if the node IDs have changed and let you know. Thanks for your patience!

**Comment by Raneet10** [comment]
Our seed node IDs did actually change. Could you try these and let us know ? : 
`9df7ae4bf9b996c0e3436ed4cd3050dbc5742a28@43.200.206.40:26656`, `d9275750bc877b0276c374307f0fd7eae1d71e35@54.216.248.9:26656`
We'll also get our docs updated soon. Sorry again for the trouble!

**Comment by leoenes** [comment]
Thank you very much @Raneet10. For me, it is working again.

**Comment by rufin0615** [comment]
@Raneet10 
Thank you. It works.

**Comment by Shockedshodan** [comment]
Hello! Sorry for commenting over there, but tried to run Mumbai testned node with this seeds `9df7ae4bf9b996c0e3436ed4cd3050dbc5742a28@43.200.206.40:26656, d9275750bc877b0276c374307f0fd7eae1d71e35@54.216.248.9:26656` and got EOF errors, and one of them is timeout, like in a rufin0615 opening post. Tried other seeds from other issues and still timeout or EOF errors. Maybe @Raneet10 may help me?
