### ISSUE TITLE
Heimdall does not publish include the merkle tree root hash in headers for blocks containing exactly one transaction

### ISSUE THREAD

**Issue by svenski123** [maticnetwork/heimdall#1026]
(Note this issue has been edited following further investigation which identified the underlying cause of the validation failures.)

Heimdall returns invalid merkle transaciton inclusion proofs for transactions from blocks containing only a single transaction and such transactions fail validation according to heimdallcli.

The problem occurs as the validation logic in Heimdall checks that the block header's data hash is equal to the root hash of the merkle tree.

When producing a block with more than one transactions, Heimdall computes a merkle tree of all of the transactions and stores it in the the block header's root hash field.

However when producing a block with only one transaction, Heimdall does not store the merkle tree root hash (which would be a leaf hash of the single transaction) but rather stores the transaction hash itself in the block header's root hash field.

For example:
```
# block 14923947 num_txs=1 tx e3f2de96c4a0e45524508700d947e3c0bb8ff2145c9828ffffc6cc6a88a8c749
$ heimdallcli --chain-id heimdall-137 query tx e3f2de96c4a0e45524508700d947e3c0bb8ff2145c9828ffffc6cc6a88a8c749
ERROR: Proof matches different data hash
```
In the transaction and related block extract below, note the "hash" from the transaction is the same as the "data_hash" from the block header and is different from the "proof_root_hash".
```
$ curl -sG -d hash=0xe3f2de96c4a0e45524508700d947e3c0bb8ff2145c9828ffffc6cc6a88a8c749 -d prove=true http://HEIMDALL_IP:26657/tx|jq -r '.result|{height,hash,proof_root_hash:.proof.root_hash}'
{
  "height": "14923947",
  "hash": "E3F2DE96C4A0E45524508700D947E3C0BB8FF2145C9828FFFFC6CC6A88A8C749",
  "proof_root_hash": "608E6C2206CC62785C5CBFD0FD5BEF31275A338EC02F841A0FAA96BB57888624"
}
$ curl -sG -d height=14923947 http://HEIMDALL_IP:26657/block|jq -r '.result.block.header|{
data_hash,num_txs}'
{
  "data_hash": "E3F2DE96C4A0E45524508700D947E3C0BB8FF2145C9828FFFFC6CC6A88A8C749",
  "num_txs": "1"
}
```
In the transaction and related block extract below (this time for a 5 transaction block), note the "hash" from the transaction is different than the "data_hash" from the block header which now matches the "proof_root_hash".
```
$ curl -sG -d hash=0x58d4c582d933dda5fbaabab55984dc2d11120c2c7d266a421070d276be4421a4 -d prove=true http://HEIMDALL_IP:26657/tx|jq -r '.result|{height,hash,proof_root_hash:.proof.root_hash}'
{
  "height": "14923963",
  "hash": "58D4C582D933DDA5FBAABAB55984DC2D11120C2C7D266A421070D276BE4421A4",
  "proof_root_hash": "80610AAA3717EEF5868C871A0194423E59FCEA5158CBEA02CE28008C0FB6E856"
}
$ curl -sG -d height=14923963 http://HEIMDALL_IP:26657/block|jq -r '.result.block.header|{data_hash,num_txs}'
{
  "data_hash": "80610AAA3717EEF5868C871A0194423E59FCEA5158CBEA02CE28008C0FB6E856",
  "num_txs": "5"
}
```
The heimdallcli tool can successfully validate the transaction as seen below.
```
# block 14923963 num_txs=5 tx 58d4c582d933dda5fbaabab55984dc2d11120c2c7d266a421070d276be4421a4
$ heimdallcli --chain-id heimdall-137 query tx 58d4c582d933dda5fbaabab55984dc2d11120c2c7d266a421070d276be4421a4
height: 14923963
txhash: 58D4C582D933DDA5FBAABAB55984DC2D11120C2C7D266A421070D276BE4421A4
code: 0
data: ""
rawlog: '[{"msg_index":0,"success":true,"log":"","events":[{"type":"message","attributes":[{"key":"action","value":"event-record"}]},{"type":"record","attributes":[{"key":"module","value":"clerk"},{"key":"record-id","value":"2731488"},{"key":"record-contract","value":"0x8397259c983751daf40400790063935a11afa28a"},{"key":"record-tx-hash","value":"0x48f88f73cf3f0cf901fbcccf01fa8b0da1aef3c91bf8d72e1b5a8d59fcf4770a"},{"key":"record-tx-log-index","value":"222"}]}]}]'
logs:
- msgindex: 0
  success: true
  log: ""
  events:
  - type: message
    attributes:
    - key: action
      value: event-record
  - type: record
    attributes:
    - key: module
      value: clerk
    - key: record-id
      value: "2731488"
    - key: record-contract
      value: 0x8397259c983751daf40400790063935a11afa28a
    - key: record-tx-hash
      value: 0x48f88f73cf3f0cf901fbcccf01fa8b0da1aef3c91bf8d72e1b5a8d59fcf4770a
    - key: record-tx-log-index
      value: "222"
info: ""
gaswanted: 1000000
gasused: 47277
codespace: ""
tx:
  msg:
    from: 0x2c74ca71679cf1299936d6104d825c965448907b
    txhash: 0x48f88f73cf3f0cf901fbcccf01fa8b0da1aef3c91bf8d72e1b5a8d59fcf4770a
    logindex: 222
    blocknumber: 17779461
    contractaddress: 0x8397259c983751daf40400790063935a11afa28a
    data: 0x00000000000000000000000086d26ed31556ea7694bd0cc4e674d7526f70511a0000000000000000000000002ad412a1df96434eed0779d2db4a8694a06132f800000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000044b52a6a7e1a2a3cb6001458379a920fe9058fcea34cb1689c5b8db2214a6da0309e8126840000000000000000000000000000000000000000000000000000000064c1796b00000000000000000000000000000000000000000000000000000000
    id: 2731488
    chainid: "137"
  signature: 0x442e5f7e4fecdc17fa7e6d3216d3e09674feea096c93860b33a08d0e7816b1875397f71fb58a960edebe09b42a911baf7a3768f5aca97f778b7c7b11e0f2a7b500
  memo: ""
timestamp: "2023-07-26T20:10:23Z"
events:
- type: message
  attributes:
  - key: action
    value: event-record
- type: record
  attributes:
  - key: module
    value: clerk
  - key: record-id
    value: "2731488"
  - key: record-contract
    value: 0x8397259c983751daf40400790063935a11afa28a
  - key: record-tx-hash
    value: 0x48f88f73cf3f0cf901fbcccf01fa8b0da1aef3c91bf8d72e1b5a8d59fcf4770a
  - key: record-tx-log-index
    value: "222"
```

**Comment by Raneet10** [comment]
Hey @svenski123 , thanks for reporting this! This [commit](https://github.com/maticnetwork/tendermint/commit/aa42854c513f4d2387d858ce84cda7e24e31ab22) brought in the check where , if `len(txs) = 1 ` , `txs.hash()` would return the hash of the (only) tx instead of the merkle root, which makes sense. As to why it fails validation is something that we need to check.

**Comment by VAIBHAVJINDAL3012** [comment]
Hi @svenski123, We checked from our side this doesn't have any issue on consensus part.
RPC is working fine for it.
https://tendermint-api.polygon.technology/tx?hash=0XE3F2DE96C4A0E45524508700D947E3C0BB8FF2145C9828FFFFC6CC6A88A8C749&prove=true

There might be some issue with CLI, which we will solve soon.

**Comment by svenski123** [comment]
The problem is that the transaction proofs returned by peppermint core.Tx() are invalid when the transaction is the only one in the block as the root hash in the proof doesn't match the hash in the block header.

The inclusion proof is added to the RPC response here:
https://github.com/tendermint/tendermint/blob/35581cf54ec436b8c37fabb43fdaa3f48339a170/rpc/core/tx.go#L41
https://github.com/maticnetwork/tendermint/blob/3e7c7f86ce9f8ed954a673de225c6ca537f0eaad/types/tx.go#L82

Note there is no exception made for one transaction only in core.Txs.Proof() as was done to core.Txs.Hash() in the commit above.

It's not clear to me what the motivation for replacing the merkle hash with the plain transaction hash for the single transaction case was. The comment above core.Txs.Hash() was not changed by the commit mentioned above that changed the hash for one transaction and as it states 'Hash returns the Merkle root hash of the transaction hashes' it is now misleading and incorrect for the len(txs) == 1 case.

It would be cleaner to use merkle tree hashes for all blocks including those with only one transactions as verification would be consistent and simpler however given that the chain is already live this would break consensus and necessitate a hard fork.

Alternatively the existing behaviour as implemented would need to be formalised and documented so that verification logic could be implemented properly. Note this would involve more than just returning the transaction hash as the root hash for single transaction blocks as it would no longer be internally consistent - I suppose the concept of a leaf node hash would need to be redefined for the single transaction case.

**Comment by VAIBHAVJINDAL3012** [comment]
Yes @svenski123 I agree to you point. We are working from our end to redefine and update the documentation.

**Comment by svenski123** [comment]
I have submitted a minimal PR #1030 addressing this issue. Draft for now to allow for comments, if any.

**Comment by VAIBHAVJINDAL3012** [comment]
Sure @svenski123 ,I will look into it.
