### ISSUE TITLE
New Snapshot not available

### ISSUE THREAD

**Issue by shanshan-999** [maticnetwork/heimdall#1036]
Hi,help me get there.
    I have a question,I don't know how to use the new snapshot file,What is the format of the new snapshot file?
    I try to use command:  cat heimdall-mainnet-snapshot-* > heimdall-mainnet-snapshot.tar
    then use command:  tar xvf  heimdall-mainnet-snapshot.tar
    The merged file has 248G,but after decompressing it, it was only 2.8GB
    Unable to use these snapshot files properly

root@3bac919dbee5:/data/snapshots/data# ll                                                                                                                                          
total 518103216                                                                                                                                                                     
drwxr-xr-x 3 root root         4096 Aug 18 07:50 ./                                                                                                                                 
drwxr-xr-x 4 root root           34 Aug 17 16:56 ../                                                                                                                                
-rw-r--r-- 1 root root         2653 Aug 17 12:37 heimdall-mainnet-parts.txt                                                                                                         
-rw-r--r-- 1 root root   1512029290 Aug 17 13:31 heimdall-mainnet-snapshot-2023-08-09-part-aa                                                                                       
-rw-r--r-- 1 root root    841078417 Aug 17 13:35 heimdall-mainnet-snapshot-2023-08-10-part-aa                                                                                       
-rw-r--r-- 1 root root   1704871552 Aug 17 13:38 heimdall-mainnet-snapshot-2023-08-11-part-aa                                                                                       
-rw-r--r-- 1 root root   1026585286 Aug 17 13:41 heimdall-mainnet-snapshot-2023-08-12-part-aa                                                                                       
-rw-r--r-- 1 root root    864561670 Aug 17 13:41 heimdall-mainnet-snapshot-2023-08-13-part-aa                                                                                       
-rw-r--r-- 1 root root   1845047202 Aug 17 13:41 heimdall-mainnet-snapshot-2023-08-14-part-aa                                                                                       
-rw-r--r-- 1 root root   1324035133 Aug 17 13:42 heimdall-mainnet-snapshot-2023-08-15-part-aa                                                                                       
-rw-r--r-- 1 root root   1096166978 Aug 17 13:42 heimdall-mainnet-snapshot-2023-08-16-part-aa                                                                                       
-rw-r--r-- 1 root root    630794312 Aug 17 13:42 heimdall-mainnet-snapshot-2023-08-17-part-aa                                                                                       
-rw-r--r-- 1 root root  26843545600 Aug 17 12:52 heimdall-mainnet-snapshot-bulk-2023-08-08-part-aa                                                                                  
-rw-r--r-- 1 root root  26843545600 Aug 17 12:55 heimdall-mainnet-snapshot-bulk-2023-08-08-part-ab                                                                                  
-rw-r--r-- 1 root root  26843545600 Aug 17 12:53 heimdall-mainnet-snapshot-bulk-2023-08-08-part-ac                                                                                  
-rw-r--r-- 1 root root  26843545600 Aug 17 13:01 heimdall-mainnet-snapshot-bulk-2023-08-08-part-ad                                                                                  
-rw-r--r-- 1 root root  26843545600 Aug 17 13:00 heimdall-mainnet-snapshot-bulk-2023-08-08-part-ae                                                                                  
-rw-r--r-- 1 root root  26843545600 Aug 17 13:01 heimdall-mainnet-snapshot-bulk-2023-08-08-part-af                                                                                  
-rw-r--r-- 1 root root  26843545600 Aug 17 13:10 heimdall-mainnet-snapshot-bulk-2023-08-08-part-ag                                                                                  
-rw-r--r-- 1 root root  26843545600 Aug 17 13:19 heimdall-mainnet-snapshot-bulk-2023-08-08-part-ah                                                                                  
-rw-r--r-- 1 root root  26843545600 Aug 17 13:22 heimdall-mainnet-snapshot-bulk-2023-08-08-part-ai                                                                                  
-rw-r--r-- 1 root root  12831750390 Aug 17 13:27 heimdall-mainnet-snapshot-bulk-2023-08-08-part-aj

root@3bac919dbee5:/data/snapshots/data# du -sh heimdall-mainnet-snapshot.tar                                                                                               
248G    heimdall-mainnet-snapshot.tar

root@3bac919dbee5:/data/snapshots/data# du -sh root                                                                                                                                 
2.8G       root

**Comment by anshalshukla** [comment]
Hey, please refer to [this](https://wiki.polygon.technology/docs/pos/reference/snapshot-instructions-heimdall-bor/). It already has a script that can be used to download as well as extract the snapshots.

**Comment by shanshan-999** [comment]
> Hey, please refer to [this](https://wiki.polygon.technology/docs/pos/reference/snapshot-instructions-heimdall-bor/). It already has a script that can be used to download as well as extract the snapshots.

Thanks for your reply.I downloaded it using the script here,download the completed snapshot file is shown above,these snapshot files have no an extension, I don't know what type of file,unlike previous snapshot files with tar.zst

**Comment by shanshan-999** [comment]
Thanks @anshalshukla I know from 'View script here'
