### ISSUE TITLE
heimdalld package tries to remove files it doesn't own

### ISSUE THREAD

**Issue by feld** [maticnetwork/heimdall#1054]
```
$ sudo apt remove heimdalld
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages will be REMOVED:
  heimdalld
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
(Reading database ... 69303 files and directories currently installed.)
Removing heimdalld (0.3.4) ...
Failed to stop heimdalld.service: Unit heimdalld.service not loaded.
dpkg: error processing package heimdalld (--remove):
 installed heimdalld package pre-removal script subprocess returned error exit status 5
dpkg: too many errors, stopping
Directory /var/lib/heimdall exists.
Errors were encountered while processing:
 heimdalld
Processing was halted because there were too many errors.
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

heimdalld package does not own `/var/lib/heimdall` nor does it have the `heimdalld.service`. These are installed by one of the config packages like `heimdalld-mainnet-sentry-config_v0.3.4-amd64.deb`.

The packaging is done incorrectly here.

**Comment by VAIBHAVJINDAL3012** [comment]
Have you stopped the Heimdall before removing it?

**Comment by feld** [comment]
How can I start the service when the systemd unit isn't even part of the package? :)

Take a fresh OS, install the heimdall package:

dpkg -i heimdalld-v0.3.4-amd64.deb

Now try to uninstall it and you'll get errors because it's trying to remove a directory and a service it does not own. Those pieces are actually owned by the **heimdalld-mainnet-sentry-config_v0.3.4-amd64.deb** package

**Comment by temaniarpit27** [comment]
@feld 
We will take a look into this. Thanks

**Comment by manav2401** [comment]
Addressed in https://github.com/maticnetwork/heimdall/pull/1064
