### ISSUE TITLE
heimdall can't sync because app hash not match in polygon mumbai

### ISSUE THREAD

**Issue by wangjiangw** [maticnetwork/heimdall#1056]
**Heimdall version** (use `heimdall version` or `git rev-parse --verify HEAD` if installed from source):
3.5.0
![image](https://github.com/maticnetwork/heimdall/assets/7013043/adf2e171-1e2e-4827-a741-7d2b7db52ffb)

**Environment**:
- **OS** (e.g. from /etc/os-release): 
- **Install tools**:
- **Others**:

![image](https://github.com/maticnetwork/heimdall/assets/7013043/857cde2b-5f37-4219-9491-242c7a6130c3)

**What happened**:

heimdall synced failed from latest snapshot.

when heimdall start from latest snapshot, the status is ：
![image](https://github.com/maticnetwork/heimdall/assets/7013043/5bb6e70e-2206-46bf-be38-6ceadabcbe0a)

after start, the heimdall will sync from other nodes, but after 2 blocks, sync failed.

**What you expected to happen**:

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible):

i don't know if this issue  can be reproduced in other place, in my node, i have update snapshot twice (different days), but it always sync failed after 2 block.

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:
![image](https://github.com/maticnetwork/heimdall/assets/7013043/bb4c8d8c-e125-4df5-bd4b-73481d035b1f)

**Config (you can paste only the changes you've made)**:

heimdall-config.toml
![image](https://github.com/maticnetwork/heimdall/assets/7013043/dc685d4f-c485-48bd-a18a-6a3c8e22a4fb)

**node command runtime flags**:

/home/polygon/heimdall/heimdalld start --home "/data2/heimdall"

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**:

**Comment by Liamlu28** [comment]
same error
heimdall
```
Sep 14 20:53:29 iZt4n1j4luhc59roqufo5pZ heimdalld[12826]: ERROR: failed to create new node: error during handshake: error on replay: Wrong Block.Header.AppHash.  Expected BCC3C660B7A95F9FFA0BDF8F6FA33291593AC40B40CF28F7A3D388F45F83B4BD, got 4677FA640D2C10BBCF585E2AF206129B342E1E17C508DE5D681E38226A511B3E
```

**Comment by VAIBHAVJINDAL3012** [comment]
@wangjiangw You need to update your node to v1.0.0-beta.
This tag contains the hardfork.

**Comment by wangjiangw** [comment]
> @wangjiangw @Liamlu28 You need to update your node to v1.0.0-beta. This tag contains the hardfork.

ok，i will try it today. i have a question, will the mumbai network always use the bin version larger than 1.0.0 ?
