### ISSUE TITLE
When will the Aalborg Hardfork occur on the Mainnet？

### ISSUE THREAD

**Issue by milc0x** [maticnetwork/heimdall#1063]
Based on the latest Heimdall release note (v1.0.1), there is a description related to the Aalborg hardfork. It states, "This release contains a new hardfork called Aalborg which will activate a milestone on the Polygon PoS chain, bringing faster and deterministic finality." Based on this information, it appears necessary to update Heimdall to v1.0.1 and Bor to v1.0.4 simultaneously. Failure to do so may result in being unable to catch up with the correct Polygon PoS chain after the Aalborg hardfork occurs.

However, upon checking the AalborgHeight on the Mainnet using the provided link (https://github.com/maticnetwork/heimdall/blob/fe190174aeba79b9ec6383c61c8fde2f961307b9/helper/config.go#L399), I discovered that the aalborgHeight is currently set at a past block height. There is also a note indicating that this height will change in the future.

Therefore, to confirm, it seems that the Aalborg hardfork will not be activated in the Heimdall v1.0.1 release but will occur in future releases after v1.0.1. Until a version is released that includes the activation, there is no immediate need to upgrade Heimdall.

**Comment by artree222** [comment]
15950759 is the block height of Heimdall, and the block height of the current Heimdall is below this value.

**Comment by artree222** [comment]
What I really want to know is if I upgrade heimdall to v1.0.1 and whether my nodes will be affected by the upcoming block height 15950759, for example, only a few nodes will upgrade clients to v1.0.1 and will my nodes be abnormal？

**Comment by milc0x** [comment]
@artree222 
Thanks for your reply.
As you mentioned, the block height 15950759 of Heimdall will occur in 19 days. I am also curious if this block height will be changed to a lower value in the next release of Heimdall.

**Comment by ssandeep** [comment]
Hi All,
You can find more info about Aalborg here: https://forum.polygon.technology/t/aalborg-upgrade-mainnet-timeline-update/12960
Apologies for missing to remove the comment in https://github.com/maticnetwork/heimdall/blob/fe190174aeba79b9ec6383c61c8fde2f961307b9/helper/config.go#L399
which will be removed soon.
