### ISSUE TITLE
/milestone/latest status=500

### ISSUE THREAD

**Issue by jerrybb** [maticnetwork/heimdall#1065]
Hi, we have upgraded today heimdall, heimdall-rest and bor.
Old versions: 
- bor: 0.4.0
- heimdall: 0.3.5

New versions:
- bor: 1.0.4
- heimdall: 1.0.1

Bor was upgraded first as per release notes instructions, heimdall has been upgraded afterwards.

There are repeating events in heimdall-rest logs.
INFO [2023-09-21|09:18:59.376] Served RPC HTTP response                     module=rest-server method=GET url=/milestone/latest status=500 duration=0 remoteAddr=172.16.167.4:45864

There are repeating events in bor logs.
WARN [09-22|04:11:10.611] an error while trying fetching from Heimdall attempt=5 error="error while fetching data from Heimdall: response code 500"
INFO [09-22|04:11:10.611] Retrying again in 5 seconds to fetch data from Heimdall path=/milestone/latest        attempt=5

Current bor status:
General
Num peers = 81
Sync mode = full

Current Header
Hash   = 0x87a06131c572092cdd1e82e25ad0d15180924c1b1b0ea2603420515a3c359c3e
Number = 47835508

Current Block
Hash   = 0x87a06131c572092cdd1e82e25ad0d15180924c1b1b0ea2603420515a3c359c3e
Number = 47835508

Syncing
Current block  = 47835508
Highest block  = 47835472
Starting block = 47835471

Forks
Name              Block     Enabled
Homestead         0         true
EIP150            0         true
EIP155            0         true
EIP158            0         true
Byzantium         0         true
Constantinople    0         true
Petersburg        0         true
Istanbul          3395000   true
MuirGlacier       3395000   true
Berlin            14750000  true
London            23850000  true
ArrowGlacier      0         false
GrayGlacier       0         false
MergeNetsplit     0         false
Jaipur            23850000  true
Delhi             38189056  true
ParallelUniverse  0         true
Indore            44934656  true

Kindly please advise how to fix this issue.
Jerry

**Comment by VAIBHAVJINDAL3012** [comment]
Hi @jerrybb 
Milestone is still not activated on Mainnet
It will activate after 9th october after the hardfork.

WARN [09-22|04:11:10.611] an error while trying fetching from Heimdall attempt=5 error="error while fetching data from Heimdall: response code 500"
INFO [09-22|04:11:10.611] Retrying again in 5 seconds to fetch data from Heimdall path=/milestone/latest attempt=5
These are expected logs till hardfork.

**Comment by jerrybb** [comment]
Hi @VAIBHAVJINDAL3012, thank you for your answer. I'll sleep better now since I know I can these ignore events :)
