### ISSUE TITLE
Inquiry about Migration Plans for Goerli Deprecation

### ISSUE THREAD

**Issue by milc0x** [maticnetwork/heimdall#1096]
I would like to inquire about the future plans for the successor testnet to goerli and the data changes associated with the migration. As goerli is scheduled for [deprecation](https://github.com/eth-clients/goerli), I am interested to know which testnet, between sepolia and holesky, Polygon intends to choose as the successor.

Furthermore, I would greatly appreciate it if you could provide insights into the data changes that will be involved in the migration process. Specifically, I am curious about any modifications, updates, or adjustments that developers and users should be aware of when transitioning from goerli to the chosen successor testnet. 

If there are any official documentation, migration guides, or resources available that outline the plans for the successor testnet and the associated data changes, I kindly request you to share the relevant links. This information would greatly assist developers like me in preparing for the upcoming transition.

**Comment by 0xsharma** [comment]
Hi @milc0x , 

Initially, we were exploring the migration the Mumbai Testnet to a different L1 chain but after internal discussions, we figured out the challenges involved( including mappings of tokens on L1 and L2) and the issues we will face with this approach. We concluded that the best way forward would be to start a brand new testnet and to this end, we have decided to spin up a new testnet for the PoS called Amoy Testnet using Sepolia Testnet as the L1. 

We have announced this in governance calls. You can expect the forum posts for the same soon.
