### ISSUE TITLE
v0.3.4 Fresh sync fails with: "failed to create new node: error during handshake: error on replay: Wrong Block.Header.AppHash."

### ISSUE THREAD

**Issue by Ethics3606** [maticnetwork/heimdall#1099]
Hi,

At height 8587012 sync fails and cannot be recovered. 'chain' has been set to mainnet since beginning. 

Rollback function does not rollback: "Rolled back state to height 8587012 and hash B524A829BFCB8ABB78D0BEB796DF5E770C4C23DDB632F6B6CB6048936F9161CA"

ERROR: failed to create new node: error during handshake: error on replay: Wrong Block.Header.AppHash.  Expected B524A829BFCB8ABB78D0BEB796DF5E770C4C23DDB632F6B6CB6048936F9161CA, got F614FBD4E1F3AB75D6E288ABC664F4D692AFC591E644829CB0C1AE9DC081E0B8

**Comment by temaniarpit27** [comment]
Please use the latest version and snapshot to fix the issue

**Comment by temaniarpit27** [comment]
Closing this for now. Please reopen if required
