### ISSUE TITLE
Milestone not in continuity

### ISSUE THREAD

**Issue by kaber2** [maticnetwork/heimdall#1107]
Running version 1.0.3, I first receive a tons of messages "Milestone not in continuity", followed by crashes in the RPC handler when calling GetMilestoneID() because SetMilestoneID() has never been called.

This is with a fresh sync of both bor and heimdall snapshots.

**Comment by temaniarpit27** [comment]
Can you please send the logs?

**Comment by kaber2** [comment]
Well, the bug is quite obviously the same as #1089.

Here are the logs from heimdalld:

_INFO [2023-11-16|13:03:19.754] Executed block                               module=state height=16392245 validTxs=1 invalidTxs=0
INFO [2023-11-16|13:03:19.790] Committed state                              module=state height=16392245 txs=1 appHash=F1D1C79FAF8166C454DE2D6AAF05C29FD84120C0550A21DAC24AA5483ADF0D7C
INFO [2023-11-16|13:03:26.265] Executed block                               module=state height=16392246 validTxs=0 invalidTxs=0
INFO [2023-11-16|13:03:26.306] Committed state                              module=state height=16392246 txs=0 appHash=F1D1C79FAF8166C454DE2D6AAF05C29FD84120C0550A21DAC24AA5483ADF0D7C
ERROR[2023-11-16|13:03:28.962] Stopping peer for error                      module=p2p peer="Peer{MConn{134.65.193.157:26656} c124ce0b508e8b9ed1c5b6957f362225659b5343 out}" err=EOF
ERROR[2023-11-16|13:03:29.276] Stopping peer for error                      module=p2p peer="Peer{MConn{74.63.216.190:26656} ab59e5a2cc1ac5ecd63ec28f79d1c263db0f89ca out}" err=EOF
ERROR[2023-11-16|13:03:29.276] Stopping peer for error                      module=p2p peer="Peer{MConn{69.162.111.10:26656} 5511c9e5c2e46ee5041ec0b6e3f4aeb5f0fd4190 out}" err=EOF
ERROR[2023-11-16|13:03:29.931] dialing failed (attempts: 5): dial tcp 54.172.174.165:26656: i/o timeout module=pex addr=eb38a3e6b527baab7173ce6161ab216687798f1a@54.172.174.165:26656
ERROR[2023-11-16|13:03:32.804] Milestone not in continuity                  module=Milestone lastMilestoneEndBlock=50012823 receivedMsgStartBlock=50012804
INFO [2023-11-16|13:03:32.806] Executed block                               module=state height=16392247 validTxs=0 invalidTxs=1
INFO [2023-11-16|13:03:32.848] Committed state                              module=state height=16392247 txs=1 appHash=CBBD726105C36ACA21A08E14FB98729C7D55E6F3753ED5E04EB1CDF7097B3D33
INFO [2023-11-16|13:03:39.086] Executed block                               module=state height=16392248 validTxs=0 invalidTxs=0
INFO [2023-11-16|13:03:39.130] Committed state                              module=state height=16392248 txs=0 appHash=CBBD726105C36ACA21A08E14FB98729C7D55E6F3753ED5E04EB1CDF7097B3D33
INFO [2023-11-16|13:03:47.447] Executed block                               module=state height=16392249 validTxs=0 invalidTxs=0
INFO [2023-11-16|13:03:47.514] Committed state                              module=state height=16392249 txs=0 appHash=CBBD726105C36ACA21A08E14FB98729C7D55E6F3753ED5E04EB1CDF7097B3D33
INFO [2023-11-16|13:03:53.660] Executed block                               module=state height=16392250 validTxs=0 invalidTxs=0
INFO [2023-11-16|13:03:53.708] Committed state                              module=state height=16392250 txs=0 appHash=CBBD726105C36ACA21A08E14FB98729C7D55E6F3753ED5E04EB1CDF7097B3D33_

While the REST server throws the same panic as in the bug mentioned above:

_ERROR[2023-11-14|18:22:51.536] Panic in RPC HTTP handler                    module=rest-server err="interface conversion: interface {} is nil, not string" stack="goroutine 97244 ..._

With the reason being that the milestone has never been set due to "not being in continuity".

I'm seeing the same behaviour on >20 servers. Is this actually working for you?

**Comment by temaniarpit27** [comment]
We have already taken this up and should fix with upcoming releases.

**Comment by kaber2** [comment]
Any news on this?

On top of the error stated above, I'm also experiencing frequent (every few minutes) heimdall /milestone/lastNoAck query timeouts, which apparently lead to stalls in block processing in bor:

> INFO [2023-11-29|12:29:36.745] Served RPC HTTP response                     module=rest-server method=GET url=/milestone/lastNoAck status=200 duration=4006 remoteAddr=127.0.0.1:55220

Overall, the blockchain node is pretty much unusable because of these frequent stalls.

**Comment by VAIBHAVJINDAL3012** [comment]
This feature is working fine for other nodes in the network, they are producing the milestone.

**Comment by kaber2** [comment]
So a couple of questions to help in debugging this.

First some log files. On the heimdall side, this is pretty much what repeats itself over time:

```
DEBUG[2023-12-05|22:24:17.945] Tx included in block                         block=18722712 tx=0xb29ceb55158137984fd34db2a92e8394bea7e52fd00c873b499c38741ded48f1
DEBUG[2023-12-05|22:24:17.947] Latest finalized block on main chain obtained Block=18722736 receiptblock=18722712
INFO [2023-12-05|22:24:17.949] Executed block                               module=state height=16645220 validTxs=1 invalidTxs=0
INFO [2023-12-05|22:24:17.973] Committed state                              module=state height=16645220 txs=1 appHash=66478B040EFDEB22B17F93D85998BB61810AA199F37EE3239F8B23320059177F
INFO [2023-12-05|22:24:24.498] Executed block                               module=state height=16645221 validTxs=0 invalidTxs=0
INFO [2023-12-05|22:24:24.532] Committed state                              module=state height=16645221 txs=0 appHash=66478B040EFDEB22B17F93D85998BB61810AA199F37EE3239F8B23320059177F
DEBUG[2023-12-05|22:24:31.314] [ENDBLOCK] Updated current validator set     module=app proposer="Validator{87 1EFECB61A2F80AA34D3B9218B564A64D05946290 0x0404a438fa6b5033aa83847d283aedc67ca862c4183b837b664489e38f141d9fe92aaee18976acbcbbbaa137ecd350a9fe5b37bb851156f2a077500b5e742ca3ec VP:109006978 A:-1098947925}"
INFO [2023-12-05|22:24:31.315] Executed block                               module=state height=16645222 validTxs=0 invalidTxs=0
INFO [2023-12-05|22:24:31.320] Updates to validators                        module=state updates=B95D435DF3F8B2A8D8B9C2B7C8766C9AE6ED8CC9:39758725
INFO [2023-12-05|22:24:31.375] Committed state                              module=state height=16645222 txs=0 appHash=13CCE5C50C543AB908EC2A37042BF8F2D942E0F28F6490CD48B163665B740BF3
INFO [2023-12-05|22:24:38.692] Executed block                               module=state height=16645223 validTxs=0 invalidTxs=0
INFO [2023-12-05|22:24:38.710] Committed state                              module=state height=16645223 txs=0 appHash=13CCE5C50C543AB908EC2A37042BF8F2D942E0F28F6490CD48B163665B740BF3
INFO [2023-12-05|22:24:45.309] Executed block                               module=state height=16645224 validTxs=0 invalidTxs=0
INFO [2023-12-05|22:24:45.332] Committed state                              module=state height=16645224 txs=0 appHash=13CCE5C50C543AB908EC2A37042BF8F2D942E0F28F6490CD48B163665B740BF3
INFO [2023-12-05|22:24:51.492] Executed block                               module=state height=16645225 validTxs=0 invalidTxs=0
INFO [2023-12-05|22:24:51.509] Committed state                              module=state height=16645225 txs=0 appHash=13CCE5C50C543AB908EC2A37042BF8F2D942E0F28F6490CD48B163665B740BF3
DEBUG[2023-12-05|22:24:58.056] Tx included in block                         block=18722709 tx=0xeef8ab9631be7dba5833709e5629caf5b232da12923788780b2d88bb2067caff
DEBUG[2023-12-05|22:24:58.058] Latest finalized block on main chain obtained Block=18722736 receiptblock=18722709
DEBUG[2023-12-05|22:24:58.063] Tx included in block                         block=18722729 tx=0x2e8ea4a06fdbefa5c83e400251ca9962dd7f3653f1e5101e83be089ae81670a2
DEBUG[2023-12-05|22:24:58.065] Latest finalized block on main chain obtained Block=18722736 receiptblock=18722729
DEBUG[2023-12-05|22:24:58.069] Tx included in block                         block=18722736 tx=0xe104e88ca2be66844ca268a16f9557743788fbb252484262bd6fb76329ea26fc
DEBUG[2023-12-05|22:24:58.071] Latest finalized block on main chain obtained Block=18722736 receiptblock=18722736
DEBUG[2023-12-05|22:24:58.071] Tx included in block                         block=18722736 tx=0xe104e88ca2be66844ca268a16f9557743788fbb252484262bd6fb76329ea26fc
DEBUG[2023-12-05|22:24:58.072] Latest finalized block on main chain obtained Block=18722736 receiptblock=18722736
DEBUG[2023-12-05|22:24:58.078] Tx included in block                         block=18722718 tx=0xe0a6151d3b0a18d3965ab0b0e76194bed44a2512060148dcfce0cda0260a4285
DEBUG[2023-12-05|22:24:58.079] Latest finalized block on main chain obtained Block=18722736 receiptblock=18722718
INFO [2023-12-05|22:24:58.081] Executed block                               module=state height=16645226 validTxs=5 invalidTxs=0
INFO [2023-12-05|22:24:58.106] Committed state                              module=state height=16645226 txs=5 appHash=20CB4996B5D72DC598ED3255B9A4993E6C3C15F9A14D921BB3520E88C0C25402
ERROR[2023-12-05|22:25:09.940] Error validating milestone                   module=Milestone startBlock=50784723 endBlock=50784758 hash=0x889369ec8fb7aa37e088cb0aa424b428b5e33f3524cd93ec70f5e1daf55a6321 milestoneId="88d841b9-5099-4a7c-8446-e10086f8bcb0 - 0xa424b428b5e33f3524cd93ec70f5e1daf55a6321" error="Error in fetching vote from matic chainerrPost \"http://localhost:8545\": context deadline exceeded"
ERROR[2023-12-05|22:25:09.940] Hash is not valid                            module=Milestone startBlock=50784723 endBlock=50784758 hash=0x889369ec8fb7aa37e088cb0aa424b428b5e33f3524cd93ec70f5e1daf55a6321 milestoneId="88d841b9-5099-4a7c-8446-e10086f8bcb0 - 0xa424b428b5e33f3524cd93ec70f5e1daf55a6321"
INFO [2023-12-05|22:25:09.942] Executed block                               module=state height=16645227 validTxs=1 invalidTxs=0
INFO [2023-12-05|22:25:09.969] Committed state                              module=state height=16645227 txs=1 appHash=7AC3B0F8C088201A44301CE9D16605212E3434DBD089EC36BC3723429A4DBEBF
ERROR[2023-12-05|22:25:13.364] Previous milestone still in voting phase     module=Milestone previousMilestoneBlock=16645227 currentMilestoneBlock=16645228
DEBUG[2023-12-05|22:25:13.365] [ENDBLOCK] Updated current validator set     module=app proposer="Validator{87 1EFECB61A2F80AA34D3B9218B564A64D05946290 0x0404a438fa6b5033aa83847d283aedc67ca862c4183b837b664489e38f141d9fe92aaee18976acbcbbbaa137ecd350a9fe5b37bb851156f2a077500b5e742ca3ec VP:109006978 A:-1098947925}"
INFO [2023-12-05|22:25:13.366] Executed block                               module=state height=16645228 validTxs=0 invalidTxs=5
```

and finally this:

```
ERROR[2023-12-05|22:33:20.941] Error validating milestone                   module=Milestone startBlock=50784970 endBlock=50784989 hash=0xc902d878cb7317570438e8667816574e4059b7a2c45d593d8d0d3e756e1e8e0a milestoneId="30f1c2f6-d434-4e53-9ef8-3b55eb1b7ac7 - 0x7816574e4059b7a2c45d593d8d0d3e756e1e8e0a" error="Error in fetching vote from matic chainerrPost \"http://localhost:8545\": context deadline exceeded"
ERROR[2023-12-05|22:33:20.941] Hash is not valid                            module=Milestone startBlock=50784970 endBlock=50784989 hash=0xc902d878cb7317570438e8667816574e4059b7a2c45d593d8d0d3e756e1e8e0a milestoneId="30f1c2f6-d434-4e53-9ef8-3b55eb1b7ac7 - 0x7816574e4059b7a2c45d593d8d0d3e756e1e8e0a"
INFO [2023-12-05|22:33:20.943] Executed block                               module=state height=16645301 validTxs=1 invalidTxs=0
INFO [2023-12-05|22:33:20.979] Committed state                              module=state height=16645301 txs=1 appHash=E25AFBE623BF7F172D225E0EB5B086EC034463486A5B167CD2DEE874F04AFAB8
INFO [2023-12-05|22:33:22.531] Executed block                               module=state height=16645302 validTxs=0 invalidTxs=0
INFO [2023-12-05|22:33:22.555] Committed state                              module=state height=16645302 txs=0 appHash=E25AFBE623BF7F172D225E0EB5B086EC034463486A5B167CD2DEE874F04AFAB8
ERROR[2023-12-05|22:33:29.023] Milestone not in continuity                  module=Milestone lastMilestoneEndBlock=50784989 receivedMsgStartBlock=50784970
INFO [2023-12-05|22:33:29.025] Executed block                               module=state height=16645303 validTxs=0 invalidTxs=1
```

At the same time, on the bor side, I see:

```
WARN [12-05|22:33:15.941] an error while trying fetching from Heimdall path="/milestone/ID/30f1c2f6-d434-4e53-9ef8-3b55eb1b7ac7 - 0x7816574e4059b7a2c45d593d8d0d3e756e1e8e0a" attempt=1 error="error while fetching data from Heimdall: response code 400"
WARN [12-05|22:33:15.941] Retrying again in 5 seconds to fetch data from Heimdall path="/milestone/ID/30f1c2f6-d434-4e53-9ef8-3b55eb1b7ac7 - 0x7816574e4059b7a2c45d593d8d0d3e756e1e8e0a" attempt=1
```

and 5 seconds later:
```
WARN [12-05|22:33:20.941] Served bor_getVoteOnHash                 conn=127.0.0.1:37772 reqid=24    duration=5.000084939s err="Milestone ID doesn't exist in Heimdall: context canceled"
```

So the root cause for the failure appears to be that heimdall does not respond to the /milestone/ID request, however I'm not sure I understand the interplay between them properly.

So first question, the bor error seems to indicate that the request timed out within heimdall. What might cause this? This particular example is heimdall running on a rotating disk, but the logs from an NVME look identical.

Second question regarding "Milestone not in continuity" - as heimdall seems to require a running bor instance to validate the milestones, what would happen if bor were down? When last replacing the heimdall snapshot, the bor snapshot was still downloading, so I started heimdall before bor to get going with syncing the missing blocks. Could this be responsible for the "not in continuity" error, and would heimdall be capable of recovering from running a while without a running bor instance?

Thanks!

**Comment by koraykoska** [comment]
Are there any updates?

**Comment by VAIBHAVJINDAL3012** [comment]
HI @koraykoska,There is no link between "Milestone not in continuity" error log and RPC handler failure.

And also going down the line we are going to remove the GetMilestoneID() rest function.

**Comment by temaniarpit27** [comment]
Closing this issue as it seems to work fine and improvements will be included in upcoming releases
