### ISSUE TITLE
panic: Error initializing DB: open /var/lib/heimdall/data/blockstore.db/LOCK: permission denied

### ISSUE THREAD

**Issue by BoogalooLi** [maticnetwork/heimdall#1113]
**Heimdall version** (use `heimdall version` or `git rev-parse --verify HEAD` if installed from source):

**Environment**:
- **OS** (e.g. from /etc/os-release):
- **Install tools**: packages
- **Others**:

**What happened**:
after downloading the snapshot and run it as shown in the doc https://wiki.polygon.technology/docs/pos/reference/snapshot-instructions-heimdall-bor/
panic: Error initializing DB: open /var/lib/heimdall/data/blockstore.db/LOCK: permission denied

**What you expected to happen**:

**Have you tried the latest version**: yes/no
yes
**How to reproduce it** (as minimally and precisely as possible):

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:
Nov 27 07:55:35 aiftblockchaina1 heimdalld[3005614]: DEBUG[2023-11-27|07:55:35.750] Missing ETH RPC timeout or invalid value provided, falling back to default timeout=>
Nov 27 07:55:35 aiftblockchaina1 heimdalld[3005614]:  module=cmd/heimdalld
Nov 27 07:55:35 aiftblockchaina1 heimdalld[3005614]: DEBUG[2023-11-27|07:55:35.750] Missing ETH RPC timeout or invalid value provided, falling back to default timeout=>
Nov 27 07:55:35 aiftblockchaina1 heimdalld[3005614]: DEBUG[2023-11-27|07:55:35.750] Missing BOR RPC timeout or invalid value provided, falling back to default timeout=>
Nov 27 07:55:35 aiftblockchaina1 heimdalld[3005614]: DEBUG[2023-11-27|07:55:35.751] ABI initialized                              name="[{\"constant\":true,\"inputs\":[>
Nov 27 07:55:35 aiftblockchaina1 heimdalld[3005614]: DEBUG[2023-11-27|07:55:35.753] ABI initialized                              name="[{\"constant\":false,\"inputs\":>
Nov 27 07:55:35 aiftblockchaina1 heimdalld[3005614]: DEBUG[2023-11-27|07:55:35.753] ABI initialized                              name="[{\"constant\":true,\"inputs\":[>
Nov 27 07:55:35 aiftblockchaina1 heimdalld[3005614]: DEBUG[2023-11-27|07:55:35.753] ABI initialized                              name="[{\"constant\":true,\"inputs\":[>
Nov 27 07:55:35 aiftblockchaina1 heimdalld[3005614]: DEBUG[2023-11-27|07:55:35.753] ABI initialized                              name="[{\"constant\":false,\"inputs\":>
Nov 27 07:55:35 aiftblockchaina1 heimdalld[3005614]: DEBUG[2023-11-27|07:55:35.755] ABI initialized                              name="[{\"constant\":true,\"inputs\":[>
Nov 27 07:55:35 aiftblockchaina1 heimdalld[3005614]: DEBUG[2023-11-27|07:55:35.755] ABI initialized                              name="[{\"constant\":true,\"inputs\":[>
Nov 27 07:55:35 aiftblockchaina1 heimdalld[3005614]: DEBUG[2023-11-27|07:55:35.755] ABI initialized                              name="[{\"anonymous\":false,\"inputs\">
Nov 27 07:55:35 aiftblockchaina1 heimdalld[3005614]: panic: Error initializing DB: open /var/lib/heimdall/data/blockstore.db/LOCK: permission denied

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**:

**Comment by BoogalooLi** [comment]
-rwxrwxrwx 1 heimdall nogroup       0 Nov 27 07:36 LOCK*

**Comment by VAIBHAVJINDAL3012** [comment]
Closing it for now, reopen it if it not resolved.
