### ISSUE TITLE
heimdall Error dialing seed（v1.0.2)

### ISSUE THREAD

**Issue by zyx0355** [maticnetwork/heimdall#1119]
ERROR[2023-12-17|07:48:25.971] Error dialing seed                           module=p2p err="dial tcp 52.209.21.164:26656: i/o timeout" seed=6726b826df45ac8e9afb4bdb2469c7771bd797f1@52.209.21.164:26656
ERROR[2023-12-17|07:48:26.971] Error dialing seed                           module=p2p err="dial tcp 3.36.224.80:26656: i/o timeout" seed=dd4a3f1750af5765266231b9d8ac764599921736@3.36.224.80:26656
ERROR[2023-12-17|07:48:27.972] Error dialing seed                           module=p2p err="dial tcp 52.78.36.216:26656: i/o timeout" seed=1500161dd491b67fb1ac81868952be49e2509c9f@52.78.36.216:26656
ERROR[2023-12-17|07:48:28.973] Error dialing seed                           module=p2p err="dial tcp 34.240.245.39:26656: i/o timeout" seed=8ea4f592ad6cc38d7532aff418d1fb97052463af@34.240.245.39:26656
ERROR[2023-12-17|07:48:29.973] Error dialing seed                           module=p2p err="dial tcp 54.194.245.5:26656: i/o timeout" seed=e772e1fb8c3492a9570a377a5eafdb1dc53cd778@54.194.245.5:26656
ERROR[2023-12-17|07:48:29.973] Couldn't connect to any seeds                module=p2p
ERROR[2023-12-17|07:48:55.970] Error dialing seed                           module=p2p err="dial tcp 52.78.36.216:26656: i/o timeout" seed=1500161dd491b67fb1ac81868952be49e2509c9f@52.78.36.216:26656
ERROR[2023-12-17|07:48:56.971] Error dialing seed                           module=p2p err="dial tcp 34.240.245.39:26656: i/o timeout" seed=8ea4f592ad6cc38d7532aff418d1fb97052463af@34.240.245.39:26656
ERROR[2023-12-17|07:48:57.971] Error dialing seed                           module=p2p err="dial tcp 52.209.21.164:26656: i/o timeout" seed=6726b826df45ac8e9afb4bdb2469c7771bd797f1@52.209.21.164:26656
ERROR[2023-12-17|07:48:58.973] Error dialing seed                           module=p2p err="dial tcp 54.194.245.5:26656: i/o timeout" seed=e772e1fb8c3492a9570a377a5eafdb1dc53cd778@54.194.245.5:26656
ERROR[2023-12-17|07:48:59.974] Error dialing seed                           module=p2p err="dial tcp 3.36.224.80:26656: i/o timeout" seed=dd4a3f1750af5765266231b9d8ac764599921736@3.36.224.80:26656
ERROR[2023-12-17|07:48:59.974] Couldn't connect to any seeds                module=p2p
ERROR[2023-12-17|07:49:25.969] Error dialing seed                           module=p2p err="dial tcp 54.194.245.5:26656: i/o timeout" seed=e772e1fb8c3492a9570a377a5eafdb1dc53cd778@54.194.245.5:26656
ERROR[2023-12-17|07:49:26.970] Error dialing seed                           module=p2p err="dial tcp 34.240.245.39:26656: i/o timeout" seed=8ea4f592ad6cc38d7532aff418d1fb97052463af@34.240.245.39:26656
ERROR[2023-12-17|07:49:27.971] Error dialing seed                           module=p2p err="dial tcp 3.36.224.80:26656: i/o timeout" seed=dd4a3f1750af5765266231b9d8ac764599921736@3.36.224.80:26656
ERROR[2023-12-17|07:49:28.973] Error dialing seed                           module=p2p err="dial tcp 52.78.36.216:26656: i/o timeout" seed=1500161dd491b67fb1ac81868952be49e2509c9f@52.78.36.216:26656
ERROR[2023-12-17|07:49:29.973] Error dialing seed                           module=p2p err="dial tcp 52.209.21.164:26656: i/o timeout" seed=6726b826df45ac8e9afb4bdb2469c7771bd797f1@52.209.21.164:26656
ERROR[2023-12-17|07:49:29.973] Couldn't connect to any seeds                module=p2p
ERROR[2023-12-17|07:49:55.970] Error dialing seed                           module=p2p err="dial tcp 34.240.245.39:26656: i/o timeout" seed=8ea4f592ad6cc38d7532aff418d1fb97052463af@34.240.245.39:26656
ERROR[2023-12-17|07:49:56.970] Error dialing seed                           module=p2p err="dial tcp 3.36.224.80:26656: i/o timeout" seed=dd4a3f1750af5765266231b9d8ac764599921736@3.36.224.80:26656
ERROR[2023-12-17|07:49:57.971] Error dialing seed                           module=p2p err="dial tcp 54.194.245.5:26656: i/o timeout" seed=e772e1fb8c3492a9570a377a5eafdb1dc53cd778@54.194.245.5:26656
ERROR[2023-12-17|07:49:58.971] Error dialing seed                           module=p2p err="dial tcp 52.209.21.164:26656: i/o timeout" seed=6726b826df45ac8e9afb4bdb2469c7771bd797f1@52.209.21.164:26656
ERROR[2023-12-17|07:49:59.972] Error dialing seed                           module=p2p err="dial tcp 52.78.36.216:26656: i/o timeout" seed=1500161dd491b67fb1ac81868952be49e2509c9f@52.78.36.216:26656
ERROR[2023-12-17|07:49:59.972] Couldn't connect to any seeds                module=p2p
ERROR[2023-12-17|07:50:25.970] Error dialing seed                           module=p2p err="dial tcp 52.78.36.216:26656: i/o timeout" seed=1500161dd491b67fb1ac81868952be49e2509c9f@52.78.36.216:26656
ERROR[2023-12-17|07:50:26.972] Error dialing seed                           module=p2p err="dial tcp 34.240.245.39:26656: i/o timeout" seed=8ea4f592ad6cc38d7532aff418d1fb97052463af@34.240.245.39:26656
ERROR[2023-12-17|07:50:27.973] Error dialing seed                           module=p2p err="dial tcp 52.209.21.164:26656: i/o timeout" seed=6726b826df45ac8e9afb4bdb2469c7771bd797f1@52.209.21.164:26656
ERROR[2023-12-17|07:50:28.974] Error dialing seed                           module=p2p err="dial tcp 3.36.224.80:26656: i/o timeout" seed=dd4a3f1750af5765266231b9d8ac764599921736@3.36.224.80:26656
ERROR[2023-12-17|07:50:29.974] Error dialing seed                           module=p2p err="dial tcp 54.194.245.5:26656: i/o timeout" seed=e772e1fb8c3492a9570a377a5eafdb1dc53cd778@54.194.245.5:26656
ERROR[2023-12-17|07:50:29.974] Couldn't connect to any seeds                module=p2p
ERROR[2023-12-17|07:50:55.971] Error dialing seed                           module=p2p err="dial tcp 54.194.245.5:26656: i/o timeout" seed=e772e1fb8c3492a9570a377a5eafdb1dc53cd778@54.194.245.5:26656
ERROR[2023-12-17|07:50:56.971] Error dialing seed                           module=p2p err="dial tcp 34.240.245.39:26656: i/o timeout" seed=8ea4f592ad6cc38d7532aff418d1fb97052463af@34.240.245.39:26656
ERROR[2023-12-17|07:50:57.972] Error dialing seed                           module=p2p err="dial tcp 52.78.36.216:26656: i/o timeout" seed=1500161dd491b67fb1ac81868952be49e2509c9f@52.78.36.216:26656
ERROR[2023-12-17|07:50:58.972] Error dialing seed                           module=p2p err="dial tcp 52.209.21.164:26656: i/o timeout" seed=6726b826df45ac8e9afb4bdb2469c7771bd797f1@52.209.21.164:26656
ERROR[2023-12-17|07:50:59.973] Error dialing seed                           module=p2p err="dial tcp 3.36.224.80:26656: i/o timeout" seed=dd4a3f1750af5765266231b9d8ac764599921736@3.36.224.80:26656
ERROR[2023-12-17|07:50:59.973] Couldn't connect to any seeds                module=p2p
**Heimdall version** (use `heimdall version` or `git rev-parse --verify HEAD` if installed from source):
v1.0.2

**Environment**:
- **OS** (e.g. from /etc/os-release):
- **Install tools**:
- **Others**:
centos

**What happened**:
heimdall's heimdalld cannot connect to seeds

**What you expected to happen**:
solve this problem：heimdall's heimdalld cannot connect to seeds

**Have you tried the latest version**: yes/no
My heimdall's version is v1.0.2
**How to reproduce it** (as minimally and precisely as possible):

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:
ERROR[2023-12-17|07:51:25.970] Error dialing seed                           module=p2p err="dial tcp 54.194.245.5:26656: i/o timeout" seed=e772e1fb8c3492a9570a377a5eafdb1dc53cd778@54.194.245.5:26656
ERROR[2023-12-17|07:51:26.971] Error dialing seed                           module=p2p err="dial tcp 34.240.245.39:26656: i/o timeout" seed=8ea4f592ad6cc38d7532aff418d1fb97052463af@34.240.245.39:26656
ERROR[2023-12-17|07:51:27.971] Error dialing seed                           module=p2p err="dial tcp 52.209.21.164:26656: i/o timeout" seed=6726b826df45ac8e9afb4bdb2469c7771bd797f1@52.209.21.164:26656
ERROR[2023-12-17|07:51:28.972] Error dialing seed                           module=p2p err="dial tcp 52.78.36.216:26656: i/o timeout" seed=1500161dd491b67fb1ac81868952be49e2509c9f@52.78.36.216:26656
ERROR[2023-12-17|07:51:29.973] Error dialing seed                           module=p2p err="dial tcp 3.36.224.80:26656: i/o timeout" seed=dd4a3f1750af5765266231b9d8ac764599921736@3.36.224.80:26656
ERROR[2023-12-17|07:51:29.973] Couldn't connect to any seeds                module=p2p
ERROR[2023-12-17|07:51:55.969] Error dialing seed                           module=p2p err="dial tcp 54.194.245.5:26656: i/o timeout" seed=e772e1fb8c3492a9570a377a5eafdb1dc53cd778@54.194.245.5:26656
ERROR[2023-12-17|07:51:56.970] Error dialing seed                           module=p2p err="dial tcp 34.240.245.39:26656: i/o timeout" seed=8ea4f592ad6cc38d7532aff418d1fb97052463af@34.240.245.39:26656
ERROR[2023-12-17|07:51:57.971] Error dialing seed                           module=p2p err="dial tcp 52.78.36.216:26656: i/o timeout" seed=1500161dd491b67fb1ac81868952be49e2509c9f@52.78.36.216:26656
ERROR[2023-12-17|07:51:58.971] Error dialing seed                           module=p2p err="dial tcp 3.36.224.80:26656: i/o timeout" seed=dd4a3f1750af5765266231b9d8ac764599921736@3.36.224.80:26656
ERROR[2023-12-17|07:51:59.972] Error dialing seed                           module=p2p err="dial tcp 52.209.21.164:26656: i/o timeout" seed=6726b826df45ac8e9afb4bdb2469c7771bd797f1@52.209.21.164:26656
ERROR[2023-12-17|07:51:59.972] Couldn't connect to any seeds                module=p2p
ERROR[2023-12-17|07:52:25.970] Error dialing seed                           module=p2p err="dial tcp 52.78.36.216:26656: i/o timeout" seed=1500161dd491b67fb1ac81868952be49e2509c9f@52.78.36.216:26656
ERROR[2023-12-17|07:52:26.970] Error dialing seed                           module=p2p err="dial tcp 54.194.245.5:26656: i/o timeout" seed=e772e1fb8c3492a9570a377a5eafdb1dc53cd778@54.194.245.5:26656
ERROR[2023-12-17|07:52:27.970] Error dialing seed                           module=p2p err="dial tcp 3.36.224.80:26656: i/o timeout" seed=dd4a3f1750af5765266231b9d8ac764599921736@3.36.224.80:26656
ERROR[2023-12-17|07:52:28.971] Error dialing seed                           module=p2p err="dial tcp 34.240.245.39:26656: i/o timeout" seed=8ea4f592ad6cc38d7532aff418d1fb97052463af@34.240.245.39:26656
ERROR[2023-12-17|07:52:29.972] Error dialing seed                           module=p2p err="dial tcp 52.209.21.164:26656: i/o timeout" seed=6726b826df45ac8e9afb4bdb2469c7771bd797f1@52.209.21.164:26656
ERROR[2023-12-17|07:52:29.972] Couldn't connect to any seeds                module=p2p
ERROR[2023-12-17|07:52:55.970] Error dialing seed                           module=p2p err="dial tcp 52.78.36.216:26656: i/o timeout" seed=1500161dd491b67fb1ac81868952be49e2509c9f@52.78.36.216:26656
ERROR[2023-12-17|07:52:56.971] Error dialing seed                           module=p2p err="dial tcp 34.240.245.39:26656: i/o timeout" seed=8ea4f592ad6cc38d7532aff418d1fb97052463af@34.240.245.39:26656
ERROR[2023-12-17|07:52:57.972] Error dialing seed                           module=p2p err="dial tcp 54.194.245.5:26656: i/o timeout" seed=e772e1fb8c3492a9570a377a5eafdb1dc53cd778@54.194.245.5:26656
ERROR[2023-12-17|07:52:58.972] Error dialing seed                           module=p2p err="dial tcp 52.209.21.164:26656: i/o timeout" seed=6726b826df45ac8e9afb4bdb2469c7771bd797f1@52.209.21.164:26656
ERROR[2023-12-17|07:52:59.973] Error dialing seed                           module=p2p err="dial tcp 3.36.224.80:26656: i/o timeout" seed=dd4a3f1750af5765266231b9d8ac764599921736@3.36.224.80:26656
ERROR[2023-12-17|07:52:59.973] Couldn't connect to any seeds                module=p2p
ERROR[2023-12-17|07:53:25.970] Error dialing seed                           module=p2p err="dial tcp 34.240.245.39:26656: i/o timeout" seed=8ea4f592ad6cc38d7532aff418d1fb97052463af@34.240.245.39:26656
ERROR[2023-12-17|07:53:26.971] Error dialing seed                           module=p2p err="dial tcp 3.36.224.80:26656: i/o timeout" seed=dd4a3f1750af5765266231b9d8ac764599921736@3.36.224.80:26656
ERROR[2023-12-17|07:53:27.972] Error dialing seed                           module=p2p err="dial tcp 52.209.21.164:26656: i/o timeout" seed=6726b826df45ac8e9afb4bdb2469c7771bd797f1@52.209.21.164:26656
ERROR[2023-12-17|07:53:28.972] Error dialing seed                           module=p2p err="dial tcp 52.78.36.216:26656: i/o timeout" seed=1500161dd491b67fb1ac81868952be49e2509c9f@52.78.36.216:26656
ERROR[2023-12-17|07:53:29.973] Error dialing seed                           module=p2p err="dial tcp 54.194.245.5:26656: i/o timeout" seed=e772e1fb8c3492a9570a377a5eafdb1dc53cd778@54.194.245.5:26656

**Config (you can paste only the changes you've made)**:
# Comma separated list of seed nodes to connect to
seeds="1500161dd491b67fb1ac81868952be49e2509c9f@52.78.36.216:26656,dd4a3f1750af5765266231b9d8ac764599921736@3.36.224.80:26656,8ea4f592ad6cc38d7532aff418d1fb97052463af@34.240.245.39:26656,e772e1fb8c3492a9570a377a5eafdb1dc53cd778@54.194.245.5:26656,6726b826df45ac8e9afb4bdb2469c7771bd797f1@52.209.21.164:26656"
# UPNP port forwarding
upnp = false

# Path to address book
addr_book_file = "config/addrbook.json"

# Set true for strict address routability rules
# Set false for private or local networks
addr_book_strict = true

# Maximum number of inbound peers
max_num_inbound_peers = 100

# Maximum number of outbound peers to connect to, excluding persistent peers
max_num_outbound_peers = 100

# Time to wait before flushing messages out on the connection
flush_throttle_timeout = "100ms"

# Maximum size of a message packet payload, in bytes
max_packet_msg_payload_size = 1024

# Rate at which packets can be sent, in bytes/second
send_rate = 5120000

**Comment by pratikspatil024** [comment]
Hi @zyx0355, sometimes it takes some time to connect to the seed nodes. The seed nodes that you are using are the correct ones.
```
seeds="1500161dd491b67fb1ac81868952be49e2509c9f@52.78.36.216:26656,dd4a3f1750af5765266231b9d8ac764599921736@3.36.224.80:26656,8ea4f592ad6cc38d7532aff418d1fb97052463af@34.240.245.39:26656,e772e1fb8c3492a9570a377a5eafdb1dc53cd778@54.194.245.5:26656,6726b826df45ac8e9afb4bdb2469c7771bd797f1@52.209.21.164:26656"
```

If you still face issues connecting to peers, try clearing the address book.
```
$ sudo systemctl heimdalld stop
$ sudo cp /var/lib/heimdall/config/addrbook.json /var/lib/heimdall/config/addrbook.bkp
$ sudo rm /var/lib/heimdall/config/addrbook.json
$ sudo systemctl heimdalld start
```

**Comment by zyx0355** [comment]
> Hi @zyx0355, sometimes it takes some time to connect to the seed nodes. The seed nodes that you are using are the correct ones.
> 
> ```
> seeds="1500161dd491b67fb1ac81868952be49e2509c9f@52.78.36.216:26656,dd4a3f1750af5765266231b9d8ac764599921736@3.36.224.80:26656,8ea4f592ad6cc38d7532aff418d1fb97052463af@34.240.245.39:26656,e772e1fb8c3492a9570a377a5eafdb1dc53cd778@54.194.245.5:26656,6726b826df45ac8e9afb4bdb2469c7771bd797f1@52.209.21.164:26656"
> ```
> 
> If you still face issues connecting to peers, try clearing the address book.
> 
> ```
> $ sudo systemctl heimdalld stop
> $ sudo cp /var/lib/heimdall/config/addrbook.json /var/lib/heimdall/config/addrbook.json.bkp
> $ sudo rm /var/lib/heimdall/config/addrbook.json
> $ sudo systemctl heimdalld start
> ```

thank you,I will try your method.

**Comment by zyx0355** [comment]
Hello, I also deleted the addrbook.json file before connecting. However, I have been connected for 3 days now and the connection is still not successful.

**Comment by pratikspatil024** [comment]
Hi @zyx0355 - can you make sure your ports are configured correctly as mentioned [here](https://docs.polygon.technology/pos/reference/port-management/)?

**Comment by zyx0355** [comment]
version: "3"

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-alpine
    ports:
      - "5672:5672" # RabbitMQ
    restart: unless-stopped

  heimdalld:
    container_name: heimdalld
    image: 0xpolygon/heimdall:latest
    build: .
    restart: unless-stopped
    environment:
      - HEIMDALL_ETH_RPC_URL=https://eth-mainnet.g.alchemy.com/v2/LnYKRTG56TYQTHCgrvmcSz9-cW5c-9
    volumes:
      - ./data:/var/lib/heimdall
    ports:
      - "26656:26656" # P2P (TCP)
      - "26657:26657" # RPC (TCP)
    depends_on:
      - rabbitmq
    command:
      - start
      - --p2p.laddr=tcp://0.0.0.0:26656
      - --rpc.laddr=tcp://0.0.0.0:26657

  heimdallr:
    container_name: heimdallr
    image: 0xpolygon/heimdall:latest
    build: .
    restart: unless-stopped
    environment:
      - HEIMDALL_ETH_RPC_URL=https://eth-mainnet.g.alchemy.com/v2/LnYKRTG56TYQTHCgrvmcSz9-cW5c-9
    volumes:
      - ./data:/var/lib/heimdall
    ports:
      - "1317:1317" # Heimdall REST API
    depends_on:
      - heimdalld
    command:
      - rest-server
      - --laddr=tcp://0.0.0.0:1317
      - --node=tcp://heimdalld:26657

  bridge:
    container_name: bridge
    image: 0xpolygon/heimdall:latest
    build: .
    restart: unless-stopped
    environment:
      - HEIMDALL_ETH_RPC_URL=https://eth-mainnet.g.alchemy.com/v2/LnYKRTG56TYQTHCgrvmcSz9-cW5c-9
      - HEIMDALL_AMQP_URL=amqp://guest:guest@rabbitmq:5672
      - HEIMDALL_HEIMDALL_REST_SERVER=http://heimdallr:1317
      - HEIMDALL_TENDERMINT_RPC_URL=http://heimdalld:26657
    volumes:
      - ./data:/var/lib/heimdall
    depends_on:
      - heimdalld
      - heimdallr
      - rabbitmq
    command:
      - bridge
      - start
      - --all

> This is my docker-compose.yml configuration for heimdall

**Comment by pratikspatil024** [comment]
https://docs.polygon.technology/pos/operate-node/operate/full-node-docker/
Follow this for docker setup.

**Comment by visualbasic6** [comment]
> > Hi @zyx0355, sometimes it takes some time to connect to the seed nodes. The seed nodes that you are using are the correct ones.
> > ```
> > seeds="1500161dd491b67fb1ac81868952be49e2509c9f@52.78.36.216:26656,dd4a3f1750af5765266231b9d8ac764599921736@3.36.224.80:26656,8ea4f592ad6cc38d7532aff418d1fb97052463af@34.240.245.39:26656,e772e1fb8c3492a9570a377a5eafdb1dc53cd778@54.194.245.5:26656,6726b826df45ac8e9afb4bdb2469c7771bd797f1@52.209.21.164:26656"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If you still face issues connecting to peers, try clearing the address book.
> > ```
> > $ sudo systemctl heimdalld stop
> > $ sudo cp /var/lib/heimdall/config/addrbook.json /var/lib/heimdall/config/addrbook.json.bkp
> > $ sudo rm /var/lib/heimdall/config/addrbook.json
> > $ sudo systemctl heimdalld start
> > ```
> 
> thank you,I will try your method.

root@blockchain:/var/lib/heimdall/config# heimdalld start --chain=mainnet
INFO [2024-01-19|15:21:57.921] starting ABCI with Tendermint                module=main
DEBUG[2024-01-19|15:21:57.956] Invalid ETH RPC timeout provided, falling back to default value timeout=5s
DEBUG[2024-01-19|15:21:57.956] Invalid BOR RPC timeout provided, falling back to default value timeout=5s
ERROR[2024-01-19|15:21:58.144] Error dialing seed                           module=p2p err="dial tcp 159.203.9.164:26656: connect: connection refused" seed=f4f605d60b8ffaaf15240564e58a81103510631c@159.203.9.164:26656
ERROR[2024-01-19|15:21:59.145] Error dialing seed                           module=p2p err="dial tcp 35.230.116.151:26656: i/o timeout" seed=25f5f65a09c56e9f1d2d90618aa70cd358aa68da@35.230.116.151:26656
ERROR[2024-01-19|15:22:00.146] Error dialing seed                           module=p2p err="dial tcp 35.199.4.13:26656: i/o timeout" seed=2eadba4be3ce47ac8db0a3538cb923b57b41c927@35.199.4.13:26656
ERROR[2024-01-19|15:22:01.147] Error dialing seed                           module=p2p err="dial tcp 44.232.55.71:26656: i/o timeout" seed=4fb1bc820088764a564d4f66bba1963d47d82329@44.232.55.71:26656
ERROR[2024-01-19|15:22:02.148] Error dialing seed                           module=p2p err="dial tcp 35.221.13.28:26656: i/o timeout" seed=3b23b20017a6f348d329c102ddc0088f0a10a444@35.221.13.28:26656
ERROR[2024-01-19|15:22:02.148] Couldn't connect to any seeds                module=p2p

**Comment by CaCaBlocker** [comment]
Hi, @visualbasic6 
Could you share working seeds for sync now?
Thanks in advance.
