### ISSUE TITLE
helidammd can't find any peers

### ISSUE THREAD

**Issue by tardigralice** [maticnetwork/heimdall#1148]
**Heimdall version** (use `heimdall version` or `git rev-parse --verify HEAD` if installed from source):

1.0.4

**Environment**:
- **OS** (e.g. from /etc/os-release):
-LINUX UBUNTU 22.04
- **Install tools**:
- **Others**:

**What happened**:

my node was not receiveing any block anymore. (was running old bor - probably the issue)

i updated binaries, and restart heimdalld

**What you expected to happen**:

finding peers, and syncing heimdalld

**Have you tried the latest version**: yes/no
yes

**How to reproduce it** (as minimally and precisely as possible):

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:
https://pastebin.com/NS531aGk

**Config (you can paste only the changes you've made)**:

i have added the recommended peers from the docs for mainnet.

**node command runtime flags**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**:

i tried to delete addresbook, 
(stop heimdalld, delete addrsbook, restart heimdalld)

it did not fixed it

**Comment by cffls** [comment]
Hi @tardigralice , the log looks okay. It sometimes take a while for a node to connect to peers. How long have you been waiting for the node to sync?

**Comment by VAIBHAVJINDAL3012** [comment]
Assuming the issue is resolved, closing it for now.
