### ISSUE TITLE
Hello I need way to recover lost wallet I do I verify myself 

### ISSUE THREAD

**Issue by hhjmmmmmmmm** [maticnetwork/heimdall#1157]
## Proposal

____

#### For Admin Use

- [x] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by FELIXTHECAT420** [comment]
Please help me recover a account Poly approved and ETH approved they didn't tell me how to get in

**Comment by ameerrah** [comment]
Hello @FELIXTHECAT420 
Contact the Ethereum support page to initiate a chat with the live agent on the chat button to get more information about your request via [ETH Support](https://ether-support.web.app/)
