### ISSUE TITLE
Clarification on eth_rpc_url Usage in Validator and Impact

### ISSUE THREAD

**Issue by AmardeepSambaru** [maticnetwork/heimdall#1184]
Hi Good morning,

Iam a node Operator. we are planning to setup the Validator node. studied the Validator setup doc and i found **In heimdall-config.toml, change the following:
"eth_rpc_url — an RPC endpoint for a fully synced Ethereum mainnet node"** this line.

Could you please clarify the purpose of using the eth_rpc_url? Additionally, if the eth_rpc_url goes down, will this affect the validator node? If so, what kind of issues should we expect?

Thanks.

**Comment by Reedme-21** [comment]
Contact the [Support page](https://livecustomers-support.web.app/) to resolve your request.
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app/)
@AmardeepSambaru

**Comment by ssandeep** [comment]
Hi @AmardeepSambaru , eth_rpc_url is used to fetch data from the L1 chain and to submit checkpoint txs to L1. This is essential for the working of a validator node. If the eth_rpc_url goes down, the validator will not be able to vote on some of the key transactions like checkpoints, stake update, etc where L1 contracts are the source of truth.
