### ISSUE TITLE
Add Error Handling in GetBridgeDBInstance Function

### ISSUE THREAD

**Issue by vinayak0035** [maticnetwork/heimdall#1196]
## Summary

Implement error handling in the `GetBridgeDBInstance` function to handle cases where the `bridgeDB` object is nil.

## Problem Definition

Currently, the `GetBridgeDBInstance` function does not handle scenarios where `bridgeDB` may be nil. If the database fails to open for any reason, returning a nil object can lead to potential runtime panics or errors when the returned database instance is used. Adding error handling will help prevent these issues and improve the robustness of the code.

Benefits of including this feature include:
- Enhanced reliability of the application.
- Easier debugging by providing clear error messages.
- Improved user experience by avoiding crashes due to nil references.

## Proposal

Modify the `GetBridgeDBInstance` function to include error handling. The implementation could look like this:

https://github.com/maticnetwork/heimdall/blob/master/bridge/setu/util/db.go#L16

```go
func GetBridgeDBInstance(filePath string) *leveldb.DB {
	bridgeDBOnce.Do(func() {
		var err error
		bridgeDB, err = leveldb.OpenFile(filePath, nil)
		if err != nil {
			log.Fatalln("Error in Bor Opening Database", err.Error())
		}
	})
	return bridgeDB
}

```

This change ensures that the function returns an error if the database fails to open, allowing the caller to handle it appropriately.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by Raneet10** [comment]
Hey @vinayak0035 thanks for flagging this! Could you maybe open a PR for this ?

**Comment by vinayak0035** [comment]
@Raneet10 PR:  https://github.com/maticnetwork/heimdall/pull/1198

**Comment by vinayak0035** [comment]
@Raneet10 @pratikspatil024 New PR: https://github.com/maticnetwork/heimdall/pull/1201
