### ISSUE TITLE
Heimdall v1.0.10 treats "heimdall-137" and "mainnet" as different networks.

### ISSUE THREAD

**Issue by sv3t0sl4v** [maticnetwork/heimdall#1200]
**Heimdall version** 1.0.10, head 8d549d1961ccf8fb21d41527b413cd7674486c72

**Environment**:
- **OS** Ubuntu Linux

**What happened**:
What title says and thus can't connect to some peers. 

**What you expected to happen**:
Connect to peer and sync.

**Have you tried the latest version**: yes

**How to reproduce it** Install from source, add seeds from log or polygon technology documentation, start heimdalld.

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

```
ERROR[2024-10-28|01:12:34.045] Error dialing seed                           module=p2p err="incompatible: Peer is on a different network. Got heimdall-137, expected mainnet" seed=dd4a3f1750af5765266231b9d8ac764599921736@3.36.224.80:26656
ERROR[2024-10-28|01:12:34.143] Error dialing seed                           module=p2p err="incompatible: Peer is on a different network. Got heimdall-137, expected mainnet" seed=5e89bcff09f1c11e3e17259c167dfaf36ec7d424@46.4.95.132:26656
ERROR[2024-10-28|01:12:34.303] Error dialing seed                           module=p2p err="incompatible: Peer is on a different network. Got heimdall-137, expected mainnet" seed=e772e1fb8c3492a9570a377a5eafdb1dc53cd778@54.194.245.5:26656
```

**Config (you can paste only the changes you've made)**:
I only increased cache.

**node command runtime flags**:
Nothing special, flag for home dir as compiled from source and different from default.

**`/dump_consensus_state` output for consensus bugs**
`{
  "jsonrpc": "2.0",
  "id": "",
  "result": {
    "round_state": {
      "height": "1186",
      "round": "0",
      "step": 1,
      "start_time": "2024-10-28T01:21:42.125499059Z",
      "commit_time": "2024-10-28T01:21:37.125499059Z",
      "validators": {
        "validators": [
          {
            "address": "D8507A6AA8C5B4FCC25043146BB357042B7040A2",
            "pub_key": {
              "type": "tendermint/PubKeySecp256k1",
              "value": "BCIzdtG7O4VcsfK3kSaOwAPoN3L8gLj+DyhCP8q2qp0XW8OcRyafJSP79pgrHpGSJP/WjuvGYtnKTFfF0vPGP04="
            },
            "voting_power": "1",
            "proposer_priority": "0"
          }
        ],
        "proposer": {
          "address": "D8507A6AA8C5B4FCC25043146BB357042B7040A2",
          "pub_key": {
            "type": "tendermint/PubKeySecp256k1",
            "value": "BCIzdtG7O4VcsfK3kSaOwAPoN3L8gLj+DyhCP8q2qp0XW8OcRyafJSP79pgrHpGSJP/WjuvGYtnKTFfF0vPGP04="
          },
          "voting_power": "1",
          "proposer_priority": "0"
        }
      },
      "proposal": null,
      "proposal_block": null,
      "proposal_block_parts": null,
      "locked_round": "-1",
      "locked_block": null,
      "locked_block_parts": null,
      "valid_round": "-1",
      "valid_block": null,
      "valid_block_parts": null,
      "votes": [
        {
          "round": "0",
          "prevotes": [
            "nil-Vote"
          ],
          "prevotes_bit_array": "BA{1:_} 0/1 = 0.00",
          "precommits": [
            "nil-Vote"
          ],
          "precommits_bit_array": "BA{1:_} 0/1 = 0.00"
        }
      ],
      "commit_round": "-1",
      "last_commit": {
        "votes": [
          "Vote{0:D8507A6AA8C5 1185/00/2(Precommit) 87F2D1B80181 2B6FDFC518AA @ 2024-10-28T01:21:37.123703493Z [no-proposals]}"
        ],
        "votes_bit_array": "BA{1:x} 1/1 = 1.00",
        "peer_maj_23s": {}
      },
      "last_validators": {
        "validators": [
          {
            "address": "D8507A6AA8C5B4FCC25043146BB357042B7040A2",
            "pub_key": {
              "type": "tendermint/PubKeySecp256k1",
              "value": "BCIzdtG7O4VcsfK3kSaOwAPoN3L8gLj+DyhCP8q2qp0XW8OcRyafJSP79pgrHpGSJP/WjuvGYtnKTFfF0vPGP04="
            },
            "voting_power": "1",
            "proposer_priority": "0"
          }
        ],
        "proposer": {
          "address": "D8507A6AA8C5B4FCC25043146BB357042B7040A2",
          "pub_key": {
            "type": "tendermint/PubKeySecp256k1",
            "value": "BCIzdtG7O4VcsfK3kSaOwAPoN3L8gLj+DyhCP8q2qp0XW8OcRyafJSP79pgrHpGSJP/WjuvGYtnKTFfF0vPGP04="
          },
          "voting_power": "1",
          "proposer_priority": "0"
        }
      },
      "triggered_timeout_precommit": false
    },
    "peers": []
  }
}`

This results in no peer connections and slow block height increment of 1 per 5-6 sec or worse.

**Comment by marcello33** [comment]
@djpolygon can you take a look at this just to make sure it's not due to the new release packagers?
Thank you

**Comment by djpolygon** [comment]
@marcello33 looked into this, I think maybe an issue with the seeds/persistent peers? 

@sv3t0sl4v , can you provide your  config.toml persistent-peers and seeds ?

**Comment by sv3t0sl4v** [comment]
persistent_peers = "8c2d9ec1d5b1aecd54e62258d21d6f15714c773d@35.246.42.75:26656,e7e17210a82c6440883d8592722178e7bdde15b4@35.233.57.147:26656,5e89bcff09f1c11e3e17259c167dfaf36ec7d424@46.4.95.132:26656,1500161dd491b67fb1ac81868952be49e2509c9f@52.78.36.216:26656,dd4a3f1750af5765266231b9d8ac764599921736@3.36.224.80:26656,8ea4f592ad6cc38d7532aff418d1fb97052463af@34.240.245.39:26656,e772e1fb8c3492a9570a377a5eafdb1dc53cd778@54.194.245.5:26656,6726b826df45ac8e9afb4bdb2469c7771bd797f1@52.209.21.164:26656"


I downloaded a snapshot from StakePool and it magically worked as **heimdall-137** instead of **mainnet**. Even weirder, but at least it is working now.

**Comment by avalkov** [comment]
@sv3t0sl4v Can we close this ?

**Comment by sv3t0sl4v** [comment]
Yes. Thank you!
