### ISSUE TITLE
Send last block merkle root with votes on chain

### ISSUE THREAD

**Issue by vaibhavchellani** [maticnetwork/heimdall#123]
We need to send votes and the `SignedHeader` to on-chain contract to correctly determine on the contract that a transaction was included on heimdall

**Comment by jdkanani** [comment]
Can you please eloborate more?

**Comment by vaibhavchellani** [comment]
Sure, so currently we just check if the transaction has received 2/3 votes on heimdall. What we have to check is if the transaction was valid and has received 2/3 votes on heimdall. The way we check if the transaction is valid is by following the light client protocol of tendermint which basically uses the `lastResultsHash` hash. If your transaction was valid it would be in the MT.

**Comment by temaniarpit27** [comment]
Please use the latest version and reopen if required
