### ISSUE TITLE
Issue while using the config files created by testnets command

### ISSUE THREAD

**Issue by vaibhavchellani** [maticnetwork/heimdall#147]
I[2020-01-10|09:29:08.955] starting ABCI with Tendermint                module=main
panic: Unknown db_backend leveldb, expected either fsdb or goleveldb or memdb
goroutine 1 [running]:
github.com/tendermint/tm-db.NewDB(0x13fa77d, 0xa, 0xc000a16c80, 0x7, 0xc00094fe20, 0x1c, 0x203000, 0xc00113f158)
        /home/ubuntu/go/pkg/mod/github.com/tendermint/tm-db@v0.2.0/db.go:67 +0x39c
github.com/tendermint/tendermint/node.DefaultDBProvider(0xc0008b5180, 0xc0008b5180, 0xc000aa24c8, 0x183, 0xc00113f280)
        /home/ubuntu/go/pkg/mod/github.com/maticnetwork/tendermint@v0.26.0-dev0.0.20200105181728-9b2d312d5d14/node/node.go:66 +0xcb
github.com/tendermint/tendermint/node.initDBs(0xc0009457c0, 0x169cad8, 0xc00113f298, 0x408bba, 0x18db8a0, 0x12b4bc0, 0x12b4bc0)
        /home/ubuntu/go/pkg/mod/github.com/maticnetwork/tendermint@v0.26.0-dev0.0.20200105181728-9b2d312d5d14/node/node.go:207 +0x6c
github.com/tendermint/tendermint/node.NewNode(0xc0009457c0, 0x18b3640, 0xc0008bb040, 0xc000ac1b30, 0x1893de0, 0xc0008b5120, 0xc000ac1c40, 0x169cad8, 0xc000ac1c50, 0x18ba840, ...)
        /home/ubuntu/go/pkg/mod/github.com/maticnetwork/tendermint@v0.26.0-dev0.0.20200105181728-9b2d312d5d14/node/node.go:548 +0x50
github.com/cosmos/cosmos-sdk/server.startInProcess(0xc0008b46a0, 0x169d360, 0x1d, 0x0, 0x0)
        /home/ubuntu/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.4/server/start.go:152 +0x4c1
github.com/cosmos/cosmos-sdk/server.StartCmd.func1(0xc000a45400, 0xc0009562e0, 0x0, 0x1, 0x0, 0x0)
        /home/ubuntu/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.4/server/start.go:65 +0xb4
github.com/spf13/cobra.(*Command).execute(0xc000a45400, 0xc0009562c0, 0x1, 0x1, 0xc000a45400, 0xc0009562c0)
        /home/ubuntu/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc000a44500, 0x2, 0xc0008b48a0, 0x1422715)
        /home/ubuntu/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /home/ubuntu/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc000a44500, 0x169d7a8, 0x2, 0xc000ba0b80)
        /home/ubuntu/go/pkg/mod/github.com/maticnetwork/tendermint@v0.26.0-dev0.0.20200105181728-9b2d312d5d14/libs/cli/setup.go:89 +0x3c
main.main()
        /home/ubuntu/go/src/github.com/maticnetwork/heimdall/cmd/heimdalld/main.go:95 +0x43a

**Comment by vaibhavchellani** [comment]
Another thing we expect with the fix for this PR would be refactoring `init` and `testnets` cmd to use the same functions to ensure we don't have such disparities.

**Comment by jdkanani** [comment]
Please update/generate config file since we updated cosmos/Tendermint.
