### ISSUE TITLE
Do not show private key on show-account 

### ISSUE THREAD

**Issue by vaibhavchellani** [maticnetwork/heimdall#151]
We should not expose the private key on `show-account` command, instead, we should do that only when explicitly asked to.

**Comment by jdkanani** [comment]
In that case, we should add different command for private key, since at any point, validator would like to export their private key.

Sent via Superhuman ( https://sprh.mn/?vip=jdkanani@gmail.com )

**Comment by vaibhavchellani** [comment]
Agreed, so this issue is a request for this command and better formatting of the output of the current `show-account` command.n

**Comment by jdkanani** [comment]
Let's start creating bounties on gitcoin?

**Comment by temaniarpit27** [comment]
Please use the latest version of heimdall and check if the issue still persists.
Reopen if required
