### ISSUE TITLE
Remove vetic from heimdall

### ISSUE THREAD

**Issue by vaibhavchellani** [maticnetwork/heimdall#160]
There are traces of `vetic` on heimdall which need to be cleaned up to avoid confusion, since fee tokens on heimdall are `1:1` pegged with `matic` let's call it `matic`

**Comment by jdkanani** [comment]
@mankenavenkatesh Please add this in your opened withdraw PR #135

**Comment by vaibhavchellani** [comment]
Fixed in #162
