### ISSUE TITLE
Heimdallcli Generate Fails In Bash Script

### ISSUE THREAD

**Issue by joesixpack** [maticnetwork/heimdall#188]
ERROR: unknown command "generate-validatorkey" for "heimdallcli"
mv: cannot stat './priv_validator_key.json': No such file or directory
ERROR: unknown command "generate-keystore" for "heimdallcli"
mv: cannot stat './UTC-*': No such file or directory

**Comment by temaniarpit27** [comment]
Please use the latest version and reopen if required
