### ISSUE TITLE
heimdalld rest-server couldn't run, when running with binaries

### ISSUE THREAD

**Issue by scraido** [maticnetwork/heimdall#192]
Before using Linux Package Installation, i use Binaries, all is checkout to CS-2001 before make heimdall, the heimdall is starting smoothly but the rest server is couldn't get to start, i'll try to buidl the binaries again now, and make the report here, Thank you

**Comment by temaniarpit27** [comment]
Please use the latest version of heimdall and check if the issue still persists.
Reopen if required
