### ISSUE TITLE
chain_id we have input for join Validator is not same with what we got from Heimdalld init made with LinuxPackage (LPI)

### ISSUE THREAD

**Issue by scraido** [maticnetwork/heimdall#193]
when i try to join Validator Yesterday system couldn't found my chain_id instead of that system tell me chain_id that differs with what i got from 'heimdalld init' sintax.

with 'heimdalld init' i got;
"chain_id": "heimdall-UMtpRs",
"node_id": "e904773732fb9e916c9b94d9afede50a7960c2db"

before this i do an ubuntu 18.04 clean installation

and then when i do;
any_command include --chain-id <chain-id>

system said;
Create verifier failed: fetching source full commit @ height 1: expected chainID heimdall-UMtpRs, got heimdall-lXaaU9

so the system said i must use that chain_id (heimdall-lXaaU9) instead of what i got from 'heimdalld init'

**Comment by temaniarpit27** [comment]
Please use the latest version of heimdall and check if the issue still persists.
Reopen if required
