### ISSUE TITLE
pub_key on balance different with pub_key we got from 'heimdalld show-account' buidl with LPI

### ISSUE THREAD

**Issue by scraido** [maticnetwork/heimdall#194]
I just realize pub_key on my balance is still use cosmos version even system has provide eth network pub_key that we can see with 'heimdalld show-account',, 

maybe because version CS-2001 still use Cosmos-SDK?

screen shot.
![pub_key](https://user-images.githubusercontent.com/44559893/74551162-47ad3600-4f85-11ea-9e60-5312c97078c0.png)

**Comment by temaniarpit27** [comment]
Please use the latest version of heimdall and check if the issue still persists.
Reopen if required
