### ISSUE TITLE
Looking validator info by id using chain_id provide by system lead to gave wrong pub_key & signer information buidl by LPI

### ISSUE THREAD

**Issue by scraido** [maticnetwork/heimdall#195]
Linux Package Installation
'heimdalld init' that gave chain_id -UMtpRs will lead system to gave us the right chain_id when we type command $ anything --chain_id <chain-id>

so the right chain_id provide by system for me is -1XaaU9 instead of -UMtpRs

but if we use that chain_id for look Validator info by id, will gave us wrong signer and pub_key

my signer is my address using for stake that was "0x299.." the pub_key was "0x049.."

but when we check Validator info by id will gave us;
signer - "0x925.."
pub_key - "0x04a.."

we will get the right info if we also input our signer address and not just the chain_id provide by system. If we include the signer (our staking address) for get Validator info, we will get the right info
command.  
heimdallcli query staking validator-info --validator=0x299b22fFD5C1A23D42199Ab80C6AbFb1004beAe7 --chain-id heimdall-lXaaU9

result.
{"ID":17,"startEpoch":1,"endEpoch":0,"power":450,"pubKey":"0x049fe0b8c94fe6deb59cbf1d779fb74d0330fdf68e7ae9d0257a8a2dc1885d594f5c226736a8d97bc067ace43e8bf87caf30a34d2205f0917f81d5a1cd2cf9088c","signer":"0x299b22ffd5c1a23d42199ab80c6abfb1004beae7","last_updated":0,"accum":0}

screen shot.
![chain_id](https://user-images.githubusercontent.com/44559893/74552692-5cd79400-4f88-11ea-9551-c4707c85863b.png)

**Comment by temaniarpit27** [comment]
Please use the latest version and reopen if required
