### ISSUE TITLE
It seems heimdalld installation with make install buidl with binaries now have a problem

### ISSUE THREAD

**Issue by scraido** [maticnetwork/heimdall#196]
Before i can do the installation, even just leave the rest server couldn't start, but now in a new ubuntu installation, with running / active rabbitMQ, instead of that i couldn't do 'make install' (buidl with binaries), even i have download 'public-testnets' directory and checkout to CS-2001 before,,

also i have re-download it, but it still gave the same result, i will waiting the fixing so i can join testnets too with binaries and update my article, thank you

**Comment by temaniarpit27** [comment]
Please use the latest version and reopen if required
