### ISSUE TITLE
when i try to look out my node i got "pong timeout" in heimdalld.log buidl with LPI

### ISSUE THREAD

**Issue by scraido** [maticnetwork/heimdall#197]
I suddenly got pong timeout info on heimdalld.log, it seems one of the peer is out and then stopped by node for error and lead to 'failed connection'?

Screen Shot.
![pong-timeout](https://user-images.githubusercontent.com/44559893/74555344-200e9b80-4f8e-11ea-93be-bbf46dd91289.png)

**Comment by temaniarpit27** [comment]
Please use the latest version of heimdall and check if the issue still persists.
Reopen if required
