### ISSUE TITLE
stop all services lead us to couldn't restart even the heimdalld service

### ISSUE THREAD

**Issue by scraido** [maticnetwork/heimdall#198]
Because of my err. based on admin suggestion i decided to stop & start again all service or restarted it, but unfortunately after all services was stop instead of restart i couldn't start the first important services which is heimdalld? 

The Err. output with $ sudo service heimdalld status;
● heimdalld.service - heimdall
   Loaded: loaded (/etc/systemd/system/heimdalld.service; static; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2020-02-15 13:46:35 CET; 8s ago
  Process: 17136 ExecStart=/bin/bash -c /usr/bin/heimdalld start --home /etc/heimdall/ > /var/log/matic-logs/heimdalld.log 2>&1 (code=exited, status=1/FAILURE)
  Process: 17135 ExecStartPre=/bin/mkdir -p /var/log/matic-logs/ (code=exited, status=0/SUCCESS)
 Main PID: 17136 (code=exited, status=1/FAILURE)

Feb 15 13:46:35 vmi330163.contaboserver.net systemd[1]: Starting heimdall...
Feb 15 13:46:35 vmi330163.contaboserver.net systemd[1]: Started heimdall.
Feb 15 13:46:35 vmi330163.contaboserver.net systemd[1]: heimdalld.service: Main process exited, code=exited, status=1/FAILURE
Feb 15 13:46:35 vmi330163.contaboserver.net systemd[1]: heimdalld.service: Failed with result 'exit-code'.
root@vmi330163:~# sudo service heimdalld stop
root@vmi330163:~# sudo service heimdalld start
root@vmi330163:~# sudo service heimdalld status

The Err. output with /var/log/matic-logs/~$ tail -f heimdalld.log;
starting ABCI with Tendermint                module=main
ERROR: error during handshake: error on replay: Wrong Block.Header.AppHash.  Expected DBA7F4314721D0D48404B27A182E0F1469F21EA7120AE25527A324094141D654, got 329294347044C1CCC054F4AC556DFC18F57B832553BE6E1A6F34037C76F96569

please advice, thank you

**Comment by scraido** [comment]
Btw my chronology to setup this;
- Fresh Install ubuntu 18.04
- Follow Linux Package Installation
- Follow Stake Doc.
- Got Error on Heimdall & Bor
- Stop All Service
- Coldn't Star or Restart Heimdall

Below is my log;
[heimdalld.log](https://github.com/maticnetwork/heimdall/files/4209702/heimdalld.log)
[heimdalld-bridge.log](https://github.com/maticnetwork/heimdall/files/4209703/heimdalld-bridge.log)
[heimdalld-rest-server.log](https://github.com/maticnetwork/heimdall/files/4209704/heimdalld-rest-server.log)
[bor.log](https://github.com/maticnetwork/heimdall/files/4209701/bor.log)

Please Advice, Thank you

**Comment by temaniarpit27** [comment]
Please use the latest version of heimdall and check if the issue still persists
