### ISSUE TITLE
Proposal. decrease of 18 decimal or cut it off to avoid error

### ISSUE THREAD

**Issue by scraido** [maticnetwork/heimdall#204]
Hi it seem i just been excess input decimal for fee, so it become 19 instead of 18 and lead me got error messages, so can you decrease or removing the decimal on approve and stake CLI command? So we can avoid many kind of this report type from validator in the future

Thank you

**Comment by jdkanani** [comment]
We will be releasing staking UI today/tomorrow. That will help validators to reduce errors while staking.

**Comment by temaniarpit27** [comment]
Please use the latest version of heimdall and check if the issue still persists.
Reopen if required
