### ISSUE TITLE
Node data synchronization failed

### ISSUE THREAD

**Issue by wetezos** [maticnetwork/heimdall#205]
I used a new server without historical data. I followed the steps and encountered the following errors.

panic: Failed to process committed block (24:661707638318C3C4F730A4472DB6434C3DF7CAD6789AEAA399BB89E3022BC3CD): Wrong Block.Header.LastResultsHash. Expected EE27AE8E18FB216C32FD11F2DA2B55E54D5FA25BDDDE205DA8CB81D53A4E39E4, got 9BBD38572701B912B97F049526384546FDBE47ADE3BE42187B9E7AF804E33383

**Comment by jdkanani** [comment]
This error is caused due to non-deterministic state execution. Early failure of sync is mostly the reason for invalid configuration. Please check your configuration files, node version and try again.

**Comment by jdkanani** [comment]
Fixed on `sidechannel` branch.
