### ISSUE TITLE
Validator signer change makes older top-up transactions invalid

### ISSUE THREAD

**Issue by jdkanani** [maticnetwork/heimdall#206]
Since both `MsgTopup` transactions are using the latest contract state for validator information, signer change on staking contracts makes older Topup invalid.

This results in sync failure.

**Comment by jdkanani** [comment]
The plan is to remove `contractCaller.GetValidatorInfo from Topup as well. But, sometimes Topup tx won't have validator in the state (Topup before ValidatorJoin for account creation), signer address is needed in `TopupEvent`.

By CS-2003, this should get fixed.

**Comment by jdkanani** [comment]
Take the following scenario:

1. Validator `v` stakes on `StakeManager` on Ethereum. This eth transaction will generate multiple events including `Staked(validatorId, signer, activationEpoch, amount)` and `TopUpFee(validatorId, fee)`. Consider that signer for `v` is `s1` and `fee` is `x` during this transaction.

2. Any validator `a` will take `TopupFee` from the contract and broadcast it on Heimdall with tx `MsgTopupFee`, since validator `v` cannot make a transaction without `HeimdallFee` on Heimdall. 

3. The top-up transaction will mint `HeimdallFee` to the signer `s1` on Heimdall and changes the state accordingly. Now, `s1` will have fee `x`.

4. `v` changes the signer to `s2` on the Ethereum staking manager contract.

Now, while syncing the Heimdall from genesis, following state changes will take place:

Validator `a`'s transaction `TopupFee` will be executed and during the execution Heimdall `Topup` handler will fetch validator information from Ethereum. But, it will receive validator information with latest signer `s2` instead of `s1` and mints `HeimdallFee` for `s2`.

This will cause different state hash than actual state hash.

**Comment by vaibhavchellani** [comment]
Got it, so I see 2 possible solutions
1. Add signer address in the event
2. Maintain fee by validator ID in Heimdall 

To me, it looks like the 2nd approach is the way to go, as it allows people to send topup txs anytime.

**Comment by jdkanani** [comment]
Second solution will change the normal behavior of Cosmos Coins. 

Fees also creates account for that particular address.

**Comment by jdkanani** [comment]
Fixed and merged on `master`
