### ISSUE TITLE
When the ETH_RPC_URL cannot be accessed, the data will be damaged

### ISSUE THREAD

**Issue by wetezos** [maticnetwork/heimdall#222]
After upgrading yesterday, the data was synchronized and the following error was reported:
ERROR: error during handshake: error on replay: Wrong Block.Header.LastResultsHash. Expected EE27AE8E18FB216C32FD11F2DA2B55E54D5FA25BDDDE205DA8CB81D53A4E39E4, got 9BBD38572701B912B97F049526384546FDBE47ADE3BE42187B9E7AF804E33383

Later, it was found that the infrastructure ID was set to private, resulting in no access eth_rpc_url.
Therefore, it is necessary to resynchronize the data after unsafe reset all,

Later, I thought about whether the data of all nodes would be reset if the ETH RPC URL service have a error one day, which would be disastrous for the nodes.

It is recommended that when the ETH API cannot access it, existing data will not be affected and unset is not needed

**Comment by jdkanani** [comment]
Thanks, @wetezos. We will try to remove this limitation. But bigger problem is that Tendermint doesn't allow tx to recover from panic if the hash doesn't match without re-sync. 

We will take a deep look into our approach of calling external APIs and try to fix it.

**Comment by jdkanani** [comment]
Fixed on `sidechannel` branch.
