### ISSUE TITLE
Remove confirmation checks from handler

### ISSUE THREAD

**Issue by vaibhavchellani** [maticnetwork/heimdall#237]
Confirmation checks cause non-determinism leading to different app hashes for different nodes depending on when they got the transaction, we need to move these checks to `msg` validators.

**Comment by jdkanani** [comment]
We should make the receipt time-dependent. Blocks are unpredictable for each node as they will be using different Ethereum nodes. But, handlers can rely on time from receipt's time.

**Comment by jdkanani** [comment]
Merged on `develop`
