### ISSUE TITLE
0.00% performance still showing on dashboard after some epoch passed

### ISSUE THREAD

**Issue by scraido** [maticnetwork/heimdall#256]
btw the more suspicious maybe on bor couldn't do sealing time after time;

Imported new chain segment               blocks=1    txs=0 mgas=0.000 elapsed=632.742µs    mgasps=0.000 number=182670 hash=bc5b15…4d2c0b dirty=140.61KiB
INFO [03-18|05:41:38.059] Commit new mining work                   number=182671 sealhash=f091b2…4cf8fc uncles=0 txs=0 gas=0 fees=0 elapsed=296.02µs
WARN [03-18|05:41:38.059] Block sealing failed                     err="unauthorized signer"

even the heimdall is run well, with small note on bridge (because it's depend on bor);
bridge.
Found new state txs                          module=clerk-service length=0
D[2020-03-18|05:43:53.561] Querying heimdall event record txs           module=clerk-service start=0 lastEventRecord=0 currentStateCounter=0 tags="record.record-id>0 AND message.action='event-record'"

Generated proposer span msg                module=span-service msg="Span 31 {2004 (192256:198655) [{5 0 0 1 0x04a36f6ed1f93acb0a38f4cacbe2467c72458ac41ce3b12b34d758205b2bc5d930a4e059462da7a0976c32fce766e1f7e8d73933ae72ac2af231fe161187743932 836FE3E3DD0A5F77D9D5B0F67E48048AAAFCD5A0 0 10000} {6 5 0 1 0x040e328f024b0ce1bc3bcbddc0ea3120bb1ba575686a6528bc6547fb5b7dd77d1c720e1607841048549fe38076ba9f25dbb5d3d12e13392747df8175d6f46d035d C50FE6EEA35B73A18F22C14C75456EA3BB01B25E  0} {9 6 0 2 0x04dd0f2f27cae91cd1774992f0daad844b3cad642e85bde5a72baea321e3aa6d7f6bc313ed89c74ea5cee3775fec8ada3f4afef59e989f4264a7fbd7478b732204 C70C6EA5336AE88A581B1336E774F53AED3BF64E 236057600001 0}]}"
E[2020-03-18|05:44:13.795] Unable to fetch next span details            module=span-service

rest-server.
Served RPC HTTP response                     module=rest-server method=GET url=/bor/latest-span status=200 duration=14 remoteAddr=127.0.0.1:51242
I[2020-03-18|05:45:13.777] Served RPC HTTP response                     module=rest-server method=GET url="/bor/prepare-next-span?chain_id=2004&proposer=0x299b22ffd5c1a23d42199ab80c6abfb1004beae7&span_id=31&start_block=192256" status=200 duration=311 remoteAddr=127.0.0.1:51242

heimdalld.
 Executed block                               module=state height=69504 validTxs=0 invalidTxs=0
I[2020-03-18|05:46:51.493] Committed state                              module=state height=69504 txs=0 appHash=14D3FD8D791DF55FFB5EB39BDFC0314437B8EC161C375E181D125DDF15088D6C

**Comment by jdkanani** [comment]
It's mostly dashboard related issue and how we calculate performance cc @arthcp

**Comment by temaniarpit27** [comment]
Closing this.
Reopen if required
