### ISSUE TITLE
MAT-863 Cache external calls

### ISSUE THREAD

**Issue by jdkanani** [maticnetwork/heimdall#261]
## Summary

This proposal proposes an LRU caching mechanism for external calls like fetching receipt logs from Etheruem for top-up, validator details.

## Problem Definition

Currently, it takes 3 exact same calls to check receipt log while sending top-up, validator join or checkpoint-ack to make -- before submitted to pool, checkTx and actual transaction handler. 

## Proposal

Having LRU in place for the external call can reduce redundant calls with the same result. The caching mechanism should not cache it for a longer time or store failed-result in any case. **It should only store successful calls in LRU**.

Heimdall makes all external calls from `helper/call.go`, so it should be easy to add cache in one place.

More on LRU: https://github.com/hashicorp/golang-lru

Reviewers: @mankenavenkatesh @vaibhavchellani 
____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by ptsayli** [comment]
Implemented in https://github.com/maticnetwork/heimdall/pull/267
