### ISSUE TITLE
some user couldn't do approve command from CLI on heimdall-cs2005

### ISSUE THREAD

**Issue by scraido** [maticnetwork/heimdall#283]
**Heimdall version**:
heimdall-cs2005 version. 0.32.7

**Environment**:
- **OS**: ubuntu 18.04
- **Install tools**: rabbit, htop, iftop, go1.13.5 linux/amd64, jq, git, 
- **Others**:

**What happened**:
when i want to do approve;
    heimdallcli approve --staked-amount 480000000000000000000 --fee-amount 20000000000000000000
it's gave me error;
    ERROR: no RPC client defined

**What you expected to happen**:
it should give me tx hash, then i can continue to do stake,,

**Have you tried the latest version**: 
yes

**How to reproduce it** (as minimally and precisely as possible):
i do the step on 
https://docs.matic.network/docs/validate/counter-stake-stage-1/linux-package-installation

and then when i reach Approve steps from;
https://docs.matic.network/docs/validate/counter-stake-stage-1/stake-on-matic

it show this error

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:
i didn't understand how to do it

**Config (you can paste only the changes you've made)**:
i didn't do any changes

**node command runtime flags**:
i didn't understand how to do it

**`/dump_consensus_state` output for consensus bugs**
i didn't understand how to do it

**Anything else we need to know**:
Thank you very much for help

**Comment by temaniarpit27** [comment]
Please check if this persists in latest heimdall version
