### ISSUE TITLE
The address of validator list is not displayed correctly

### ISSUE THREAD

**Issue by wetezos** [maticnetwork/heimdall#303]
**Heimdall version** (use `heimdall version` or `git rev-parse --verify HEAD` if installed from source):

**Environment**:
- **OS** (e.g. from /etc/os-release):
- **Install tools**:
- **Others**:

**What happened**:

Run the command to query the verifier list, and the verifier address will show the beginning of cosmos

heimdallcli query tendermint-validator-set  130047  --chain-id  heimdall-cs2006

blockheight: 130047
validators:
- address: cosmosvalcons1q6p2s0kl4t38l75qejuf3j4veky4acnrrxalwm
  pubkey: cosmosvalconspub1addwnp6pqsvr6dhvnf984q54s3ylsdpl6glsd4f5k5y3dvmm4qszrkz42ulxkc50jvc0dnnsxjawsjpteq7h9rhxt2hs0al97q8d2q23v0kydr0xnwtd6t
  proposerpriority: -30016
  votingpower: 518
- address: cosmosvalcons1q7twxl3gx4kngw9hg2pypdaeznw2ah3es50azf
  pubkey: cosmosvalconspub1addwnp6pqsgcrgml8pgzrnme0f4hfma438h02m8hptxxxrdtj9syehnc7zv3gymqq4hscep5r7ghf4dj6q24gpx44pnefa6nh2dzffne2h50rfpyy595dy
  proposerpriority: 101442
  votingpower: 490
- address: cosmosvalcons1p9ez8m5ruu2wykhna35c9y7xxkl2q4ukg2xf79
  pubkey: cosmosvalconspub1addwnp6pq3h7y7ysndacw8sac7dyu3zk57kxsvyypagvt9c3hdw3vmzzxl4m3u96z2xcczsr4a0gjddf6znwtnmtz7c09rl68ac45fe8jsusc0zusnwmg5
  proposerpriority: -38697
  votingpower: 528
**What you expected to happen**:

Expecting a address for matic
**Have you tried the latest version**: yes/no

**How to reproduce it** (as minimally and precisely as possible):

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**:

**Comment by temaniarpit27** [comment]
Please use the latest version and reopen if issue still persists
