### ISSUE TITLE
Not working ports from config

### ISSUE THREAD

**Issue by sl-he** [maticnetwork/heimdall#384]
**Heimdall version** (use `heimdall version` or `git rev-parse --verify HEAD` if installed from source):

**Environment**:
- **OS** Ubuntu 18.04

**What happened**:
I try to change ports on my VPS in heimdall-config.toml to these ports because it used by other software
**tendermint_rpc_url = "http://0.0.0.0:36657"
heimdall_rest_server = "http://0.0.0.0:3317"**
but isn't working with these ports

**What you expected to happen**:
Working on indicated ports

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible):
Just change ports to these ports in heimdall-config.toml
**tendermint_rpc_url = "http://0.0.0.0:36657"
heimdall_rest_server = "http://0.0.0.0:3317"**

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:
**https://pastebin.com/zpRWAak6**
**Config (you can paste only the changes you've made)**:
_heimdall-config.toml_
**tendermint_rpc_url = "http://0.0.0.0:36657"
heimdall_rest_server = "http://0.0.0.0:3317"**

**Comment by novy4** [comment]
+

**Comment by joesixpack** [comment]
See also https://github.com/maticnetwork/bor/issues/74

**Comment by sl-he** [comment]
> See also [maticnetwork/bor#74](https://github.com/maticnetwork/bor/issues/74)

I think isn't bor problem.

**Comment by joesixpack** [comment]
Are you running geth by any chance?

**Comment by jdkanani** [comment]
Sorry for the late reply.

Rest server needs flags with a new port for a node:

```bash
heimalld rest-server --heimdalld rest-server --laddr tcp://0.0.0.0:3317 --node tcp://localhost:26637
```

So, if you are using `heimdalld-rest-server.service`, please edit `/etc/systemd/system/heimdalld-rest-server.service` with appropriate port and node (heimdalld service) url.

**Comment by sl-he** [comment]
> Are you running geth by any chance?

Nope, only bor.

**Comment by sl-he** [comment]
> Sorry for the late reply.
> 
> Rest server needs flags for new port and non-default node url:
> 
> ```shell
> heimalld rest-server --heimdalld rest-server --laddr tcp://0.0.0.0:3317 --node tcp://localhost:26637
> ```
> 
> So, if you are using `heimdalld-rest-server.service`, please edit `/etc/systemd/system/heimdalld-rest-server.service` with appropriate port and node (heimdalld service) url.
> 
> More details:
> 
> ```
> $ heimdalld rest-server --help
> 
> Start LCD (light-client daemon), a local REST server
> 
> Usage:
>   heimdalld rest-server [flags]
> 
> Flags:
>       --chain-id string   The chain ID to connect to
>   -h, --help              help for rest-server
>       --laddr string      The address for the server to listen on (default "tcp://0.0.0.0:1317")
>       --max-open int      The number of maximum open connections (default 1000)
>       --node string       Address of the node to connect to (default "tcp://localhost:26657")
>       --trust-node        Trust connected full node (don't verify proofs for responses) (default true)
> 
> Global Flags:
>       --home string                   directory for config and data (default "/Users/jdkanani/.heimdalld")
>       --log_level string              Log level (default "main:info,state:info,*:error")
>       --trace                         print out full stack trace on errors
>       --with-heimdall-config string   Heimdall config file path (default <home>/config/heimdall-config.json)
> ```

But isn't normal behavior

**Comment by antech-ashwani** [comment]
heimall service not get start in ubuntu 20.4.3 for polygon mainnet

**Comment by temaniarpit27** [comment]
Please use the latest version and reopen if required
