### ISSUE TITLE
Panic error in heimdalld log on both sentry and validator

### ISSUE THREAD

**Issue by malise800** [maticnetwork/heimdall#385]
**Heimdall version** (use `heimdall version` or `git rev-parse --verify HEAD` if installed from source):
```
heimdalld version
0.1.8
```

**Environment**:
- **OS** (e.g. from /etc/os-release):
```
cat /etc/os-release
NAME="Ubuntu"
VERSION="19.10 (Eoan Ermine)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 19.10"
VERSION_ID="19.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan
```

- **Install tools**: linux package
- **Others**: N/A

**What happened**:
While troubleshooting low uptime, I found those panic error
- https://pastebin.com/gbKP1kaV
- https://pastebin.com/FdbUY3hS

**What you expected to happen**:
no error message

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible): I don't know, i just followed the normal validator guide installation for validator and sentry

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:
see above

**Config (you can paste only the changes you've made)**: N/A

**node command runtime flags**: N/A

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**: N/A

**Comment by temaniarpit27** [comment]
Please use the latest heimdall version - v0.2.9
Reopen if required again
