### ISSUE TITLE
Heimdalld v0.1.9 is Wrong Network

### ISSUE THREAD

**Issue by joesixpack** [maticnetwork/heimdall#387]
I've wiped, reinstalled Heimdall 0.1.9 and Bor 0.1.8 twice, but everytime after configuring for the Sentry and running heimdalld:

root@cassandra:/etc/heimdall/config# curl http://localhost:26657/status
{
  "jsonrpc": "2.0",
  "id": "",
  "result": {
    "node_info": {
      "protocol_version": {
        "p2p": "7",
        "block": "10",
        "app": "0"
      },
      "id": "17d6fa501aa975c3db255c8c533abbb91d17d2a5",
      "listen_addr": "tcp://0.0.0.0:26656",
      "network": "heimdall-cs2007",
      "version": "0.32.7",
      "channels": "4020212223303800",
      "moniker": "\u003cchange to a name of your choice (no spaces) - e.g. flagship-sentry-node\u003e",
      "other": {
        "tx_index": "on",
        "rpc_address": "tcp://127.0.0.1:26657"
      }
    },
    "sync_info": {
      "latest_block_hash": "35C05EE196ACCD3430F4685B50EF318A07B0829FD561F9FA94D19A6AF309064F",
      "latest_app_hash": "3FABEC4A7C2CEA1206A991454778583A9332839D73DDF51D8914CDC8B0C90C4C",
      "latest_block_height": "300771",
      "latest_block_time": "2020-06-08T15:14:23.178491929Z",
      "catching_up": true
    },
    "validator_info": {
      "address": "2F6102A60813AF809C8DA5F46CEB1D022DD718F2",
      "pub_key": {
        "type": "tendermint/PubKeySecp256k1",
        "value": "BDW4zf800KXn5svjk7MOAPa0z2NbaaDdYoCP8aqgVkJ2Oi7SVnbXUNBqmPgHhvMU30VDFAy1XIYSkk52g5o1ZT4="
      },
      "voting_power": "9422"
    }
  }

}root@cassandra:/etc/heimdall/config# head genesis.json
{
  "genesis_time": "2020-05-24T08:43:20.854728Z",
  "chain_id": "heimdall-cs2008",
  "consensus_params": {
    "block": {
      "max_bytes": "22020096",
      "max_gas": "25000000",
      "time_iota_ms": "1000"
    },
    "evidence": {

**Comment by joesixpack** [comment]
Happened on a new machine also.  I suspect it is 0.1.9 causing this:

j@milkyway:~/public-testnets/CS-2008/without-sentry/heimdall$ curl http://localhost:26757/status
{
  "jsonrpc": "2.0",
  "id": "",
  "result": {
    "node_info": {
      "protocol_version": {
        "p2p": "7",
        "block": "10",
        "app": "0"
      },
      "id": "3fe7a08ec6cf57491669826d4a41302cb9d7f23f",
      "listen_addr": "tcp://0.0.0.0:26756",
      "network": "heimdall-WyXreD",
      "version": "0.32.7",
      "channels": "4020212223303800",
      "moniker": "milkyway",
      "other": {
        "tx_index": "on",
        "rpc_address": "tcp://127.0.0.1:26757"
      }
    },
    "sync_info": {
      "latest_block_hash": "B111E344B88A2FAA4D2ABD7D8A8B66CE37D7F590AB83043F64D4AF0AC5171D4F",
      "latest_app_hash": "0597B9D4F82DBC98218222576434A96E051CEEDE0F00B3B8813D381D6F7417C8",
      "latest_block_height": "48",
      "latest_block_time": "2020-06-12T18:58:18.434815603Z",
      "catching_up": true
    },
    "validator_info": {
      "address": "2F6102A60813AF809C8DA5F46CEB1D022DD718F2",
      "pub_key": {
        "type": "tendermint/PubKeySecp256k1",
        "value": "BDW4zf800KXn5svjk7MOAPa0z2NbaaDdYoCP8aqgVkJ2Oi7SVnbXUNBqmPgHhvMU30VDFAy1XIYSkk52g5o1ZT4="
      },
      "voting_power": "0"
    }
  }
}j@milkyway:~/public-testnets/CS-2008/without-sentry/heimdall$ sudo head /etc/heimdall/config/genesis.json
{
  "genesis_time": "2020-05-24T08:43:20.854728Z",
  "chain_id": "heimdall-cs2008",
  "consensus_params": {
    "block": {
      "max_bytes": "22020096",
      "max_gas": "25000000",
      "time_iota_ms": "1000"
    },
    "evidence": {

**Comment by joesixpack** [comment]
Working solution was either to delete the binary directories, but more likely it was using -P with dpkg to cleanup instead of -r.

**Comment by joesixpack** [comment]
At least for the validator machine that worked, Sentry still persists in being CS-2007.

**Comment by joesixpack** [comment]
After further troubleshooting, I suspect there is something wrong with v0.1.9's heimdalld init.  You must also run heimdalld unsafe-reset-all before first launching heimdall or the network will be wrong.

**Comment by joesixpack** [comment]
j@cassandra:/etc/heimdall$ heimdalld init
{
  "chain_id": "heimdall-AdNU4H",
  "node_id": "a616b3ce186e2c896c68022267aef3582f9bb6d7"
}
j@cassandra:/etc/heimdall$ ls -al
total 16
drwxr-xr-x   3 root root 4096 Jun 13 16:26 .
drwxr-xr-x 102 root root 4096 Jun 13 16:26 ..
-rw-------   1 j    j     349 Jun 13 16:26 config
drwx------   2 root root 4096 Jun 13 16:26 data

**Comment by jdkanani** [comment]
@joesixpack yes!

**Comment by temaniarpit27** [comment]
We are using heimdall v0.2.9
Please check and reopen if required
