### ISSUE TITLE
Changing all addresses to string instead of bytes in new-heimdall

### ISSUE THREAD

**Issue by ssandeep** [maticnetwork/heimdall#413]
Ref: https://github.com/cosmos/cosmos-sdk/pull/7242

**Comment by ssandeep** [comment]
We need to stick to either lower or upper case for addresses
cc: @anilCSE @ptsayli @mankenavenkatesh @jdkanani

**Comment by jdkanani** [comment]
Let's use `lowercase` address everywhere.  All `msg.go` will use the same lowercase addresses. CLI and rest API handlers will convert to lowercase from the given address input.

**Comment by anilCSE** [comment]
Yes, let's use lowercase addresses
