### ISSUE TITLE
Use gentxutil instead of genesis state

### ISSUE THREAD

**Issue by jdkanani** [maticnetwork/heimdall#424]
In the current Heimdall version, we are adding initial accounts and validator set while `heimdalld init`. The correct way might be to use `gentxutil` module and populate the initial state.

**Comment by jdkanani** [comment]
@anilCSE Let me know your thoughts.

**Comment by anilCSE** [comment]
Yes, let's use `genutil` as it allows the decentralized launch pattern.

**Comment by temaniarpit27** [comment]
Heimdall V2 issue
Closing this
