### ISSUE TITLE
 Error while `heimdall init` command when genesis file already exist.

### ISSUE THREAD

**Issue by murthyvitwit** [maticnetwork/heimdall#428]
**Heimdall version** (use `heimdall version` or `git rev-parse --verify HEAD` if installed from source):

**Environment**:
- **OS** (e.g. from /etc/os-release): Ubuntu 20.04
- **Install tools**: Make all
- **Others**:

**What happened**:
While initizationg the heimdall app using
 ```heimdall init heimdall --chain-id heimdall-new ```

Got following error
 ```Error: genesis.json file already exists: /home/vitwit/.heimdalld/config/genesis.json```

**What you expected to happen**:
Should overwrite genesis file by using the flag like --overwrite or -o

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible):
**Do** ```heimdall init heimdall --chain-id heimdall-new ``` and **redo** ```heimdall init heimdall-test --chain-id heimdall-test ``` with different moniker and chain-id

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**:

**Comment by ssandeep** [comment]
@murthyvitwit , the solution to this is to delete the ~/.heimdalld directory, right? Please reassign if there's no fix yet.

**Comment by murthyvitwit** [comment]
Deleting ~/.hiemdalld directory a way to do it. Additionally, we can pass the overwrite flag for ``init``` command. 
It's also fixed and merged. Hence I am closing this.
