### ISSUE TITLE
Implement slashing 

### ISSUE THREAD

**Issue by vaibhavchellani** [maticnetwork/heimdall#45]
We need to implement slashing of validators, where we would need to slash validators on multiple parameters.
Some of the parameters can be:
1. `no-ack` received for a proposer.
2. `vote` not submitted by validator. 
3. `validator` inactive 

More parameters to be discussed in this issue.

**Comment by vaibhavchellani** [comment]
Updates present in #84

**Comment by temaniarpit27** [comment]
Please use the latest version and reopen if required
