### ISSUE TITLE
Unable to gerenate pg.gw.go files on proto-gen command

### ISSUE THREAD

**Issue by murthyvitwit** [maticnetwork/heimdall#457]
**Heimdall version** (use `heimdall version` or `git rev-parse --verify HEAD` if installed from source):

**Environment**:
- **OS** (e.g. from /etc/os-release): LInux
- **Install tools**:
- **Others**:

**What happened**:
For GRPC client connection, we need pb.gw.go file to be generated. Gateway output cammond is missing in protoc in `./scripts/protoc-gen.sh` that generate pb.gw.go file.

**What you expected to happen**:
On execution `make proto-gen` command, pb.gw.go file should be generated for rpc queries in proto definitions.

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible):
`make proto-gen`

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**:

**Comment by temaniarpit27** [comment]
Heimdall V2 issue
Closing this
