### ISSUE TITLE
Remove gogoproto.castttype for from proto definations as it is not supported by grpc-gateway

### ISSUE THREAD

**Issue by murthyvitwit** [maticnetwork/heimdall#461]
**Heimdall version** (use `heimdall version` or `git rev-parse --verify HEAD` if installed from source):

**Environment**:
- **OS** (e.g. from /etc/os-release): Linux
- **Install tools**:
- **Others**:

**What happened**:
`gogoproto.casttype` is not supported by grpc-gateway. It should be avoided in proto definations.

**What you expected to happen**:

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible):

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**:

**Comment by temaniarpit27** [comment]
Heimdall V2 issue
Closing this
