### ISSUE TITLE
Error while running init command

### ISSUE THREAD

**Issue by murthyvitwit** [maticnetwork/heimdall#502]
**Heimdall version** (use `heimdall version` or `git rev-parse --verify HEAD` if installed from source): latest master branch

**Environment**:
- **OS** (e.g. from /etc/os-release): Ubuntu
- **Install tools**:
- **Others**:

**What happened**:
on running init command, it's throwing `panic: unable to resolve type URL /cosmos.crypto.secp256k1.PubKey`

**What you expected to happen**:
It should be successful with json response

**Have you tried the latest version**: yes/no

**How to reproduce it** (as minimally and precisely as possible): Pull latest master branch, init chain using `init` command.
`Ex: ./build/heimdalld init heimdall-chain --chain-id heimdall-chain -o`

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:
panic: unable to resolve type URL /cosmos.crypto.secp256k1.PubKey

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/codec.(*ProtoCodec).MustMarshalJSON(0xc0006cb670, 0x2064720, 0xc0010aae80, 0xc000010200, 0x1, 0x1)
	github.com/cosmos/cosmos-sdk@v0.40.0-rc5/codec/proto_codec.go:132 +0x8a
github.com/maticnetwork/heimdall/cmd/heimdalld/cmd.initCmd.func1(0xc000179b80, 0xc0006e9140, 0x1, 0x4, 0x0, 0x0)
	github.com/maticnetwork/heimdall/cmd/heimdalld/cmd/init.go:129 +0xa02
github.com/spf13/cobra.(*Command).execute(0xc000179b80, 0xc0006e9100, 0x4, 0x4, 0xc000179b80, 0xc0006e9100)
	github.com/spf13/cobra@v1.1.1/command.go:850 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000178b00, 0x1b7d20c, 0x8, 0xc0006bf900)
	github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.1/command.go:895

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**:

**Comment by temaniarpit27** [comment]
Please check again and reopen if required
