### ISSUE TITLE
Port client module from previous heimdall

### ISSUE THREAD

**Issue by ssandeep** [maticnetwork/heimdall#530]
Similar to what we had in v0.3.0 for QuerySideTxRequestHandlerFn: https://github.com/maticnetwork/heimdall/blob/v0.3.0/client/tx/root.go#L13

**Comment by ssandeep** [comment]
@temaniarpit27 this is already done right?

**Comment by temaniarpit27** [comment]
Not sure
I didn't pick up this task

**Comment by ssandeep** [comment]
OK, please refer the old code and implement here as well.
