### ISSUE TITLE
Add clerk record rest query by id

### ISSUE THREAD

**Issue by jdkanani** [maticnetwork/heimdall#572]

**Comment by ssandeep** [comment]
@temaniarpit27 please check with @saikumar0x1967 if he's already done this in the other branch.

**Comment by saikumar0x1967** [comment]
@jdkanani  This issue is fixed in this Pull Request https://github.com/maticnetwork/heimdall/pull/561/files#diff-d28208c3541183b009194f8cc4f39b87a9a071977b6239a170338c136684d9f1
