### ISSUE TITLE
Support bor clerk calls

### ISSUE THREAD

**Issue by temaniarpit27** [maticnetwork/heimdall#579]

**Comment by ssandeep** [comment]
@temaniarpit27 can we close this?

**Comment by temaniarpit27** [comment]
@ssandeep we have completed the work but PR hasn't been raised

**Comment by temaniarpit27** [comment]
for_latest_heimdall_develop -> this branch has changes which we are testing

**Comment by ssandeep** [comment]
Let's close it as we'll be merging to master closer to the release.
