### ISSUE TITLE
Issue with checkpoint creation and getting next span details

### ISSUE THREAD

**Issue by ssandeep** [maticnetwork/heimdall#619]
While testing the multi-node setup, bor chain halts after 1 span:

```Retrying again in 5 seconds for next Heimdall span path=heimdall/bor/v1beta1/span/1```

**Comment by floodboad** [comment]
does it solved?

I use the hemidall latest version 

curl localhost:1317/bor/span/1
{"error":"{\"codespace\":\"sdk\",\"code\":1,\"message\":\"could not get span; span not found for id\"}"} 

curl localhost:1317/bor/span/0
{"height":"12140","result":{"span_id":0,"start_block":0,"end_block":255,"validator_set":{"validators":[{"ID":1,"startEpoch":0,"endEpoch":0,"nonce":1,"power":1,"pubKey":"0x0465af1f44963cca826a95021aa06993a7025f547c4bfd691b1a9f444ffe9ee90a779eb36a5af87704685126bbb1994d80c2efa9e9483a9cfc86c4ecbc54f6f377","signer":"0x679d220a90799eaeb49d2569d9afe4c2b207d8b3","last_updated":"","jailed":false,"accum":0}],"proposer":{"ID":1,"startEpoch":0,"endEpoch":0,"nonce":1,"power":1,"pubKey":"0x0465af1f44963cca826a95021aa06993a7025f547c4bfd691b1a9f444ffe9ee90a779eb36a5af87704685126bbb1994d80c2efa9e9483a9cfc86c4ecbc54f6f377","signer":"0x679d220a90799eaeb49d2569d9afe4c2b207d8b3","last_updated":"","jailed":false,"accum":0}},"selected_producers":[{"ID":1,"startEpoch":0,"endEpoch":0,"nonce":1,"power":1,"pubKey":"0x0465af1f44963cca826a95021aa06993a7025f547c4bfd691b1a9f444ffe9ee90a779eb36a5af87704685126bbb1994d80c2efa9e9483a9cfc86c4ecbc54f6f377","signer":"0x679d220a90799eaeb49d2569d9afe4c2b207d8b3","last_updated":"","jailed":false,"accum":0}],"bor_chain_id":"15001"}}

but bor always use /bor/span/1 to sync


INFO [09-02|02:28:43.397] Retrying again in 5 seconds for next Heimdall span path=bor/span/1
INFO [09-02|02:28:45.186] Retrying again in 5 seconds for next Heimdall span path=bor/span/1
INFO [09-02|02:28:48.398] Retrying again in 5 seconds for next Heimdall span path=bor/span/1
INFO [09-02|02:28:50.187] Retrying again in 5 seconds for next Heimdall span path=bor/span/1
INFO [09-02|02:28:53.400] Retrying again in 5 seconds for next Heimdall span path=bor/span/1

could you tell me how can solve this problem?

**Comment by saintevens** [comment]
Hey Everybody- Was there ever any more on this?

**Comment by ssandeep** [comment]
@floodboad , can you create a new issue providing more details of your setup, which document you referred to for installing and setting up bor and heimdall, is your node in sync, etc?
