### ISSUE TITLE
generate-validatorkey: .heimdalld/config/priv_validator_key.json should be -rw------- 

### ISSUE THREAD

**Issue by gaia** [maticnetwork/heimdall#657]
current versions of all matic code, ubuntu 18, go1.15

I absolutely cannot `generate-validatorkey`. 

Invalid file permission for file /root/.heimdalld/config/priv_validator_key.json should be -rw------- 
err: stat /root/.heimdalld/config/priv_validator_key.json: no such file or directory

tried as root. tried as unpriv user with the config dir set to 700 and umask 077 , it doesn't matter. see the umask at 077, the touched file gets created with 600. but I still cannot create priv_validator_key.json

i tried from a different machine. no way around this except reverting [this commit](https://github.com/maticnetwork/heimdall/commit/d2848b2707bcf2b56242c1c2a09c3f8d3d66d64a)

interesting also bc the instructions say it would get created in the dir where the cmd is being run, then it has to be moved to the config dir. dunno why it would complain about the file which still doesn't exist in the final location.

![image](https://user-images.githubusercontent.com/87547/115916271-721c3e00-a429-11eb-97f4-5a559fd09906.png)

**Comment by 0xKrishna** [comment]
The default `priv_validator_key.json` must have got created with `heimdalld init`. Did you deleted that?

**Comment by 0xKrishna** [comment]
You can try to do the `heimdalld init` again.
It will generate a default `priv_validator_key.json` in the ~/.heimdalld/config folder.
After that you can use above command to generate another file anywhere and replace the default one with that.

**Comment by gaia** [comment]
argh! I placed the old key back in there and `generate-validatorkey` worked. I had tried an empty file, a dummy invalid key file. it shouldn't even care what is in `.heimdalld/config/`, it should generate the key then allow the user to move it to `.heimdalld/config/`. at validator START it should check whether the permissions are appropriate. thanks Krishna!

**Comment by decentral-foundation** [comment]
Just realized that you have to move it to the data folder now
