### ISSUE TITLE
How long does it take for the nodes to fully sync?

### ISSUE THREAD

**Issue by junbeomlee** [maticnetwork/heimdall#658]
Our VM specification is 
- 8 GB RAM
- 500GB SSD
- x64 2.0 GHz 2v CPU

**Comment by rangershi** [comment]
the time is up to your net's  bandwidth

**Comment by sunil0410** [comment]
Hi @junbeomlee 

We understand your concern.

So basically there are other factors also taken into consideration for the syncing of the node

1. The IOPS of the node(6000 is the recommended range for IOPS).

2. The Network speed.

3. The average sync speed should be at 15-20 blocks every 8 secs.

4. You can track the block difference between your node and the current block of the network by using the below command

bor attach ./.bor/data/bor.ipc
eth.syncing.highestBlock - eth.syncing.currentBlock

**Comment by temaniarpit27** [comment]
Closing this for now
Reopen if required
