### ISSUE TITLE
slow syncing

### ISSUE THREAD

**Issue by sai-voiddev** [maticnetwork/heimdall#665]
after my node syncing reached  4950000 it becomes so slow and getting alot of errors 

![image](https://user-images.githubusercontent.com/11740157/116729954-23057880-a9e8-11eb-9c84-8c3a06be9f66.png)
![image](https://user-images.githubusercontent.com/11740157/116729980-2993f000-a9e8-11eb-9b8a-9fd4035c1d06.png)
![image](https://user-images.githubusercontent.com/11740157/116730009-34e71b80-a9e8-11eb-878b-e3be007459b7.png)

Its my second time i tried to deploy a full node and get same behavior . in 2 different instances (aws)

**Comment by XXXholics** [comment]
Hello, I am facing with the same problem, did you solve this problem and deployed the node successfully?

**Comment by shivhg** [comment]
We are facing same issue with 8core 32gb ec2 machine, with high IOPS. Can someone assist? The sync is too slow compared to other chains. With this rate it will take at least a month

**Comment by wangzhen130** [comment]
Me too,Kneel down and wait for the great god！
