### ISSUE TITLE
heimdalld rest-server error

### ISSUE THREAD

**Issue by panfeilei** [maticnetwork/heimdall#697]
curl localhost:1317/bor/span/1

got this error:

{
  "code": 12,
  "message": "Not Implemented",
  "details": [
  ]
}

why?

**Comment by cryptowalletr** [comment]
Kindly reach out to rengvoinc finance for any cryptocurrency related inquiry or difficulty you’re having, visit https://support.rengvoinc.com/welcome-to-rengvoinc-wallet-support/ get swift response and help on how to solve the issue and any other related problem you are having.

**Comment by temaniarpit27** [comment]
Please use the latest version of heimdall and check if the issue still persists.
Reopen if required

**Comment by Comolli** [comment]
same one
