### ISSUE TITLE
What happens if the bridge server sends the wrong event from Ethereum to Heimdall

### ISSUE THREAD

**Issue by summerpro** [maticnetwork/heimdall#717]
If the bridge server is attacked by hackers and intentionally sends wrong events to Heimdall, does Heimdall have the ability to verify it?

**Comment by rangershi** [comment]
not at all

**Comment by jdkanani** [comment]
The majority (2/3+ out of total stake) of validators have to agree on the event to make it valid.

**Comment by summerpro** [comment]
> The majority (2/3+ out of total stake) of validators have to agree on the event to make it valid.

But how do these honest nodes know that the Ethereum contract data sent from the bridge is consistent with the data in the Ethereum contract?

**Comment by jdkanani** [comment]
Majority validators run https://github.com/maticnetwork/heimdall/blob/master/clerk/side_handler.go#L59-L70 code as part of event-record tx. If it's valid, they stores data in Heimdall state. Bor picks those event records and executes on Bor state. So if a malicious validator sends invalid data to Heimdall, all honest validators will check with Ethereum and vote "SKIP/NO" on the same.

**Comment by summerpro** [comment]
> Majority validators run https://github.com/maticnetwork/heimdall/blob/master/clerk/side_handler.go#L59-L70 code as part of event-record tx. If it's valid, they stores data in Heimdall state. Bor picks those event records and executes on Bor state. So if a malicious validator sends invalid data to Heimdall, all honest validators will check with Ethereum and vote "SKIP/NO" on the same.

thanks your reply, how does the validator check with Ethereum? Is it through the query interface or other methods?

**Comment by jdkanani** [comment]
Yes - https://github.com/maticnetwork/heimdall/blob/9ceee1a78f274fbf2fefc4242f8773ed95cb180c/helper/call.go#L588

**Comment by summerpro** [comment]
> Yes -
> 
> https://github.com/maticnetwork/heimdall/blob/9ceee1a78f274fbf2fefc4242f8773ed95cb180c/helper/call.go#L588

get it, thank you
