### ISSUE TITLE
Heimdall-testnet seeds not working

### ISSUE THREAD

**Issue by empirer2** [maticnetwork/heimdall#721]
Please assist, when i check the sudo service heimdalld status, I get all these failed attempts to connect to the peers

Aug 15 10:02:46 Ubuntu-2004-focal-64-minimal bash[13482]: E[2021-08-15|10:02:46.815] dialing failed (attempts: 8): dial tcp 54.237.61.33:26656: i/o timeout module=pex addr=149db>
Aug 15 10:03:16 Ubuntu-2004-focal-64-minimal bash[13482]: E[2021-08-15|10:03:16.814] dialing failed (attempts: 8): dial tcp 54.211.245.52:26656: i/o timeout module=pex addr=1f1b>
Aug 15 10:03:16 Ubuntu-2004-focal-64-minimal bash[13482]: E[2021-08-15|10:03:16.814] dialing failed (attempts: 8): dial tcp 34.197.83.153:26656: i/o timeout module=pex addr=1089>
Aug 15 10:05:16 Ubuntu-2004-focal-64-minimal bash[13482]: E[2021-08-15|10:05:16.815] dialing failed (attempts: 8): dial tcp 18.214.246.244:26656: i/o timeout module=pex addr=fbe>
Aug 15 10:07:16 Ubuntu-2004-focal-64-minimal bash[13482]: E[2021-08-15|10:07:16.815] dialing failed (attempts: 9): dial tcp

**Comment by dileepfrog** [comment]
Having the same problem, any updates?

**Comment by sreevalsanmr** [comment]
Sorry for the inconvenience,  the seed nodes has been fixed, please check and let us know if u encounter any new issues.

**Comment by antech-ashwani** [comment]
Error dialing seed in mainnet
