### ISSUE TITLE
debugger.go:22:13: warning: ‘_duk_debugger_attach’ defined but not used [-Wunused-function]

### ISSUE THREAD

**Issue by Dmise** [maticnetwork/heimdall#728]
I run `make install` command from folder where I copy heimdall  from (https://github.com/maticnetwork/heimdall.git)
But heimdalld does not installed

installed go version: go version go1.17 linux/amd64

output `make install` is:
> ~/go/src/github.com/maticnetwork/heimdall# make install
go run helper/heimdall-params.template.go
go install -ldflags '-X github.com/maticnetwork/heimdall/version.Name=heimdall -X github.com/maticnetwork/heimdall/version.ServerName=heim                    dalld -X github.com/maticnetwork/heimdall/version.ClientName=heimdallcli -X github.com/maticnetwork/heimdall/version.Version=0.2.2-beta-1-                    g9ceee1a7 -X github.com/maticnetwork/heimdall/version.Commit=9ceee1a78f274fbf2fefc4242f8773ed95cb180c -X github.com/cosmos/cosmos-sdk/vers                    ion.Name=heimdall -X github.com/cosmos/cosmos-sdk/version.ServerName=heimdalld -X github.com/cosmos/cosmos-sdk/version.ClientName=heimdall                    cli -X github.com/cosmos/cosmos-sdk/version.Version=0.2.2-beta-1-g9ceee1a7 -X github.com/cosmos/cosmos-sdk/version.Commit=9ceee1a78f274fbf                    2fefc4242f8773ed95cb180c' ./cmd/heimdalld
# gopkg.in/olebedev/go-duktape.v3
In file included from _cgo_export.c:4:0:
debugger.go:22:13: warning: ‘_duk_debugger_attach’ defined but not used [-Wunused-function]
go install -ldflags '-X github.com/maticnetwork/heimdall/version.Name=heimdall -X github.com/maticnetwork/heimdall/version.ServerName=heim                    dalld -X github.com/maticnetwork/heimdall/version.ClientName=heimdallcli -X github.com/maticnetwork/heimdall/version.Version=0.2.2-beta-1-                    g9ceee1a7 -X github.com/maticnetwork/heimdall/version.Commit=9ceee1a78f274fbf2fefc4242f8773ed95cb180c -X github.com/cosmos/cosmos-sdk/vers                    ion.Name=heimdall -X github.com/cosmos/cosmos-sdk/version.ServerName=heimdalld -X github.com/cosmos/cosmos-sdk/version.ClientName=heimdall                    cli -X github.com/cosmos/cosmos-sdk/version.Version=0.2.2-beta-1-g9ceee1a7 -X github.com/cosmos/cosmos-sdk/version.Commit=9ceee1a78f274fbf                    2fefc4242f8773ed95cb180c' ./cmd/heimdallcli
# gopkg.in/olebedev/go-duktape.v3
In file included from _cgo_export.c:4:0:
debugger.go:22:13: warning: ‘_duk_debugger_attach’ defined but not used [-Wunused-function]
go install -ldflags '-X github.com/maticnetwork/heimdall/version.Name=heimdall -X github.com/maticnetwork/heimdall/version.ServerName=heim                    dalld -X github.com/maticnetwork/heimdall/version.ClientName=heimdallcli -X github.com/maticnetwork/heimdall/version.Version=0.2.2-beta-1-                    g9ceee1a7 -X github.com/maticnetwork/heimdall/version.Commit=9ceee1a78f274fbf2fefc4242f8773ed95cb180c -X github.com/cosmos/cosmos-sdk/vers                    ion.Name=heimdall -X github.com/cosmos/cosmos-sdk/version.ServerName=heimdalld -X github.com/cosmos/cosmos-sdk/version.ClientName=heimdall                    cli -X github.com/cosmos/cosmos-sdk/version.Version=0.2.2-beta-1-g9ceee1a7 -X github.com/cosmos/cosmos-sdk/version.Commit=9ceee1a78f274fbf                    2fefc4242f8773ed95cb180c' bridge/bridge.go
# gopkg.in/olebedev/go-duktape.v3
In file included from _cgo_export.c:4:0:
debugger.go:22:13: warning: ‘_duk_debugger_attach’ defined but not used [-Wunused-function]
root@Ubuntu-1804-bionic-64-minimal:~/go/src/github.com/maticnetwork/heimdall# debugger.go:22:13: warning: ‘_duk_debugger_attach’ defined b                    ut not used [-Wunused-function]

**Comment by Ivanello** [comment]
Hi,
any updates with this error, how do You fix it @Dmise ?
tnx

**Comment by SaltySousChef** [comment]
Any update on this. Have tried go 15.5, 15.6 and 17.3 but none successfully build heimdalld. Trying to build without the Makefile returns:

```
# gopkg.in/olebedev/go-duktape.v3
In file included from _cgo_export.c:4:
debugger.go:22:13: warning: ‘_duk_debugger_attach’ defined but not used [-Wunused-function]
```

It does however work if you manually install it and replace go install with go get like:

```
go get -ldflags="-X github.com/maticnetwork/heimdall/version.Name=heimdall \
-X github.com/maticnetwork/heimdall/version.ServerName=heimdalld \
-X github.com/maticnetwork/heimdall/version.ClientName=heimdallcli \
-X github.com/maticnetwork/heimdall/version.Version=$VERSION \
-X github.com/maticnetwork/heimdall/version.Commit=$COMMIT \
-X github.com/cosmos/cosmos-sdk/version.Name=heimdall \
-X github.com/cosmos/cosmos-sdk/version.ServerName=heimdalld \
-X github.com/cosmos/cosmos-sdk/version.ClientName=heimdallcli \
-X github.com/cosmos/cosmos-sdk/version.Version=$VERSION \
-X github.com/cosmos/cosmos-sdk/version.Commit=$COMMIT" ./cmd/heimdalld
```

**Comment by osizadmin** [comment]
debugger.go:22:13: warning: ‘_duk_debugger_attach’ defined but not used [-Wunused-function]

We also got this issue. Is there any solution for this issue.

**Comment by SaltySousChef** [comment]
This issue doesn't effect the building of the packages. If the executables aren't where they should be after running 'make install' maybe you are using the sudo command which will install it in the root home folder. If you have to use sudo use the -E flag to preserve the current users environment variables for go.

**Comment by osizadmin** [comment]
We have faced same issue while use the sudo.

**Comment by supragya** [comment]
Downgrading to a very specific commit of `go-duktape` worked for me. You can try if this helps:
```
go get gopkg.in/olebedev/go-duktape.v3@60c24ae608a642bf894bed9eb53627d2384bedca
```
