### ISSUE TITLE
Heimdall crashes

### ISSUE THREAD

**Issue by nuliknol** [maticnetwork/heimdall#740]
**Problem: Heimdall crashes**

**Heimdall version** (use `heimdall version` or `git rev-parse --verify HEAD` if installed from source):

unfortunately 'heimdalld version' returns empty string:
```
user@host:~/h$ ~/bin/heimdalld version

user@host:~/h$

```

**Environment**:

OS: Ubuntu 21.04

user@host:~/h$ ~/bin/heimdalld tendermint version
tendermint: 0.32.7
abci: 0.16.1
blockprotocol: 10
p2pprotocol: 7

user@host:~/h$ 

**What happened**:

Heimdall daemon crashed:

```
2021/10/28 15:52:05 http: Accept error: accept tcp 127.0.0.1:26657: accept4: too many open files; retrying in 1s
2021/10/28 15:52:06 http: Accept error: accept tcp 127.0.0.1:26657: accept4: too many open files; retrying in 1s
2021/10/28 15:52:07 http: Accept error: accept tcp 127.0.0.1:26657: accept4: too many open files; retrying in 1s
2021/10/28 15:52:07 http: Accept error: accept tcp [::]:26660: accept4: too many open files; retrying in 320ms
E[2021-10-28|15:52:07.894] Accept on transport errored                  module=p2p err="accept tcp [::]:26656: accept4: too many open files" numPeers=2
panic: accept routine exited: accept tcp [::]:26656: accept4: too many open files

goroutine 186 [running]:
github.com/tendermint/tendermint/p2p.(*Switch).acceptRoutine(0xc000166c60)
        /home/prodmatic/go/pkg/mod/github.com/maticnetwork/tendermint@v0.26.0-dev0.0.20200429080413-edc079e7d4c9/p2p/switch.go:622 +0xd38
created by github.com/tendermint/tendermint/p2p.(*Switch).OnStart
        /home/prodmatic/go/pkg/mod/github.com/maticnetwork/tendermint@v0.26.0-dev0.0.20200429080413-edc079e7d4c9/p2p/switch.go:230 +0x17d



```

not sure if 'too many files open' error is relevant because it appears a few minutes before the crash.

**Have you tried the latest version**: no

**How to reproduce it** (as minimally and precisely as possible):
it happens after running heimdall for a few weeks

**Config (you can paste only the changes you've made)**:
I am using standard config, no fancy stuff

**Comment by ssandeep** [comment]
If you are getting error “Too many open files (24)” then your application/command/script is hitting max open file limit allowed by linux. You need to increase open file limit as below:

1. **Per-User Limit**

Add the below entries in */etc/security/limits.conf*        

```jsx
*         hard    nofile      500000
*         soft    nofile      500000
root      hard    nofile      500000
root      soft    nofile      500000
```

 **Note**: Once you save file, you may need to logout and login again.

2. **System-Wide Limit

Note**: Set this higher than user-limit set above
Add the below entry in /etc/sysctl.conf

```jsx
fs.file-max = 2097152
```

Then run 

```jsx
sysctl -p
```

Above will increase “total” number of files that can remain open system-wide.

3. **Verify the Limits**

Use the following command to see the max limit of file descriptors

```jsx
cat /proc/sys/fs/file-max
```

Hard Limit

```jsx
ulimit -Hn
```

Soft Limit

```jsx
ulimit -Sn
```

to check maximum limit

```python
ubuntu@ip-40-0-1-8:~$ cat /proc/sys/fs/nr_open
```

If the above does not work, set

```
DefaultLimitNOFILE=1000000

```

in both `/etc/systemd/user.conf`and `/etc/systemd/system.conf`

**Comment by nuliknol** [comment]
@ssandeep I know, but this "open files" error shows only after a few weeks of running the daemon. Therefore , there must be some resource leak in the code, the correct behavior would be to close files when they aren't needed. The default ulimit for maximum open files is 1024, does the daemon needs one thousand files to be in the "open" state?
