### ISSUE TITLE
Can't compile 0.2.3-beta (latest release)

### ISSUE THREAD

**Issue by nuliknol** [maticnetwork/heimdall#741]
Just downloaded latest sources from **Releases** section (heimdall-0.2.3-beta1) but it doesn't compile, apparently the versions of the dependant packages in `go.mod` file are set incorrectly;

```
user@host:~/sources/heimdall-0.2.3-beta1/cmd/heimdalld$ go build .
# gopkg.in/olebedev/go-duktape.v3
In file included from _cgo_export.c:4:
debugger.go:22:13: warning: ‘_duk_debugger_attach’ defined but not used [-Wunused-function]
# github.com/maticnetwork/heimdall/bor
../../bor/keeper.go:235:25: undefined: helper.NewSelectionAlgoHeight
user@host:~/sources/heimdall-0.2.3-beta1/cmd/heimdalld$ 

```

**Comment by ssandeep** [comment]
Hi @nuliknol ,
The latest version is v0.2.3, not sure why the beta tag was showing up on top in the Releases section. There is a new config file that needs to be generated on the basis of the network you will be running. The make command does this automatically. As mentioned in the readme, you can run `make install network=mainnet` for generating the mainnet config file and `make install network=mumbai` for generating the one for mumbai.
