### ISSUE TITLE
question: what's the difference between NewHandler in handler.go and NewPostTxHandler in side_handler.go?

### ISSUE THREAD

**Issue by shiziwen** [maticnetwork/heimdall#744]
Hi, I have a question about the heimdall. I found that there are function NewHandler in handler.go and NewPostTxHandler in side_handler.go. What's the difference between the two functions?

I mean that I don't know what does the handler.go and side_handler.go do.

**Comment by temaniarpit27** [comment]
NewPostTxHandler takes care of the side transactions and processes them
