### ISSUE TITLE
question: do the heimdall share the same proposer as the tendermint?

### ISSUE THREAD

**Issue by shiziwen** [maticnetwork/heimdall#751]
Hi, when I do some research about the validator and the proposer, I found that there are many places need to check if the node is the proposer by IsCurrentProposer, and it will fetch the result from the keeper. Does this keeper will do some connection with the tendermint?

I mean, does the heimdall will share the same DB with the tendermint? Or the heimdall has its own proposer and it is different with the tendermint? Or the heimdall implements the same logic with the tendermint, so they can share the same proposer?

**Comment by temaniarpit27** [comment]
No, they are different
