### ISSUE TITLE
Question: How can I check I am using mainnet or testnet?

### ISSUE THREAD

**Issue by manbobo2002** [maticnetwork/heimdall#776]
**Heimdall version** (use `heimdall version` or `git rev-parse --verify HEAD` if installed from source):
0.2.5

**Environment**:
- **OS** (e.g. from /etc/os-release): debian 10
- **Install tools**:
- **Others**:

I tried
```
curl localhost:26657/status
{
  "jsonrpc": "2.0",
  "id": "",
  "result": {
    "node_info": {
      "protocol_version": {
        "p2p": "7",
        "block": "10",
        "app": "0"
      },
      "id": "c68cdade720482c5512b916637a57d3c1d47e739",
      "listen_addr": "tcp://0.0.0.0:26656",
      "network": "heimdall-80001",
      "version": "0.32.7",
      "channels": "40202122233038",
      "moniker": "MyPolygonNode",
      "other": {
        "tx_index": "on",
        "rpc_address": "tcp://0.0.0.0:26657"
      }
    },
    "sync_info": {
      "latest_block_hash": "",
      "latest_app_hash": "",
      "latest_block_height": "0",
      "latest_block_time": "1970-01-01T00:00:00Z",
      "catching_up": true
    },
    "validator_info": {
      "address": "99572715D0EA22F9053A3AED559752CBB7C82C6F",
      "pub_key": {
        "type": "tendermint/PubKeySecp256k1",
        "value": "BL6uI2GrYOOmnJPvU1PEC/fW/0aKy5iTo8dlsNSdQ46RIAVgjgtboS60hlDP33K3RWJ4K/30Jy0FBC2T8BgY0go="
      },
      "voting_power": "0"
    }
  }
}
```

but it seems not quite obviously to show testnet or mainnet

**Comment by rootwarp** [comment]
As you can see "network" field, `heimdall-80001` is for testnet.
For mainnet, it should be `heimdall-137`.

**Comment by rootulp** [comment]
+1 @rootwarp 's answer:
1. Polygon Mainnet chainId: 137 ([docs](https://docs.polygon.technology/docs/develop/network-details/network#polygon-mainnet))
2. Mumbai-Testnet chainId: 80001 ([docs](https://docs.polygon.technology/docs/develop/network-details/network#polygon-mainnet))

**Comment by cryptowalletr** [comment]
Kindly reach out to rengvoinc finance for any cryptocurrency related inquiry or difficulty you’re having, visit https://support.rengvoinc.com/welcome-to-rengvoinc-wallet-support/ get swift response and help on how to solve the issue and any other related problem you are having.

**Comment by manbobo2002** [comment]
yes, resolved, forgot to close this
