### ISSUE TITLE
heimdall can't synchonize

### ISSUE THREAD

**Issue by lunzhenw** [maticnetwork/heimdall#789]
heimdalld version: v0.2.5

E[2022-03-14|04:26:59.627] Stopping peer for error                      module=p2p peer="Peer{MConn{176.9.20.45:26656} dc4ad9853759ad81ece5204e428e4fb7f30e1c4a out}" err=EOF
E[2022-03-14|04:26:59.656] Stopping peer for error                      module=p2p peer="Peer{MConn{176.9.16.203:26656} 5d835437973a542cc98cf253679ee156df9efcd9 out}" err=EOF
E[2022-03-14|04:26:59.667] Stopping peer for error                      module=p2p peer="Peer{MConn{54.71.51.234:26656} 94bfd5afea010f9e4528765616194ac9f2a6caa5 out}" err=EOF
E[2022-03-14|04:26:59.683] Stopping peer for error                      module=p2p peer="Peer{MConn{100.21.225.217:26656} 1ac87bef27f1e2bdb2396c07e907fe870caae781 out}" err=EOF
E[2022-03-14|04:26:59.833] Stopping peer for error                      module=p2p peer="Peer{MConn{176.9.17.151:26656} 83c72190b209bb4e54bb2926a48f7b155186b0bf out}" err=EOF
E[2022-03-14|04:26:59.918] Stopping peer for error                      module=p2p peer="Peer{MConn{65.21.91.208:26656} c8b2705efaac7c2dfe7d4886f26a97a291403999 out}" err=EOF
E[2022-03-14|04:27:00.160] dialing failed (attempts: 1): dial tcp 18.214.219.27:26656: i/o timeout module=pex addr=322fe55015c7170474775b7d305fde571e455e10@18.214.219.27:26656
E[2022-03-14|04:27:00.160] dialing failed (attempts: 1): dial tcp 52.205.196.14:26656: i/o timeout module=pex addr=bb504105390b146958d7a693d95cef2b74e65caf@52.205.196.14:26656
E[2022-03-14|04:27:29.169] Stopping peer for error                      module=p2p peer="Peer{MConn{118.189.177.157:26655} 6a7923d90b1d0cb624f1f16aa48f51555bba8995 out}" err=EOF
E[2022-03-14|04:27:29.435] Stopping peer for error                      module=p2p peer="Peer{MConn{52.65.134.57:26656} e55dc772c8ce63035fd1fb0261da4c369fa9cf6c out}" err=EOF
E[2022-03-14|04:27:29.627] Stopping peer for error                      module=p2p peer="Peer{MConn{157.90.95.104:15608} 90f0de1cf873f3026f894f079eb122a91ba8f94f out}" err=EOF
E[2022-03-14|04:27:29.634] Stopping peer for error                      module=p2p peer="Peer{MConn{88.198.129.16:26656} 471518432477e31ea348af246c0b54095d41352c out}" err=EOF
E[2022-03-14|04:27:29.637] Stopping peer for error                      module=p2p peer="Peer{MConn{78.46.161.90:26656} a0c65ddc1035cafe1458b6d724bdf0431fe80da0 out}" err=EOF
E[2022-03-14|04:27:29.713] Stopping peer for error                      module=p2p peer="Peer{MConn{158.174.73.246:26656} 4b107a4caf08fff82ac973c3cc94840f357995af out}" err=EOF
E[2022-03-14|04:27:29.809] Stopping peer for error                      module=p2p peer="Peer{MConn{45.79.51.71:26656} f5d1cbdc377b80c09c2b5c6f76684a9afacb0c95 out}" err=EOF
E[2022-03-14|04:27:29.823] Stopping peer for error                      module=p2p peer="Peer{MConn{34.138.62.51:26656} a4aac1ea597d4f6a8cea4f90b1ac588a770fbc03 out}" err=EOF
E[2022-03-14|04:27:29.845] Stopping peer for error                      module=p2p peer="Peer{MConn{209.50.50.107:26656} 74648d5c6cc3cfa6806c458ce79af5fba642841a out}" err=EOF
E[2022-03-14|04:27:30.161] dialing failed (attempts: 1): dial tcp 54.162.193.166:26656: i/o timeout module=pex addr=688b25d7fe9cf9d4e03bd7d3f5014d08e6a9143c@54.162.193.166:26656
E[2022-03-14|04:27:59.631] Stopping peer for error                      module=p2p peer="Peer{MConn{46.4.22.149:26656} 611f40340f736ea5aa9b423de0c46eb5d626271e out}" err=EOF
E[2022-03-14|04:27:59.650] Stopping peer for error                      module=p2p peer="Peer{MConn{54.203.39.40:26656} be9cb5e34686caaa3bf96949f02e5868e390a1da out}" err=EOF
E[2022-03-14|04:27:59.752] Stopping peer for error                      module=p2p peer="Peer{MConn{95.79.50.224:26656} 4dbafb630ca9d715602a984d984f3131fbdd916e out}" err=EOF
E[2022-03-14|04:27:59.789] Stopping peer for error                      module=p2p peer="Peer{MConn{35.173.94.108:26656} 3169bf9d75277e7fb393fd4804395c3317a9fdf3 out}" err=EOF
E[2022-03-14|04:27:59.834] Stopping peer for error                      module=p2p peer="Peer{MConn{54.163.119.243:26656} 1f1b21cacf3ac8a1e1402646e023811b250e2d76 out}" err=EOF
E[2022-03-14|04:27:59.852] Stopping peer for error                      module=p2p peer="Peer{MConn{88.198.69.205:26656} 0d60fad9fd0822700809ed190a1a468eeb8317e0 out}" err=EOF
E[2022-03-14|04:27:59.882] Stopping peer for error                      module=p2p peer="Peer{MConn{23.88.18.56:26656} c124ce0b508e8b9ed1c5b6957f362225659b5343 out}" err=EOF
E[2022-03-14|04:27:59.885] Stopping peer for error                      module=p2p peer="Peer{MConn{159.89.134.248:26656} 64c922566ac244ecc84307ff35ad493ec79b5796 out}" err=EOF
E[2022-03-14|04:28:00.161] dialing failed (attempts: 1): dial tcp 3.222.43.158:26656: i/o timeout module=pex addr=4907711ae92b342e91f63cdfcf3c7c0ba2b5a02a@3.222.43.158:26656
E[2022-03-14|04:28:00.161] dialing failed (attempts: 1): dial tcp 52.44.102.247:26656: i/o timeout module=pex addr=9420adf63b14855018f192d44599e68428b358a9@52.44.102.247:26656

**Comment by jdkanani** [comment]
@lunzhenw Please try https://forum.polygon.technology/t/heimdall-v0-2-7/2423 and check.
