### ISSUE TITLE
Retrying again in 5 seconds for next Heimdall span path=bor/span/4034

### ISSUE THREAD

**Issue by unek** [maticnetwork/heimdall#790]
**Heimdall version** (use `heimdall version` or `git rev-parse --verify HEAD` if installed from source):
empty string but latest release

**Environment**:
- **OS** (e.g. from /etc/os-release): linux 20.04
- **Install tools**:
- **Others**:

**What happened**:
bor says
```Retrying again in 5 seconds for next Heimdall span path=bor/span/4034```

heimdall rest server says
```Served RPC HTTP response                     module=rest-server method=GET url=/bor/span/4034 status=500 duration=0 remoteAddr=127.0.0.1:42484```

bor refuses to sync, heimdall looks synced.

**What you expected to happen**:
syncing

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible): run heimdall run bor

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**:

**Comment by jdkanani** [comment]
Please try https://forum.polygon.technology/t/heimdall-v0-2-7/2423

**Comment by unek** [comment]
works fine after building 0.2.7 from scratch and using the latest bor snapshot, thanks
