### ISSUE TITLE
Wrong Block.Header

### ISSUE THREAD

**Issue by nuliknol** [maticnetwork/heimdall#797]
I am getting the following error with heimdalld v0.2.8

```
I[2022-03-22|19:40:06.075] starting ABCI with Tendermint                module=main 
ERROR: error during handshake: error on replay: Wrong Block.Header.AppHash.  Expected EBC68C180769161664897E8A590461D89709FE044BFE51C0E602A822672A3047, got F11B37FF2DDD8B28B373D01834563002AC4102961BDE950710C401A61129D95A
```

The daemon was running fine, it is just that suddenly this error appeared and now the daemon halts. What is the reason and how should I fix it?

**Comment by Brando753** [comment]
I can confirm my archive node has stopped syncing and has encountered this bug as well. I updated heimdall to version v0.2.8 and rebuilt but the error is persisting. 

```
server_name: heimdalld
client_name: heimdallcli
version: 0.2.8
commit: 3cdebf177775bf697945636b4f07fe9a79b642be
build_tags: ""
go: go version go1.17.7 linux/amd64
```

```
➜  heimdall git:(3cdebf17) heimdalld --home /zfs_pool/heimdall start
I[2022-03-26|05:09:55.815] starting ABCI with Tendermint                module=main 
ERROR: error during handshake: error on replay: Wrong Block.Header.AppHash.  Expected EBC68C180769161664897E8A590461D89709FE044BFE51C0E602A822672A3047, got F11B37FF2DDD8B28B373D01834563002AC4102961BDE950710C401A61129D95A
```

**Comment by gobinat-h** [comment]
@Brando753 Please refer the below article and see if it helps
https://docs.polygon.technology/docs/validate/knowledge-base/known-issues#23-error-wrong-blockheaderapphash

**Comment by Brando753** [comment]
@gobinat-h I am running my own local archival node of Ethereum so I am not using infura. Any other ideas?

**Comment by temaniarpit27** [comment]
Please join the discord server: https://discord.gg/epsBG3Yf and post your queries in #full-node channel and our team will help you resolve the issue.
