### ISSUE TITLE
heimdalld mainet doesn`t work

### ISSUE THREAD

**Issue by wangtao19911111** [maticnetwork/heimdall#808]
Please assist, when i check the sudo service heimdalld status, I get all these failed attempts to connect to the peers

E[2022-03-30|07:15:22.429] dialing failed (attempts: 7): dial tcp 107.21.182.208:26656: i/o timeout module=pex addr=98405233881e5a8175b8435bc51e3b9a7997c32e@107.21.182.208:26656
E[2022-03-30|07:15:52.427] dialing failed (attempts: 6): dial tcp 23.106.70.154:26756: i/o timeout module=pex addr=4D5C50D72A3C7B493294479D603661A707DC4BAF@23.106.70.154:26756
E[2022-03-30|07:16:22.429] dialing failed (attempts: 6): dial tcp 54.88.79.122:26656: i/o timeout module=pex addr=8dd16b82f4628c63f2d0653171dab5f8fc071f86@54.88.79.122:26656
E[2022-03-30|07:17:22.428] dialing failed (attempts: 4): dial tcp 54.226.228.119:26656: i/o timeout module=pex addr=0f1fe6854cb21175c71de045c84244adb4780df7@54.226.228.119:26656
E[2022-03-30|07:17:52.427] dialing failed (attempts: 10): dial tcp 18.205.141.103:26656: i/o timeout module=pex addr=4d1de3db9863f20381fec05ed940c959721448f7@18.205.141.103:26656
E[2022-03-30|07:17:52.427] dialing failed (attempts: 8): dial tcp 34.204.138.107:26656: i/o timeout module=pex addr=503e4d7327c02b07f88f18dcbc3175cbba61cb1b@34.204.138.107:26656
E[2022-03-30|07:18:22.428] dialing failed (attempts: 2): dial tcp 34.197.55.199:26656: i/o timeout module=pex addr=a5a48b7868d9c5e489ffbeadc60c51ab6b6c767c@34.197.55.199:26656
E[2022-03-30|07:18:22.428] dialing failed (attempts: 3): dial tcp 44.198.121.55:26656: i/o timeout module=pex addr=7eb7ef7e556cbc9b1729b45935ab480fc03b672e@44.198.121.55:26656
E[2022-03-30|07:18:52.427] dialing failed (attempts: 7): dial tcp 35.168.253.178:26656: i/o timeout module=pex addr=11aeca90e4598a75e8405f95c8ad7672a2fca562@35.168.253.178:26656
E[2022-03-30|07:18:52.427] dialing failed (attempts: 10): dial tcp 148.251.235.60:26656: i/o timeout module=pex addr=099a22da847b04cbc35c7f72acadcc3a17e870c4@148.251.235.60:26656
E[2022-03-30|07:19:22.427] dialing failed (attempts: 2): dial tcp 54.156.93.118:26656: i/o timeout module=pex addr=e5eccb16d6900d598d7afe43182ada506df14c34@54.156.93.118:26656
E[2022-03-30|07:19:22.427] dialing failed (attempts: 11): dial tcp 100.24.150.135:26656: i/o timeout module=pex addr=d4d6cdf6cc49f150e249c654aabb0481b35542e2@100.24.150.135:26656
E[2022-03-30|07:19:52.427] dialing failed (attempts: 12): dial tcp 52.204.236.200:26656: i/o timeout module=pex addr=ba90d04f95f0b734a9e439b475241bee6141fe5f@52.204.236.200:26656
E[2022-03-30|07:19:52.427] dialing failed (attempts: 2): dial tcp 95.217.37.67:26656: i/o timeout module=pex addr=aaf1658b9ee4828fd23dfbf3b2a1fec2ab87caa5@95.217.37.67:26656
E[2022-03-30|07:20:52.427] dialing failed (attempts: 4): dial tcp 18.135.219.247:26656: i/o timeout module=pex addr=4565db46c22a771fa20c74a8560ca08d4b5b1a77@18.135.219.247:26656
E[2022-03-30|07:20:52.427] dialing failed (attempts: 6): dial tcp 54.205.141.140:26656: i/o timeout module=pex addr=f86280d731b6b2216d15599ac37b1846be15eb60@54.205.141.140:26656
E[2022-03-30|07:21:22.428] dialing failed (attempts: 5): dial tcp 54.163.137.39:46656: i/o timeout module=pex addr=be971cd7312edb6162e9044aab2ab02d683667b6@54.163.137.39:46656
E[2022-03-30|07:21:22.428] dialing failed (attempts: 10): dial tcp 100.21.59.30:26656: i/o timeout module=pex addr=622e72db3f35c9140cb75417dd082b1b466ad812@100.21.59.30:26656
E[2022-03-30|07:21:52.428] dialing failed (attempts: 6): dial tcp 168.119.70.147:26656: i/o timeout module=pex addr=314060227a16b54bc2812872a3989957d6a4fb63@168.119.70.147:26656
E[2022-03-30|07:22:22.429] dialing failed (attempts: 4): dial tcp 54.160.189.36:26656: i/o timeout module=pex addr=ad16df66fd8a74eb1db904ff12871b56cf726c4a@54.160.189.36:26656
E[2022-03-30|07:22:22.429] dialing failed (attempts: 3): dial tcp 54.158.37.81:26656: i/o timeout module=pex addr=5497729780e8cb0e05bfbbdb4230300a7d673a7a@54.158.37.81:26656
E[2022-03-30|07:22:22.429] dialing failed (attempts: 3): dial tcp 44.196.199.181:26656: i/o timeout module=pex addr=4a1608e0c4d9db50a33462f85db30d2b74aabe79@44.196.199.181:26656
E[2022-03-30|07:22:22.429] dialing failed (attempts: 5): dial tcp 54.80.47.203:26656: i/o timeout module=pex addr=3369d89fa538807cec0ed8862fd07669cd29ee6b@54.80.47.203:26656
E[2022-03-30|07:22:52.428] dialing failed (attempts: 7): dial tcp 52.204.18.11:26656: i/o timeout module=pex addr=396a597fdf7797000370e9b71c91c083ded32641@52.204.18.11:26656
E[2022-03-30|07:23:22.428] dialing failed (attempts: 2): dial tcp 3.224.220.208:26656: i/o timeout module=pex addr=82449d60b95d70110f59e93a1ffe5f7651214969@3.224.220.208:26656
E[2022-03-30|07:23:22.428] dialing failed (attempts: 5): dial tcp 35.226.228.240:26656: i/o timeout module=pex addr=c9babd5108265a86e8a711a88449f9c48fe83fd8@35.226.228.240:26656
E[2022-03-30|07:23:22.428] dialing failed (attempts: 7): dial tcp 3.209.61.236:26656: i/o timeout module=pex addr=4c3ed763bfcdea4f326c34ae79e52534fcca672d@3.209.61.236:26656
E[2022-03-30|07:23:52.428] dialing failed (attempts: 9): dial tcp 34.202.242.55:26656: i/o timeout module=pex addr=1f729477b8f1b99d32726bafca70fbe9cc0b66e2@34.202.242.55:26656
E[2022-03-30|07:23:52.428] dialing failed (attempts: 5): dial tcp 34.193.91.179:26656: i/o timeout module=pex addr=37b7047a81ba757f9e744577e37bef2541b63d3b@34.193.91.179:26656
E[2022-03-30|07:24:22.428] dialing failed (attempts: 9): dial tcp 18.117.1.216:46656: i/o timeout module=pex addr=0cd2d726a73380653c831f72402a0baa4812f786@18.117.1.216:46656
E[2022-03-30|07:24:22.428] dialing failed (attempts: 11): dial tcp 54.159.253.210:26656: i/o timeout module=pex addr=a305aac82c42a0053cc5021eadbd6725ad63f814@54.159.253.210:26656
E[2022-03-30|07:24:22.428] dialing failed (attempts: 6): dial tcp 54.159.218.71:26656: i/o timeout module=pex addr=09cd04703296b5fd06520df2bf8ea5313bb0ee0a@54.159.218.71:26656
E[2022-03-30|07:24:22.428] dialing failed (attempts: 2): dial tcp 3.219.77.19:26656: i/o timeout module=pex addr=fe911855be7c33fcd228d27337cf5fa00b0bac25@3.219.77.19:26656
E[2022-03-30|07:24:52.428] dialing failed (attempts: 6): dial tcp 52.22.154.198:26656: i/o timeout module=pex addr=0b46d42e2390d4d330ec7a41ab142d9577585540@52.22.154.198:26656
E[2022-03-30|07:25:22.427] dialing failed (attempts: 11): dial tcp 34.230.238.49:26656: i/o timeout module=pex addr=9156fc9b0fbde65be52a4be772567368bb4074d6@34.230.238.49:26656
E[2022-03-30|07:25:22.427] dialing failed (attempts: 8): dial tcp 52.1.10.251:26656: i/o timeout module=pex addr=3cb0dd9bf206914d4bbebf81cbb9bcf183544ff5@52.1.10.251:26656
E[2022-03-30|07:25:52.428] dialing failed (attempts: 4): dial tcp 195.201.82.254:26656: i/o timeout module=pex addr=34c433a350c112d85aaa28ecc192faa5eb1a3fca@195.201.82.254:26656
E[2022-03-30|07:25:52.428] dialing failed (attempts: 3): dial tcp 107.20.44.21:26656: i/o timeout module=pex addr=6f406afdc8507bf860e1113c6b4cff9ca25dfdc9@107.20.44.21:26656
E[2022-03-30|07:26:22.429] dialing failed (attempts: 4): dial tcp 3.223.164.131:26656: i/o timeout module=pex addr=3dcb4501e899e80b201d682f289b6156c6966437@3.223.164.131:26656
E[2022-03-30|07:26:22.429] dialing failed (attempts: 10): dial tcp 3.226.178.201:26656: i/o timeout module=pex addr=a7e0b6cea6a9ff83ae5294ec96781cb136d64aed@3.226.178.201:26656
E[2022-03-30|07:26:22.429] dialing failed (attempts: 6): dial tcp 34.234.104.223:26656: i/o timeout module=pex addr=ae5425b1b6fe1f3f464593c3fdca26d3901226d8@34.234.104.223:26656

**Comment by temaniarpit27** [comment]
@gobinat-h

**Comment by sunil0410** [comment]
@wangtao19911111 

We understand your concern.

This is more of a connectivity-related issue.

Please check the below-provided docs link and make the necessary changes

https://docs.polygon.technology/docs/validate/knowledge-base/known-issues/#14-issue-dialling-failed-in-heimdall

Adding to that if in case still, you are facing issues after performing the suggestions provided on the docs

1. Please share your Heimdall version.
2. Also are you running the node on Testnet or Mainnet?

**Comment by simuty** [comment]
```
14. Issue: "Dialling failed" in Heimdall[#](https://docs.polygon.technology/docs/validate/knowledge-base/known-issues/#14-issue-dialling-failed-in-heimdall)

Description: This is related to connectivity and more specifically a port related problem

Solution:

Check to curl localhost:26657/status still shows the same block
Try a Heimdall Restart.
Make sure that the connectivity to this port 26656 is open.
Try adding additional peers in vi ~/.heimdalld/config/config.toml
Set max_open_connection parameter to 100.
```


`Try adding additional peers in vi ~/.heimdalld/config/config.toml`,  

**It is recommended to provide a link to view the latest peers** 
**thank you** 




> @wangtao19911111
> 
> We understand your concern.
> 
> This is more of a connectivity-related issue.
> 
> Please check the below-provided docs link and make the necessary changes
> 
> https://docs.polygon.technology/docs/validate/knowledge-base/known-issues/#14-issue-dialling-failed-in-heimdall
> 
> Adding to that if in case still, you are facing issues after performing the suggestions provided on the docs
> 
> 1. Please share your Heimdall version.
> 2. Also are you running the node on Testnet or Mainnet?

**Comment by temaniarpit27** [comment]
Please join the discord server: https://discord.gg/epsBG3Yf and post your queries in #full-node channel and our team will help you resolve the issue.
