### ISSUE TITLE
Can we have proper descriptions in PR's please?

### ISSUE THREAD

**Issue by SatpalSandhu61** [maticnetwork/heimdall#812]
## Summary

Many of the PR's raised in this repo (and others under maticnetwork) don't have any description. Some PR's do have a link to `linear-app`, but that requires users to have an account on the relevant workspace in Linear in order to read the description.

It would be a huge help to developers wanting to use Polygon if you could ensure all PR's have a textual description of what it is aiming to achieve.
For example, I have an issue with spans when trying to get a local node running. I found [this PR](https://github.com/maticnetwork/heimdall/pull/791) which might be related and maybe I need to upgrade the heimdall version I'm using, but I have no way of telling as there is no description in the PR.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by cryptowalletr** [comment]
Kindly reach out to rengvoinc finance for any cryptocurrency related inquiry or difficulty you’re having, visit https://support.rengvoinc.com/welcome-to-rengvoinc-wallet-support/ get swift response and help on how to solve the issue and any other related problem you are having.

**Comment by temaniarpit27** [comment]
We are working on it and improving the process
