### ISSUE TITLE
heimdall syncing not starting

### ISSUE THREAD

**Issue by gsngsn123** [maticnetwork/heimdall#814]
hi iam trying for full node install with ansible but heimdall syncing not starting strucked like below on aws 

"sync_info": {
      "latest_block_hash": "",
      "latest_app_hash": "",
      "latest_block_height": "0",
      "latest_block_time": "1970-01-01T00:00:00Z",
      "catching_up": true

**Comment by temaniarpit27** [comment]
@gobinat-h

**Comment by gobinat-h** [comment]
@gsngsn123 Please share the latest logs

**Comment by manbobo2002** [comment]
same for me
```
(test-aws) root@hx-sg-ts-polygon-1:~$ journalctl -fu heimdalld -n200
-- Logs begin at Tue 2022-04-26 03:53:41 UTC. --
Apr 26 03:53:45 hx-sg-ts-polygon-1 systemd[1]: Started heimdalld.
Apr 26 03:53:46 hx-sg-ts-polygon-1 polygon[702]: I[2022-04-26|03:53:46.639] starting ABCI with Tendermint                module=main
```

```
    "sync_info": {
      "latest_block_hash": "406E6118DC7B1DCC57FA0C0303C0E2AD379EE2FAF4DA371C347A2015358D8A19",
      "latest_app_hash": "0A7614136FB5DF0D5BECF1B3B96F241DF4CA59A044F5454165BC7AD59B7CB451",
      "latest_block_height": "10085504",
      "latest_block_time": "2022-03-22T05:31:33.122022162Z",
      "catching_up": true
    },
```

It stucks on the snapshot point

**Comment by temaniarpit27** [comment]
Please join the discord server: https://discord.gg/epsBG3Yf and post your queries in #full-node channel and our team will help you resolve the issue.

**Comment by kaber2** [comment]
> Please join the discord server: https://discord.gg/epsBG3Yf and post your queries in #full-node channel and our team will help you resolve the issue.

You write that in many of the issues raised here. Could you please resolve issues here, where they are raised and where other people might be looking for solutions to problems which have been solved already? This is the issue tracker after all.
