### ISSUE TITLE
Value missing for hash panic: Value missing for hash a028f029215b8ee9a4efe915c09bf688abe1fd62c5e88b8a94a5396778f27609 corresponding to nodeKey

### ISSUE THREAD

**Issue by Comolli** [maticnetwork/heimdall#827]
**Heimdall version** (use `heimdall version` or `git rev-parse --verify HEAD` if installed from source):

**Environment**:
- **OS** (e.g. from /etc/os-release):
- ubuntu 20
- **Install tools**:
- **Others**:

**What happened**:
when i run command ,heimall start, it will  panic ,i try to checkout  any ohter version,but it no work. 

**What you expected to happen**:
work  
**Have you tried the latest version**: yes/no
yes!!!!

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:
heimdalld start
I[2022-05-18|03:54:26.554] starting ABCI with Tendermint                module=main 
panic: Value missing for hash a028f029215b8ee9a4efe915c09bf688abe1fd62c5e88b8a94a5396778f27609 corresponding to nodeKey n�(�)![�����������b�苊��9gx�v

**Comment by Comolli** [comment]
run command sudo service heimdalld start also like it

**Comment by temaniarpit27** [comment]
Please join the discord server: https://discord.gg/epsBG3Yf and post your queries in #full-node channel and our team will help you resolve the issue.
