### ISSUE TITLE
panic: Failed to process committed block 

### ISSUE THREAD

**Issue by prathmeshgotoadmins** [maticnetwork/heimdall#836]
**Environment**: Mainnet
- **OS** (e.g. from /etc/os-release): Ubuntu 20:04 LTS
- **Install tools**: Docker
- **Others**:

**What happened**:
Getting Below error in /root/logs/heimdalld.log
`I[2022-06-12|06:34:43.533] Committed state                              module=state height=8664000 txs=0 appHash=EBC68C180769161664897E8A590461D89709FE044BFE51C0E602A822672A3047
panic: Failed to process committed block (8664001:D91E752959D4B3B9A6326A124B2A2A1255FB987FD9FB0099A8D6456A1264E63F): Wrong Block.Header.AppHash.  Expected EBC68C180769161664897E8A590461D89709FE044BFE51C0E602A822672A3047, got F11B37FF2DDD8B28B373D01834563002AC4102961BDE950710C401A61129D95A`

Let me know if yo want any more information

**Comment by temaniarpit27** [comment]
Please join the discord server: https://discord.gg/KeeAxrRbX6 and post your queries in the #full-node-queries channel and our team will help you resolve the issue.
