### ISSUE TITLE
[Question] How finality on Ethereum is guaranteed for checkpoint submitting?

### ISSUE THREAD

**Issue by hiromaily** [maticnetwork/heimdall#861]
Though I read source code both contracts and heimdail, I couldn't get how finality on Ethereum is guaranteed for checkpoint submitting.
What if the transaction of checkpoint submitted by heimdail is overthrown after a few confirmations?

**Comment by JekaMas** [comment]
Hi @hiromaily ,
Did you find an answer or need our help?

**Comment by hiromaily** [comment]
@JekaMas 
Hi, Thanks for your reply and sorry for this minor question.
I found confirmation of block for main chain in heimdall code
https://github.com/maticnetwork/heimdall/blob/80012d9f665c4550dc9bc6f04078912775a83574/bridge/setu/listener/rootchain.go#L94

**Comment by JekaMas** [comment]
Any question is welcome :)

**Comment by hiromaily** [comment]
I really appreciate it :)
