### ISSUE TITLE
Bridge logs error

### ISSUE THREAD

**Issue by Vimdar** [maticnetwork/heimdall#869]
Hi Polygon team,
Not sure if it's really a bug report but I need help on this one as I've tried Polygon forum [](https://forum.polygon.technology/t/error-in-bridge-logs/9783) which sent me to [](https://devcollab.live/polygon/) live chat support which for some reason insisted on me connect my wallet so I can provide some QR code which looked a lot like a scam.

Heimdall version 0.2.9
Building Heimdall from [https://github.com/maticnetwork/heimdall/archive/refs/tags/v0.2.9.zip 1](https://github.com/maticnetwork/heimdall/archive/refs/tags/v0.2.9.zip) (unzip + make build)

**Environment**:
Running this with Kubernetes, PV set to a max of 16TB storage, deployment is having a max limit of 20GB ram and 4 core cpu limit.
Running a pod from a Dockerfile starting from Ubuntu 20.04.4 (Focal Fossa)

**What happened**:
Ran Heimdall and related with
`heimdall  start –home my_home > my_heimdall_log_path.log &
heimdall rest-server –home my_home > my_rest_log_path.log &`
sleep 50 (so I’m sure it’s all started) and then
`bridge start –all –home my_home > my_bridge_log_path.log`
I'm starting off a snapshot [](https://matic-blockchain-snapshots.s3-accelerate.amazonaws.com/matic-mainnet/heimdall-snapshot-2022-08-02.tar.gz
It syncs OK and a curl to `localhost:26657/status` shows `catching_up: false` at which point I start an Erigon node as well.
At some point I can see my bridge logs show this error:
`E[2022-08-05|06:58:43.806] Error fetching block header from mainchain while calculating next span seed module=bor error="Post \http://localhost:9545\: dial tcp [::1]:9545: connect: connection refused"
E[2022-08-05|06:58:43.807] Error fetching proposers                     module=span service=processor error="Error while fetching data from url: http://0.0.0.0:1317/bor/prepare-next-span?chain_id=137&proposer=0xc19d41fa1f612983322ee8b5b68a71f3bdbf3320&span_id=4930&start_block=31545856, status: 400"
`
I made sure 9545 is exposed in Dockerfile as well as from Kubernetes deployment and service as well.
A bit of research done and I stumbled upon something that seems similar:
[](https://docs.polygon.technology/docs/maintain/validate/faq/known-issues/#16-error-error-while-fetching-data-from-url)

**What you expected to happen**:
My questions are:
How can I fix this error? A manual stop/restart of the bridge does not sound like an option for long-term use.
Does this affect my syncing (both for Heimdall and Erigon) OR the syncing speed in any way?

I got another question as well – as I was running the same setup but with Bor in the past and now switched to Erigon I’m still waiting for Heimdall to be in catching_up: false state and then start Erigon as it was with Bor.
Is this still the case or I can start Erigon even if Heimdall is still catching up?

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible):
start heimdall + rest-server + bridge in described way off the given snapshot and error shows up

Thanks in advance!

**Comment by 0xKrishna** [comment]
Check your eth_rpc_url in heimdall-config.toml inside .heimdall/config

**Comment by 0xKrishna** [comment]
Also, If you are running a sentry/full node (not a validator node), You don't need to start your/use your bridge.
It's only for validators.

Reach out to official discord for more support.
