### ISSUE TITLE
does not sync from snapshot

### ISSUE THREAD

**Issue by unek** [maticnetwork/heimdall#870]
**Heimdall version** (use `heimdall version` or `git rev-parse --verify HEAD` if installed from source): 0.2.11

**Environment**:
- **OS** (e.g. from /etc/os-release): ubuntu 22.04 lts
- **Install tools**:
- **Others**:

**What happened**: downloaded the snapshot, heimdall refuses to sync further

**What you expected to happen**: heimdall syncs

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible): download the snapshot into the data dir, run heimdall

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:
```
$ ./heimdalld start --home data/heimdall
I[2022-08-18|13:04:38.512] starting ABCI with Tendermint                module=main
```

after killing:
```
I[2022-08-18|13:10:24.547] exiting...                                   module=main
E[2022-08-18|13:10:24.547] Not stopping ConsensusState -- have not been started yet module=consensus impl=ConsensusState
```

/status:
```
    "sync_info": {
      "latest_block_hash": "DFD682EBB10316BA4FCC289792E68A7FC4182385895F550607F67E6741DAE725",
      "latest_app_hash": "F8C2B6F91D2DF0DE28C597D4F2181F51699269D8C5F78439DBC512A16C120E12",
      "latest_block_height": "10534050",
      "latest_block_time": "2022-08-16T17:01:12.766570922Z",
      "catching_up": true
    },
```

**Config (you can paste only the changes you've made)**: no changes made

**node command runtime flags**:
```./heimdalld start --home data/heimdall```

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**: syncs fine from scratch but takes ages.

**Comment by unek** [comment]
seems same as #814, which is unresolved.

**Comment by VictorBerryy** [comment]
Hello are you still having this issues?

**Comment by unek** [comment]
yes

**Comment by JekaMas** [comment]
> Hello are you still having this issues?

Thank you for the interest to the project. Yes, we're working on snap sync as our nearest goal.

**Comment by cffls** [comment]
@unek Was there only one line of log after starting heimdall?

```
I[2022-08-18|13:04:38.512] starting ABCI with Tendermint                module=main
```

Could you please provide more logs if possible? This will help us to troubleshoot further. Thank you!

**Comment by unek** [comment]
correct, it's just this one log when using the snapshot.

**Comment by cffls** [comment]
Thanks! Do you also have heimdall configurations under `data/heimdall`? You can follow this guide [here](https://wiki.polygon.technology/docs/develop/network-details/full-node-binaries#configure-network-directories-1) to setup your config files if you don't have them.

**Comment by unek** [comment]
> Thanks! Do you also have heimdall configurations under `data/heimdall`? You can follow this guide [here](https://wiki.polygon.technology/docs/develop/network-details/full-node-binaries#configure-network-directories-1) to setup your config files if you don't have them.

correct, i've got `config.toml` and `heimdall-config.toml` in `data/heimdall/config`, the snapshot is extracted in `data/heimdall/data`. config files left untouched. `genesis.json` is from the launch repo.

**Comment by cffls** [comment]
Thanks for confirming! We will try to reproduce the problem and update the thread when there are more findings.

**Comment by unek** [comment]
after updating the seed list in the config with some seeds i was provided on discord, heimdall started syncing after a while. thanks

**Comment by brunokelo** [comment]
> after updating the seed list in the config with some seeds i was provided on discord, heimdall started syncing after a while. thanks

Hi, I have the same problem, could you post which solution you used please?

Thanks,

**Comment by unek** [comment]
> > after updating the seed list in the config with some seeds i was provided on discord, heimdall started syncing after a while. thanks
> 
> Hi, I have the same problem, could you post which solution you used please?
> 
> Thanks,

I recommend going to their Discord server and getting a fresh seed list, like I did.
