### ISSUE TITLE
bor could not synced use /bor/span/1 , but  curl localhost:1317/bor/span/0 could get data ,  how can I fixed it ,make bor and heimdall use same span

### ISSUE THREAD

**Issue by floodboad** [maticnetwork/heimdall#873]
**Heimdall version** (use `heimdall version` or `git rev-parse --verify HEAD` if installed from source):
latest ,   0.2.11, I also used  0.2.7, 0.2.6, 0.2.5,

**Environment**:
- **OS** (e.g. from /etc/os-release):
- ubuntu
- **Install tools**:
- docker
- **Others**:

**What happened**:

I use the hemidall latest version

curl localhost:1317/bor/span/1
{"error":"{"codespace":"sdk","code":1,"message":"could not get span; span not found for id"}"}

curl localhost:1317/bor/span/0
{"height":"12140","result":{"span_id":0,"start_block":0,"end_block":255,"validator_set":{"validators":[{"ID":1,"startEpoch":0,"endEpoch":0,"nonce":1,"power":1,"pubKey":"0x0465af1f44963cca826a95021aa06993a7025f547c4bfd691b1a9f444ffe9ee90a779eb36a5af87704685126bbb1994d80c2efa9e9483a9cfc86c4ecbc54f6f377","signer":"0x679d220a90799eaeb49d2569d9afe4c2b207d8b3","last_updated":"","jailed":false,"accum":0}],"proposer":{"ID":1,"startEpoch":0,"endEpoch":0,"nonce":1,"power":1,"pubKey":"0x0465af1f44963cca826a95021aa06993a7025f547c4bfd691b1a9f444ffe9ee90a779eb36a5af87704685126bbb1994d80c2efa9e9483a9cfc86c4ecbc54f6f377","signer":"0x679d220a90799eaeb49d2569d9afe4c2b207d8b3","last_updated":"","jailed":false,"accum":0}},"selected_producers":[{"ID":1,"startEpoch":0,"endEpoch":0,"nonce":1,"power":1,"pubKey":"0x0465af1f44963cca826a95021aa06993a7025f547c4bfd691b1a9f444ffe9ee90a779eb36a5af87704685126bbb1994d80c2efa9e9483a9cfc86c4ecbc54f6f377","signer":"0x679d220a90799eaeb49d2569d9afe4c2b207d8b3","last_updated":"","jailed":false,"accum":0}],"bor_chain_id":"15001"}}

but bor always use /bor/span/1 to sync

INFO [09-02|02:28:43.397] Retrying again in 5 seconds for next Heimdall span path=bor/span/1
INFO [09-02|02:28:45.186] Retrying again in 5 seconds for next Heimdall span path=bor/span/1
INFO [09-02|02:28:48.398] Retrying again in 5 seconds for next Heimdall span path=bor/span/1
INFO [09-02|02:28:50.187] Retrying again in 5 seconds for next Heimdall span path=bor/span/1
INFO [09-02|02:28:53.400] Retrying again in 5 seconds for next Heimdall span path=bor/span/1

**What you expected to happen**:
how can I fixed it ,make bor and heimdall use same span

**Have you tried the latest version**: yes/no
yes,   
**How to reproduce it** (as minimally and precisely as possible):

I fellow by this instructions: 
https://docs.polygon.technology/docs/develop/network-details/full-node-docker

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**:

**Comment by floodboad** [comment]
I have replaced the .heimdalld/config/genesis.json to latest version from [GitHub - maticnetwork/launch: Matic network mainnet v1 launch 27](https://github.com/maticnetwork/launch).

**Comment by temaniarpit27** [comment]
Please post the logs for more details

**Comment by temaniarpit27** [comment]
Reach out to official discord for more support.
