### ISSUE TITLE
My rabbitmq machinery_task queue has 30000+ unconfirmed messages

### ISSUE THREAD

**Issue by lsdbitrue** [maticnetwork/heimdall#888]
**Heimdall version** (use `heimdall version` or `git rev-parse --verify HEAD` if installed from source):

The Latest version

**Environment**:
- **OS** (e.g. from /etc/os-release):
- **Install tools**: docker and kubernetes
- **Others**:

**What happened**:

I'm running an api node instead of validator node.

there are so many unconfirmed messages in `machinery_task` queue

is the bridge service required?

**What you expected to happen**:

**Have you tried the latest version**: Sure

**How to reproduce it** (as minimally and precisely as possible):

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**:

**Comment by temaniarpit27** [comment]
Bridge service is not required if you are not running a validator node.
