### ISSUE TITLE
erigon+heimdall

### ISSUE THREAD

**Issue by masayil** [maticnetwork/heimdall#889]
The heimdall call `eth_getRootHash` ,but the erigon doesn't support this method. Will this have any effect?
![image](https://user-images.githubusercontent.com/65291464/193293299-75f741b7-8ed4-4920-bdba-f58aac854148.png)

**Comment by 0xKrishna** [comment]
Only for validator nodes, But we don't support mining there so should't be a problem.

**Comment by manav2401** [comment]
Also, @masayil the call made should be `bor_getRootHash` and we've implementation of that method already in erigon. See [this](https://github.com/maticnetwork/erigon/blob/devel/cmd/rpcdaemon/README.md#rpc-implementation-status).

**Comment by masayil** [comment]
@manav2401 The question is how to let heimdall know it's running with erigon.Are there any configuration parameters now?Or I need to modify heimdall source code to call `bor_getRootHash`

**Comment by manav2401** [comment]
Nothing affects on heimdall until the client running on the opposite side has these methods available. There's no additional configuration needed. 

Also, heimdall calls the method `bor_getRootHash` through RPC so it doesn't matter if there's erigon or bor on the other side.

**Comment by masayil** [comment]
https://github.com/maticnetwork/heimdall/blob/b139221a095f6b659b1a326c63be54dac36e480a/helper/call.go#L289
It will call ` GetRootHash`(comes from bor/ethclient/bor_ethclient.go) .it has only `eth_getRootHash`.
![image](https://user-images.githubusercontent.com/65291464/194243831-ab9ae77a-3422-45be-af5e-9e97527173c9.png)

Anyway, Since it doesn't affect rpc nodes, then I have no doubts.  thank for your help!
