### ISSUE TITLE
Mumbai testnet heimdall sync wont start

### ISSUE THREAD

**Issue by Akbar30Bill** [maticnetwork/heimdall#890]
**Heimdall version** (use `heimdall version` or `git rev-parse --verify HEAD` if installed from source): 0.2.11

**Environment**:
- **OS** (e.g. from /etc/os-release): Ubuntu 22.04
- **Install tools**: Polygon ansible

**What happened**:
I have followed the official document for setting up the testnet node but after starting heimdall service the blockumber was not increasing so changing the logs to debug level i understood that the seeds were not working properly 

```
Oct 05 12:42:03 ip-172-31-36-119 heimdalld[35249]: D[2022-10-05|12:42:03.222] Blockpool has no peers                       module=blockchain
Oct 05 12:42:04 ip-172-31-36-119 heimdalld[35249]: D[2022-10-05|12:42:04.222] Consensus ticker                             module=blockchain numPending=0 total=0 outbound=0 inbound=0
```

```
seeds = "4cd60c1d76e44b05f7dfd8bab3f447b119e87042@54.147.31.250:26656,b18bbe1f3d8576f4b73d9b18976e71c65e839149@34.226.134.117:26656"
```
also the seed that is available in the guide has this error
```
Oct 05 15:38:31 ip-172-31-36-119 heimdalld[46458]: E[2022-10-05|15:38:31.066] Stopping peer for error                      module=p2p peer="Peer{MConn{54.147.31.250:26656} 4cd60c1d76e44b05f7dfd8bab3f447b119e87042 out}" err=EOF
```

**Comment by gbn8** [comment]
@Akbar30Bill is your node still stuck here?

**Comment by marul2** [comment]
same problem

**Comment by marul2** [comment]
root@debian:~# rm  .heimdalld -R
root@debian:~# heimdalld init --chain=mumbai
root@debian:~# heimdalld start --chain=mumbai
INFO [2022-10-10|13:50:22.145] starting ABCI with Tendermint                module=main
DEBUG[2022-10-10|13:50:22.160] Invalid ETH RPC timeout provided, falling back to default value timeout=5s
DEBUG[2022-10-10|13:50:22.161] Invalid BOR RPC timeout provided, falling back to default value timeout=5s
ERROR[2022-10-10|13:50:22.630] Stopping peer for error                      module=p2p peer="Peer{MConn{54.147.31.250:26656} 4cd60c1d76e44b05f7dfd8bab3f447b119e87042 out}" err=EOF
ERROR[2022-10-10|13:50:52.994] Stopping peer for error                      module=p2p peer="Peer{MConn{54.147.31.250:26656} 4cd60c1d76e44b05f7dfd8bab3f447b119e87042 out}" err=EOF

**Comment by 0xKrishna** [comment]
Try adding these to seed
```7a6c7b5d25b13ce3448b047dbebeb1a19cc2e092@18.213.200.99:26656

4cd60c1d76e44b05f7dfd8bab3f447b119e87042@54.147.31.250:26656```

**Comment by 0xKrishna** [comment]
@Akbar30Bill Any update ?

**Comment by temaniarpit27** [comment]
Closing as no update on this. Please contact the official discord server for more support
