### ISSUE TITLE
Command 'heimdall' not found

### ISSUE THREAD

**Issue by vishalkale151071** [maticnetwork/heimdall#891]
**Heimdall version** (b139221a095f6b659b1a326c63be54dac36e480a):

**Environment**:
- **OS** : Ubuntu 20.04.5 LTS
- **Install tools**:
- **Others**:

**What happened**: After executing "make install" i get following o/p

erigon-node@erigon-node:~/heimdall$ make install
go install -ldflags '-X github.com/maticnetwork/heimdall/version.Name=heimdall -X github.com/maticnetwork/heimdall/version.ServerName=heimdalld -X github.com/maticnetwork/heimdall/version.ClientName=heimdallcli -X github.com/maticnetwork/heimdall/version.Version=0.3.0-beta1-235-gb139221a -X github.com/maticnetwork/heimdall/version.Commit=b139221a095f6b659b1a326c63be54dac36e480a -X github.com/cosmos/cosmos-sdk/version.Name=heimdall -X github.com/cosmos/cosmos-sdk/version.ServerName=heimdalld -X github.com/cosmos/cosmos-sdk/version.ClientName=heimdallcli -X github.com/cosmos/cosmos-sdk/version.Version=0.3.0-beta1-235-gb139221a -X github.com/cosmos/cosmos-sdk/version.Commit=b139221a095f6b659b1a326c63be54dac36e480a' ./cmd/heimdalld
go install -ldflags '-X github.com/maticnetwork/heimdall/version.Name=heimdall -X github.com/maticnetwork/heimdall/version.ServerName=heimdalld -X github.com/maticnetwork/heimdall/version.ClientName=heimdallcli -X github.com/maticnetwork/heimdall/version.Version=0.3.0-beta1-235-gb139221a -X github.com/maticnetwork/heimdall/version.Commit=b139221a095f6b659b1a326c63be54dac36e480a -X github.com/cosmos/cosmos-sdk/version.Name=heimdall -X github.com/cosmos/cosmos-sdk/version.ServerName=heimdalld -X github.com/cosmos/cosmos-sdk/version.ClientName=heimdallcli -X github.com/cosmos/cosmos-sdk/version.Version=0.3.0-beta1-235-gb139221a -X github.com/cosmos/cosmos-sdk/version.Commit=b139221a095f6b659b1a326c63be54dac36e480a' ./cmd/heimdallcli

**What you expected to happen**:

and later  "heimdalld init" command fails with 

Command 'heimdalld' not found, did you mean:

command 'heimdall' from deb heimdall-flash (1.4.2+dfsg-1)

Try: sudo apt install <deb name>

error.

**Comment by manav2401** [comment]
Hi, this issue is because `heimdalld` command is not available globally. You can either use the binary from `./build/heimdalld` to run the `init` command or copy the binaries (heimdalld and heimdallcli) to your `$GOBIN` path.
