### ISSUE TITLE
Heimdall dockerhub image update

### ISSUE THREAD

**Issue by nikolay-ryabinin-rarible** [maticnetwork/heimdall#894]
## Summary

Missing latest docker images iun dockerhub

## Problem Definition

I'm trying to deploy latest stable release v0.2.12 or v0.2.11 in docker invironment, but cannot find required tag in [dockerhub](https://hub.docker.com/r/maticnetwork/heimdall/tags)

## Proposal

Build and push docker a new images.

**Comment by 0xKrishna** [comment]
Looking at the wrong place
https://hub.docker.com/r/0xpolygon/heimdall/tags
