### ISSUE TITLE
panic: Failed to process committed block 

### ISSUE THREAD

**Issue by jangh-lee** [maticnetwork/heimdall#897]
`11월 10 06:23:54 ip-10-52-10-10.ap-northeast-2.compute.internal heimdalld[11841]: I[2022-11-10|06:23:54.522] Executed block                               module=state height=12047965 validTxs=0 invalidTxs=0
11월 10 06:23:54 ip-10-52-10-10.ap-northeast-2.compute.internal heimdalld[11841]: I[2022-11-10|06:23:54.579] Committed state                              module=state height=12047965 txs=0 appHash=307FD0878816B0ED198785C667957A00FB15E8398030540A90470DA2E07113F2
11월 10 06:23:54 ip-10-52-10-10.ap-northeast-2.compute.internal heimdalld[11841]: I[2022-11-10|06:23:54.589] Executed block                               module=state height=12047966 validTxs=0 invalidTxs=0
11월 10 06:23:54 ip-10-52-10-10.ap-northeast-2.compute.internal heimdalld[11841]: I[2022-11-10|06:23:54.645] Committed state                              module=state height=12047966 txs=0 appHash=307FD0878816B0ED198785C667957A00FB15E8398030540A90470DA2E07113F2
11월 10 06:23:54 ip-10-52-10-10.ap-northeast-2.compute.internal heimdalld[11841]: I[2022-11-10|06:23:54.661] Executed block                               module=state height=12047967 validTxs=0 invalidTxs=1
11월 10 06:23:54 ip-10-52-10-10.ap-northeast-2.compute.internal heimdalld[11841]: I[2022-11-10|06:23:54.730] Committed state                              module=state height=12047967 txs=1 appHash=307FD0878816B0ED198785C667957A00FB15E8398030540A90470DA2E07113F2
11월 10 06:23:54 ip-10-52-10-10.ap-northeast-2.compute.internal heimdalld[11841]: panic: Failed to process committed block (12047968:B999055A729787975092BF42938024FE4463ED2ACC4EE2805C3CFCF5ADF0DA10): Wrong Block.Header.AppHash.  Expected 307FD0878816B0ED198785C667957A00FB15E8398030540A90470DA2E07113F2, got 5DA7B271B4C72F4164AD2028B3A8288D39D54A6CE18F91E17017CBFC852605F1
11월 10 06:23:54 ip-10-52-10-10.ap-northeast-2.compute.internal heimdalld[11841]: goroutine 62 [running]:
11월 10 06:23:54 ip-10-52-10-10.ap-northeast-2.compute.internal heimdalld[11841]: github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc000e4e700)
11월 10 06:23:54 ip-10-52-10-10.ap-northeast-2.compute.internal heimdalld[11841]: /root/go/pkg/mod/github.com/maticnetwork/tendermint@v0.26.0-dev0.0.20220803122020-9c20f6000900/blockchain/v0/reactor.go:344 +0x108e
11월 10 06:23:54 ip-10-52-10-10.ap-northeast-2.compute.internal heimdalld[11841]: created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
11월 10 06:23:54 ip-10-52-10-10.ap-northeast-2.compute.internal heimdalld[11841]: /root/go/pkg/mod/github.com/maticnetwork/tendermint@v0.26.0-dev0.0.20220803122020-9c20f6000900/blockchain/v0/reactor.go:118 +0x7f
11월 10 06:23:54 ip-10-52-10-10.ap-northeast-2.compute.internal systemd[1]: heimdalld.service: main process exited, code=exited, status=2/INVALIDARGUMENT
11월 10 06:23:54 ip-10-52-10-10.ap-northeast-2.compute.internal systemd[1]: Unit heimdalld.service entered failed state.
11월 10 06:23:54 ip-10-52-10-10.ap-northeast-2.compute.internal systemd[1]: heimdalld.service failed.`

**Heimdall version** (use `heimdall version` or `git rev-parse --verify HEAD` if installed from source):
testnet / Heimdall version : v0.2.12.  

**Environment**:
- **OS** (e.g. from /etc/os-release): AMZ-linux2

**What happened**:
- panic to sync block

**Have you tried the latest version**
yes

Heimdall stopped syncing block several times continuously.

**Comment by jangh-lee** [comment]
![스크린샷 2022-11-10 오후 3 33 36](https://user-images.githubusercontent.com/72970232/201017569-1c98e1bc-e7c0-48cd-9a3c-3de0d3a82dc2.png)

**Comment by temaniarpit27** [comment]
Please restore the heimdall node with the latest snapshot and start the service
