### ISSUE TITLE
heimdall-config.toml

### ISSUE THREAD

**Issue by masayil** [maticnetwork/heimdall#908]
version: v0.3.0-beta
network: mumbai testnet 
```
heimdalld init --chain=mumbai
```
heimdall-config.toml
```
##### chain - newSelectionAlgoHeight depends on this #####
chain = "mainnet"
```
Shall I change this value (mainnet ==> mumbai)?

**Comment by temaniarpit27** [comment]
Yes, v0.3.0-beta is in the mumbai testnet and you need to replace this if you want to use Mumbai chain
