### ISSUE TITLE
Stuck "catching up" forever

### ISSUE THREAD

**Issue by arthurwolf** [maticnetwork/heimdall#911]
<update>
Re-creating #904 as I can't find a re-open button.

After #904 was closed because a reinstall solved the issue, my 2TB server filled up with the chain. I contact support, support says to use 3TB. I setup a 3TB server, a few days later, the server is full *again*. So I create a 4TB server (zero hope for the future of polygon if this isn't addressed), and this time this new 4TB server has the "catching up forever" problem this ticket was originally created about:

**Heimdall version** (use `heimdall version` or `git rev-parse --verify HEAD` if installed from source):

```
arthur@polygon:~$ heimdalld version
0.2.12
```

**Environment**:
- **OS** (e.g. from /etc/os-release):

```
arthur@polygon:~$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
arthur@polygon:~$ 
```

- **Install tools**:

followed docs precisely.

**What happened**:

I followed the instructions at https://wiki.polygon.technology/docs/develop/network-details/full-node-binaries/

**What you expected to happen**:

Heimdall to "catch up" as the documentation suggests/expects to happen.

But it did not.

The curl command always returns:

```
{
  "jsonrpc": "2.0",
  "id": "",
  "result": {
    "node_info": {
      "protocol_version": {
        "p2p": "7",
        "block": "10",
        "app": "0"
      },
      "id": "c1876c525b5fd58a28839cf3acce83b9ffd8af55",
      "listen_addr": "tcp://0.0.0.0:26656",
      "network": "heimdall-137",
      "version": "0.32.7",
      "channels": "4020212223303800",
      "moniker": "polygon-node-mine",
      "other": {
        "tx_index": "on",
        "rpc_address": "tcp://127.0.0.1:26657"
      }
    },
    "sync_info": {
      "latest_block_hash": "F6729C324E80620A5DE48437B606694B214A2C9ED721100ED79A70A4A1513D15",
      "latest_app_hash": "AC0B456A60848629D31A5FFD4AF661E26E07B9994122DB8845A56144D11BE70D",
      "latest_block_height": "11666871",
      "latest_block_time": "2022-11-15T12:28:53.198656297Z",
      "catching_up": true
    },
    "validator_info": {
      "address": "1AFC3C115C5C41842FF46C443E71A2C87BBCD96A",
      "pub_key": {
        "type": "tendermint/PubKeySecp256k1",
        "value": "BE6+d9lCrVxYdvZurIj+uKQC++B1q+2eYvvQv8ZPsIS0dQ1/bVf4YT98XcDSFgIcMrmHOEPk/U2kec919hCr83s="
      },
      "voting_power": "0"
    }
  }
```

It alwas says "catching up" and the date never changes (and is always the date of the snapshot I extracted).

Complete story at https://github.com/maticnetwork/bor/issues/589

**Have you tried the latest version**: 

yes

**How to reproduce it** (as minimally and precisely as possible):

follow the documentation to the letter, no deviation

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**:

**Comment by 0xKrishna** [comment]
Can you share some logs please

**Comment by 0xKrishna** [comment]
Closing due to duplicate https://github.com/maticnetwork/heimdall/issues/904
