### ISSUE TITLE
heimadalld setup failed

### ISSUE THREAD

**Issue by wangtao19911111** [maticnetwork/heimdall#929]
who can help me? what need i do?
![image](https://user-images.githubusercontent.com/41531065/210378547-064d222d-f16e-40ca-bf07-0ec8eb3d6e81.png)
![image](https://user-images.githubusercontent.com/41531065/210378662-86dfed00-42a9-49a4-bb54-bf6fc7a3fc5e.png)

**Comment by temaniarpit27** [comment]
@rekibnikufesin can you please help him?

**Comment by rekibnikufesin** [comment]
Apologies for missing this notification. @wangtao19911111 - the docs were incorrect. They have been updated via [this PR](https://github.com/maticnetwork/matic-docs/pull/1301) and the current version available [here](https://wiki.polygon.technology/docs/develop/network-details/full-node-docker/).

Thanks for the heads-up @kryptoklob 

@wangtao19911111 closing the issue for now, but please re-open if the updated docs do not resolve your issue.
