### ISSUE TITLE
How to get validator's staking reward in an each block through jsonrpc. 

### ISSUE THREAD

**Issue by yj0x0x** [maticnetwork/heimdall#930]
**Heimdall version** (use `heimdall version` or `git rev-parse --verify HEAD` if installed from source):
v0.3.0

**Environment**:
- **OS** (e.g. from /etc/os-release):
- **Install tools**:
- **Others**:

**What happened**:
I have a wonder that how to get a validator's block reward( staking reward + fee reward) through jsonrpc or rest-api.
If those ways aren't possible, let me know any resources I can refer.  

**What you expected to happen**:

**Have you tried the latest version**: yes/no

**How to reproduce it** (as minimally and precisely as possible):

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**:

**Comment by 0xKrishna** [comment]
@gbn8 @sunilraj228

**Comment by yj0x0x** [comment]
Or please let me know if there are some formula mentioned on the source code.

**Comment by yj0x0x** [comment]
@0xKrishna @sunilraj228 @gbn8 Ping.

**Comment by temaniarpit27** [comment]
Hi
There is no API as of now to calculate/get block rewards for heimdall. The same is calculated on the contract side.
In bor, we can get the miner's reward by checking the gastip of a particular block.
Let me know if this helps

**Comment by yj0x0x** [comment]
@temaniarpit27 Thank you for the reply. 
I'm wondering that staking reward, Not block generation reward. 

I have checked by myself was block producer(miner) would get block reward is sum of total transaction fee minus total burnt fee. 

Is there no-staking reward?

**Comment by temaniarpit27** [comment]
I am not sure I understand what exactly you meant by that but there are 3 types of rewards:
1. Block mining reward in Bor (Only goes to miners/producers and not people who have delegated)
2. Checkpoint proposal reward in Heimdall (Both producers and delegators)
3. Checkpoint signing reward in Heimdall (Both producers and delegators)
Let me know if this helps

**Comment by temaniarpit27** [comment]
Closing this for now. Reopen if required

**Comment by sylviahuang123** [comment]
the same question, who has further progress please share, or any workaround? Appreciate! Expecting

**Comment by sylviahuang123** [comment]
> the same question, who has further progress please share, or any workaround? Appreciate! Expecting

@yj0x0x ping
