### ISSUE TITLE
Make Heimdall Home PATH configurable

### ISSUE THREAD

**Issue by DhunterAO** [maticnetwork/heimdall#937]
## Summary

Make Heimdall Home PATH configurable, which can be deployed easily.

## Problem Definition

The Heimdall Home PATH is hardcoded in the *.go code, and is changed to "/var/lib/heimdall", which is much better than "~/.heimdalld" before. 

But the user cannot configure it, so I have to change it in code before make install, if the PATH can be changed in the configuration, it's more user-friendly. We can specify the PATH according to the disk.

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by temaniarpit27** [comment]
`--home` can be used to pass in the custom datadir.
Please verify and let us know if this works for you.

**Comment by temaniarpit27** [comment]
Closing this for now. Please repoen if required

**Comment by DhunterAO** [comment]
Thanks, it helps a lot
