### ISSUE TITLE
The "power" in the producer set appears to be inconsistent with the power in the validator set

### ISSUE THREAD

**Issue by petejkim** [maticnetwork/heimdall#948]
How is the "power" in the producer set calculated? It seems to differ greatly from the validator set, which I suspect it may contribute to the concentration of block production.

For example, let's take a look at the following span:

https://heimdall-api.polygon.technology/bor/span/6107

Validator 137's power in the validator set is `352652886`, while its power in the producer set is `7`.

Validator 72's power in the validator set, on the other hand, is `224916618`, but its power in the producer set is only `2`, which is unexpected. You would expect the power to be close to `6` considering the ratio in the validator set. (around 1.5x)

Does this lead to validator 137 producing 3.5x more blocks than validator 72, despite having only 1.5x more stake? Wouldn't that lead to unfair concentration of block production to top validators?

I would love to seek clarification on this matter, thank you.

**Comment by Raneet10** [comment]
Thanks @petejkim for asking! A validator's power in producer set corresponds to the number of times the particular validator has been selected in the producer set while determining, pseudo-randomly,  the producers for the next span

https://github.com/maticnetwork/heimdall/blob/15a6bc2dc7cadc387e0902ae9ca2e8a11e82841e/bor/keeper.go#L240-L243

So for a span it might be difficult to correlate the validator's power in the validator set to the power in the producer set (though it does play a part in getting selected in the producer set).

Hope this helps!

**Comment by temaniarpit27** [comment]
Closing this for now. Reopen if required
