### ISSUE TITLE
Move params from heimdall-config to genesis file 

### ISSUE THREAD

**Issue by vaibhavchellani** [maticnetwork/heimdall#95]
Some params are valuable for consensus, those should not be present or configurable via heimdall-config file, instead they should be in the genesis file.

- bor-chainID
- numberOfConfirmations

**Comment by jdkanani** [comment]
Interesting. But, in our current approach, We can change the `bor-chain-ids` as multiple ids without creating a new Heimdall chain.

**Comment by vaibhavchellani** [comment]
Agreed. New chain is' will be added via a transaction to the heimdall state. So this param should exist in the state.

**Comment by jdkanani** [comment]
Agreed.

**Comment by jdkanani** [comment]
`numberOfConfirmations` should be in heimdall config, no?

**Comment by vaibhavchellani** [comment]
Since number of confirmations decides if a tx is valid or not it should be in the genesis file.

**Comment by vaibhavchellani** [comment]
Number of confirmations will change only when the whole network decides to.

**Comment by jdkanani** [comment]
@ptsayli check branch `chain-manager`

**Comment by ptsayli** [comment]
implemented in https://github.com/maticnetwork/heimdall/pull/273
