### ISSUE TITLE
heimdalld unable to connect to seed nodes

### ISSUE THREAD

**Issue by AlexBlack772** [maticnetwork/heimdall#972]
**Heimdall version** 
0.3.2 (also tried with 0.3.0)

**Environment**:
Ubuntu 20.04.2 LTS (Focal Fossa)

**What happened**:
Following the instructions at https://wiki.polygon.technology/docs/operate/full-node-binaries for mainnet, after starting heimdall I see the errors:
```

ERROR[2023-03-23|17:21:20.521] Error dialing seed                           module=p2p err="auth failure: conn.ID (7285a532bad665f051c0aadc31054e2e61ca2b3d) dialed ID (68254d33685fad151e45bfe1ed33d538ba6ec8cb) mismatch" seed=68254d33685fad151e45bfe1ed33d538ba6ec8cb@3.93.224.197:26656
ERROR[2023-03-23|17:21:20.733] Error dialing seed                           module=p2p err="auth failure: conn.ID (6f829065789e5b156cbbf076f9d133b4d7725847) dialed ID (d3d7d397339c9126235dfab11bf925e269776f4f) mismatch" seed=d3d7d397339c9126235dfab11bf925e269776f4f@3.212.183.151:26656
ERROR[2023-03-23|17:21:20.948] Error dialing seed                           module=p2p err="auth failure: conn.ID (2a53a15ffc70ad41b6876ecbe05c50a66af01e20) dialed ID (d3a8990f61bb3657da1664fe437d4993c4599a7e) mismatch" seed=d3a8990f61bb3657da1664fe437d4993c4599a7e@3.211.248.31:26656
ERROR[2023-03-23|17:21:21.286] Error dialing seed                           module=p2p err="auth failure: conn.ID (31b79cf4a628a4619e8e9ae95b72e4354c5a5d90) dialed ID (4fb1bc820088764a564d4f66bba1963d47d82329) mismatch" seed=4fb1bc820088764a564d4f66bba1963d47d82329@44.232.55.71:26656
```

I've tried to delete config directory and reinit heimdalld, but no luck

```
heimdalld init --chain=mainnet --home /var/lib/heimdall

sed -i 's|^seeds =.*|seeds = "d3a8990f61bb3657da1664fe437d4993c4599a7e@3.211.248.31:26656,d3d7d397339c9126235dfab11bf925e269776f4f@3.212.183.151:26656,68254d33685fad151e45bfe1ed33d538ba6ec8cb@3.93.224.197:26656,d26c54ebbf274896f12977bb13d83ac1237a8226@184.73.124.158:26656,f4f605d60b8ffaaf15240564e58a81103510631c@159.203.9.164:26656,4fb1bc820088764a564d4f66bba1963d47d82329@44.232.55.71:26656,2eadba4be3ce47ac8db0a3538cb923b57b41c927@35.199.4.13:26656,25f5f65a09c56e9f1d2d90618aa70cd358aa68da@35.230.116.151:26656,3b23b20017a6f348d329c102ddc0088f0a10a444@35.221.13.28:26656"|g' /var/lib/heimdall/config/config.toml

/usr/bin/heimdalld start --home "/var/lib/heimdall" --rest-server
```
**What you expected to happen**:

heimdalld should connect to seed nodes and start syncing

**Comment by matyushkins** [comment]
I also had the same problem. But now, after several restarts, I was able to connect and download blocks. There is a problem with this type of nodes.

**Comment by nmiceli-simtlix** [comment]
I am experiencing the same on mumbai

`ERROR[2023-03-25|21:39:24.855] Error dialing seed                           module=p2p err="auth failure: conn.ID (e72c0466a02ea43b2198bd3a9454b87a3ef0d77e) dialed ID (4cd60c1d76e44b05f7dfd8bab3f447b119e8704
ERROR[2023-03-25|21:39:24.978] Error dialing seed                           module=p2p err="auth failure: conn.ID (9dfc12d9f39257cefc3d57a4d7302586e59a994e) dialed ID (7a6c7b5d25b13ce3448b047dbebeb1a19cc2e09
ERROR[2023-03-25|21:39:25.107] Error dialing seed                           module=p2p err="auth failure: conn.ID (b302d1ddb21102e794b524d05152a7834da05bd1) dialed ID (b18bbe1f3d8576f4b73d9b18976e71c65e83914
ERROR[2023-03-25|21:39:25.107] Couldn't connect to any seeds                module=p2p `

**Comment by VAIBHAVJINDAL3012** [comment]
Hi @AlexBlack772 @nmiceli-simtlix , sometime it takes time to connect to its peer. Would be able to connect to peers in 8-10 hours.

**Comment by VAIBHAVJINDAL3012** [comment]
@nmiceli-simtlix Okay, We will look into this and get back to you.

**Comment by shorsher** [comment]
Any updates @VAIBHAVJINDAL3012 ?

**Comment by victorfei** [comment]
is there a list of working seeds that you guys can provide?

**Comment by VAIBHAVJINDAL3012** [comment]
Yes, We are updating the list. Will be available by this week.

**Comment by VAIBHAVJINDAL3012** [comment]
This list is updated now
https://wiki.polygon.technology/docs/operate/full-node-binaries/#configure-heimdall-seeds-mumbai
@victorfei  @shorsher Can you please check?

**Comment by victorfei** [comment]
> This list is updated now https://wiki.polygon.technology/docs/operate/full-node-binaries/#configure-heimdall-seeds-mumbai @victorfei @shorsher Can you please check?

I reset my seed and delete my `addrbook.json` and retrying to connect. waited 1-2 hrs and syncing looks like.
~~~
journalctl -u heimdalld -f
Apr 05 21:24:45 ormi-infra4-POLYGON-NODE heimdalld[140000]: ERROR[2023-04-05|21:24:45.457] Stopping peer for error                      module=p2p peer="Peer{MConn{65.21.194.224:26656} 6537b3e774be799c202e0209117576b5a302a04f out}" err=EOF
Apr 05 21:24:45 ormi-infra4-POLYGON-NODE heimdalld[140000]: ERROR[2023-04-05|21:24:45.483] dialing failed (attempts: 6): dial tcp 161.97.139.252:26656: connect: connection refused module=pex addr=1b2e67b9293bc1debc7f74efaf16d983220a47c0@161.97.139.252:26656
Apr 05 21:24:45 ormi-infra4-POLYGON-NODE heimdalld[140000]: ERROR[2023-04-05|21:24:45.531] Stopping peer for error                      module=p2p peer="Peer{MConn{162.55.86.31:26656} 32ddbbebe19b1627f09a37173a5e11941ab8af8f out}" err=EOF
Apr 05 21:24:46 ormi-infra4-POLYGON-NODE heimdalld[140000]: ERROR[2023-04-05|21:24:46.455] dialing failed (attempts: 1): dial tcp 3.228.53.114:26656: i/o timeout module=pex addr=73bf7e16b16f2b056b8dd0d472be68cd9f5233c8@3.228.53.114:26656
Apr 05 21:24:46 ormi-infra4-POLYGON-NODE heimdalld[140000]: ERROR[2023-04-05|21:24:46.455] dialing failed (attempts: 1): dial tcp 18.216.216.32:26656: i/o timeout module=pex addr=a5c43b10cd0fe6d128fdd008e1e39c780689b24e@18.216.216.32:26656
Apr 05 21:24:46 ormi-infra4-POLYGON-NODE heimdalld[140000]: ERROR[2023-04-05|21:24:46.457] dialing failed (attempts: 4): dial tcp 44.208.191.127:26656: i/o timeout module=pex addr=dce0b8415e940816be6219c14ca01ad5d401f6c9@44.208.191.127:26656
Apr 05 21:24:49 ormi-infra4-POLYGON-NODE heimdalld[140000]: INFO [2023-04-05|21:24:49.535] Executed block                               module=state height=13455551 validTxs=0 invalidTxs=0
Apr 05 21:24:49 ormi-infra4-POLYGON-NODE heimdalld[140000]: INFO [2023-04-05|21:24:49.550] Committed state                              module=state height=13455551 txs=0 appHash=1A404490CE2D6BA02E9B7708E2F4F03801DEE80F42635666B5934D9B0EF1B334
Apr 05 21:24:55 ormi-infra4-POLYGON-NODE heimdalld[140000]: INFO [2023-04-05|21:24:55.917] Executed block                               module=state height=13455552 validTxs=0 invalidTxs=0
Apr 05 21:24:55 ormi-infra4-POLYGON-NODE heimdalld[140000]: INFO [2023-04-05|21:24:55.931] Committed state                              module=state height=13455552 txs=0 appHash=1A404490CE2D6BA02E9B7708E2F4F03801DEE80F42635666B5934D9B0EF1B334
Apr 05 21:25:02 ormi-infra4-POLYGON-NODE heimdalld[140000]: INFO [2023-04-05|21:25:02.407] Executed block                               module=state height=13455553 validTxs=0 invalidTxs=0
Apr 05 21:25:02 ormi-infra4-POLYGON-NODE heimdalld[140000]: INFO [2023-04-05|21:25:02.414] Committed state                              module=state height=13455553 txs=0 appHash=1A404490CE2D6BA02E9B7708E2F4F03801DEE80F42635666B5934D9B0EF1B334
Apr 05 21:25:08 ormi-infra4-POLYGON-NODE heimdalld[140000]: INFO [2023-04-05|21:25:08.739] Executed Apr 05 18:27:08 ormi-infra4-POLYGON-NODE heimdalld[138143]: INFO [2023-04-05|18:27:08.145] Committed state                              module=state height=13453957 t
~~~
Above was my log, looks like it is a mixture of `Executed block` and `Error dialing failed`. ** this is normal right?** that means node is syncing/working.

**Comment by manav2401** [comment]
This is a normal behaviour. If you're seeing "Executed block" logs, it's syncing well. Closing this for now.

**Comment by zhy827827** [comment]
`Apr 21 10:21:29 rockx-mainnet-polygon-ovh-node-04 heimdalld[6607]: ERROR[2023-04-21|10:21:29.685] Stopping peer for error                      module=p2p peer="Peer{MConn{198.244.230.33:26656} 57269dada606a66d8ef6a7d7f23f1fb600153c8e out}" err=EOF
Apr 21 10:21:29 rockx-mainnet-polygon-ovh-node-04 heimdalld[6607]: ERROR[2023-04-21|10:21:29.752] Stopping peer for error                      module=p2p peer="Peer{MConn{176.9.38.172:26656} bb15a8858348ce49a87ff3b2e8c13a5441d58d4b out}" err=EOF
Apr 21 10:21:29 rockx-mainnet-polygon-ovh-node-04 heimdalld[6607]: ERROR[2023-04-21|10:21:29.756] Stopping peer for error                      module=p2p peer="Peer{MConn{52.70.44.85:26656} 3521f9ba40eecbb2cf0b4e419dcd5e5d86e23b58 out}" err=EOF
Apr 21 10:21:29 rockx-mainnet-polygon-ovh-node-04 heimdalld[6607]: ERROR[2023-04-21|10:21:29.805] Stopping peer for error                      module=p2p peer="Peer{MConn{65.109.37.125:26656} cab4d73fa55411959f91933fd8bf55d000f324bf out}" err=EOF
Apr 21 10:21:29 rockx-mainnet-polygon-ovh-node-04 heimdalld[6607]: ERROR[2023-04-21|10:21:29.805] Stopping peer for error                      module=p2p peer="Peer{MConn{65.108.192.211:26656} 5c36ee607d13512acc57e7492887f0005b7b08f2 out}" err=EOF
Apr 21 10:21:29 rockx-mainnet-polygon-ovh-node-04 heimdalld[6607]: ERROR[2023-04-21|10:21:29.829] Stopping peer for error                      module=p2p peer="Peer{MConn{62.182.82.250:26656} 5f5890d55798507841bea066e81c3463aeaaf447 out}" err=EOF
Apr 21 10:21:30 rockx-mainnet-polygon-ovh-node-04 heimdalld[6607]: ERROR[2023-04-21|10:21:30.018] dialing failed (attempts: 1): dial tcp 20.51.189.85:26656: i/o timeout module=pex addr=1ac0b61a22be2301a6b522e07b06b01475bba7e3@20.51.189.85:26656
Apr 21 10:21:30 rockx-mainnet-polygon-ovh-node-04 heimdalld[6607]: ERROR[2023-04-21|10:21:30.018] dialing failed (attempts: 1): dial tcp 18.210.114.236:26656: i/o timeout module=pex addr=be5c316666df9a025511a5e6209aca06e4667b59@18.210.114.236:26656
Apr 21 10:21:59 rockx-mainnet-polygon-ovh-node-04 heimdalld[6607]: ERROR[2023-04-21|10:21:59.368] Stopping peer for error                      module=p2p peer="Peer{MConn{18.180.156.34:26656} 6f1ecc0fd643581b5e91e3b64c7fe3ce41e4ee8a out}" err=EOF
Apr 21 10:21:59 rockx-mainnet-polygon-ovh-node-04 heimdalld[6607]: ERROR[2023-04-21|10:21:59.677] Stopping peer for error                      module=p2p peer="Peer{MConn{141.95.145.36:26656} fb52d329c2a628ba7cafad31c12d5be270091038 out}" err=EOF
Apr 21 10:21:59 rockx-mainnet-polygon-ovh-node-04 heimdalld[6607]: ERROR[2023-04-21|10:21:59.688] Stopping peer for error                      module=p2p peer="Peer{MConn{135.125.160.149:26656} 9c56cd18104c3a4275506d0beda6334f4ef3880a out}" err=EOF
Apr 21 10:21:59 rockx-mainnet-polygon-ovh-node-04 heimdalld[6607]: ERROR[2023-04-21|10:21:59.746] Stopping peer for error                      module=p2p peer="Peer{MConn{34.228.7.93:26656} a4d68af0538fea09619ad8be4d01d578a2354489 out}" err=EOF
Apr 21 10:21:59 rockx-mainnet-polygon-ovh-node-04 heimdalld[6607]: ERROR[2023-04-21|10:21:59.771] Stopping peer for error                      module=p2p peer="Peer{MConn{54.184.136.93:26656} 3a249dbe8bdc9caaeb4292f0e087e71a16c0c8a9 out}" err=EOF
Apr 21 10:21:59 rockx-mainnet-polygon-ovh-node-04 heimdalld[6607]: ERROR[2023-04-21|10:21:59.800] Stopping peer for error                      module=p2p peer="Peer{MConn{65.109.37.125:26656} cab4d73fa55411959f91933fd8bf55d000f324bf out}" err=EOF
Apr 21 10:21:59 rockx-mainnet-polygon-ovh-node-04 heimdalld[6607]: ERROR[2023-04-21|10:21:59.831] Stopping peer for error                      module=p2p peer="Peer{MConn{62.182.82.250:26656} 5f5890d55798507841bea066e81c3463aeaaf447 out}" err=EOF
Apr 21 10:22:00 rockx-mainnet-polygon-ovh-node-04 heimdalld[6607]: ERROR[2023-04-21|10:22:00.018] dialing failed (attempts: 1): dial tcp 52.203.70.254:26656: i/o timeout module=pex addr=5162b329701d0173661c4803ef6a854ecd67423c@52.203.70.254:26656
Apr 21 10:22:00 rockx-mainnet-polygon-ovh-node-04 heimdalld[6607]: ERROR[2023-04-21|10:22:00.018] dialing failed (attempts: 1): dial tcp 3.210.220.167:26656: i/o timeout module=pex addr=544ca02332a72c4e6af6e75f1f3d2f3d29d6c7c0@3.210.220.167:26656
Apr 21 10:22:00 rockx-mainnet-polygon-ovh-node-04 heimdalld[6607]: ERROR[2023-04-21|10:22:00.018] dialing failed (attempts: 1): dial tcp 3.82.89.65:26656: i/o timeout module=pex addr=3fba0ff64e16c558c051f2c08b5b97ff0925840e@3.82.89.65:26656
Apr 21 10:22:29 rockx-mainnet-polygon-ovh-node-04 heimdalld[6607]: ERROR[2023-04-21|10:22:29.443] Stopping peer for error                      module=p2p peer="Peer{MConn{3.35.192.94:26656} 745bfa4c31f71d4d8783cec0325fd4ad0f7c7063 out}" err=EOF
Apr 21 10:22:29 rockx-mainnet-polygon-ovh-node-04 heimdalld[6607]: ERROR[2023-04-21|10:22:29.720] Stopping peer for error                      module=p2p peer="Peer{MConn{169.155.168.232:26656} a7d96dc929824613315dcc1c90fee119f28cc51f out}" err=EOF
Apr 21 10:22:29 rockx-mainnet-polygon-ovh-node-04 heimdalld[6607]: ERROR[2023-04-21|10:22:29.742] Stopping peer for error                      module=p2p peer="Peer{MConn{116.202.232.190:26656} 786642e1e4312005e73b3926776d239199c4b413 out}" err=EOF
Apr 21 10:22:29 rockx-mainnet-polygon-ovh-node-04 heimdalld[6607]: ERROR[2023-04-21|10:22:29.747] Stopping peer for error                      module=p2p peer="Peer{MConn{3.131.6.142:26656} ad122410e3282fd64c422f3d1082dc734adf2e79 out}" err=EOF
Apr 21 10:22:29 rockx-mainnet-polygon-ovh-node-04 heimdalld[6607]: ERROR[2023-04-21|10:22:29.749] Stopping peer for error                      module=p2p peer="Peer{MConn{54.86.235.94:26656} 149dbcc6faf267c426e0376749e3824e64f77066 out}" err=EOF
Apr 21 10:22:29 rockx-mainnet-polygon-ovh-node-04 heimdalld[6607]: ERROR[2023-04-21|10:22:29.755] Stopping peer for error                      module=p2p peer="Peer{MConn{52.21.112.201:26656} 2e6a7e393185f10e069579af120326d5fc3d2c86 out}" err=EOF
Apr 21 10:22:30 rockx-mainnet-polygon-ovh-node-04 heimdalld[6607]: ERROR[2023-04-21|10:22:30.018] dialing failed (attempts: 1): dial tcp 141.95.101.109:26656: i/o timeout module=pex addr=ea94ee6aa1e924ab62173c0653997aa4ea72fe09@141.95.101.109:26656
Apr 21 10:22:30 rockx-mainnet-polygon-ovh-node-04 heimdalld[6607]: ERROR[2023-04-21|10:22:30.018] dialing failed (attempts: 1): dial tcp 54.243.36.57:26656: i/o timeout module=pex addr=9bf3c3d23d8d56364bf99a21dcf2a819a015245e@54.243.36.57:26656
Apr 21 10:22:30 rockx-mainnet-polygon-ovh-node-04 heimdalld[6607]: ERROR[2023-04-21|10:22:30.018] dialing failed (attempts: 1): dial tcp 3.93.110.101:26656: i/o timeout module=pex addr=343641823857db3b75213281f9455417cd0e3689@3.93.110.101:26656
Apr 21 10:22:30 rockx-mainnet-polygon-ovh-node-04 heimdalld[6607]: ERROR[2023-04-21|10:22:30.154] Error on catchup replay. Proceeding to start ConsensusState anyway module=consensus err="Cannot replay height 13655206. WAL does not contain #ENDHEIGHT for 13655205"
Apr 21 10:22:59 rockx-mainnet-polygon-ovh-node-04 heimdalld[6607]: ERROR[2023-04-21|10:22:59.175] Stopping peer for error                      module=p2p peer="Peer{MConn{13.212.107.7:26656} 2dabad99f1a5f0985dbbaa2eaa2084ae015e6c02 out}" err=EOF
Apr 21 10:22:59 rockx-mainnet-polygon-ovh-node-04 heimdalld[6607]: ERROR[2023-04-21|10:22:59.679] Stopping peer for error                      module=p2p peer="Peer{MConn{147.135.144.52:26656} dd97f86d096b7b81e6ee720aaba0562e2ed1bd03 out}" err=EOF
Apr 21 10:22:59 rockx-mainnet-polygon-ovh-node-04 heimdalld[6607]: ERROR[2023-04-21|10:22:59.687] Stopping peer for error                      module=p2p peer="Peer{MConn{35.190.186.16:26656} 5dd30f365d4ef12098e017eadedcfc93225fa5b5 out}" err=EOF
Apr 21 10:22:59 rockx-mainnet-polygon-ovh-node-04 heimdalld[6607]: ERROR[2023-04-21|10:22:59.689] Stopping peer for error                      module=p2p peer="Peer{MConn{51.38.53.113:26656} 0de1e2283be90465e7b25ae61527a3ab4e0685ac out}" err=EOF
Apr 21 10:22:59 rockx-mainnet-polygon-ovh-node-04 heimdalld[6607]: ERROR[2023-04-21|10:22:59.751] Stopping peer for error                      module=p2p peer="Peer{MConn{52.70.44.85:26656} 3521f9ba40eecbb2cf0b4e419dcd5e5d86e23b58 out}" err=EOF
Apr 21 10:22:59 rockx-mainnet-polygon-ovh-node-04 heimdalld[6607]: ERROR[2023-04-21|10:22:59.763] Stopping peer for error                      module=p2p peer="Peer{MConn{136.243.144.249:26656} 37378aec6d241e8dfdc292f56d9df12bae260a3c out}" err=EOF
Apr 21 10:22:59 rockx-mainnet-polygon-ovh-node-04 heimdalld[6607]: ERROR[2023-04-21|10:22:59.803] Stopping peer for error                      module=p2p peer="Peer{MConn{65.109.37.125:26656} cab4d73fa55411959f91933fd8bf55d000f324bf out}" err=EOF
Apr 21 10:23:00 rockx-mainnet-polygon-ovh-node-04 heimdalld[6607]: ERROR[2023-04-21|10:23:00.023] dialing failed (attempts: 1): dial tcp 3.227.147.144:26656: i/o timeout module=pex addr=e1b428426e2d74eca244e9ec32a2b4a75be46bf4@3.227.147.144:26656
Apr 21 10:23:00 rockx-mainnet-polygon-ovh-node-04 heimdalld[6607]: ERROR[2023-04-21|10:23:00.023] dialing failed (attempts: 2): dial tcp 65.109.22.144:26656: i/o timeout module=pex addr=e687eb2529bb71ee45d58294b4a2873de55c0749@65.109.22.144:26656
Apr 21 10:23:29 rockx-mainnet-polygon-ovh-node-04 heimdalld[6607]: ERROR[2023-04-21|10:23:29.267] dialing failed (attempts: 1): dial tcp 144.126.143.194:26656: connect: connection refused module=pex addr=70acb82ffb32d04b2ca968de1b38191c3014e9d6@144.126.143.194:26656
Apr 21 10:23:29 rockx-mainnet-polygon-ovh-node-04 heimdalld[6607]: ERROR[2023-04-21|10:23:29.717] Stopping peer for error                      module=p2p peer="Peer{MConn{134.65.193.93:26656} be641065cb6a97d42f5edb299c3d699610be36de out}" err=EOF
Apr 21 10:23:29 rockx-mainnet-polygon-ovh-node-04 heimdalld[6607]: ERROR[2023-04-21|10:23:29.743] Stopping peer for error                      module=p2p peer="Peer{MConn{54.86.235.94:26656} 149dbcc6faf267c426e0376749e3824e64f77066 out}" err=EOF
Apr 21 10:23:29 rockx-mainnet-polygon-ovh-node-04 heimdalld[6607]: ERROR[2023-04-21|10:23:29.746] Stopping peer for error                      module=p2p peer="Peer{MConn{3.22.45.51:46656} d7e71307f71acb0c5c7bd1cfc8a3928ba6f6510a out}" err=EOF
Apr 21 10:23:29 rockx-mainnet-polygon-ovh-node-04 heimdalld[6607]: ERROR[2023-04-21|10:23:29.751] Stopping peer for error                      module=p2p peer="Peer{MConn{52.21.112.201:26656} 2e6a7e393185f10e069579af120326d5fc3d2c86 out}" err=EOF
Apr 21 10:23:29 rockx-mainnet-polygon-ovh-node-04 heimdalld[6607]: ERROR[2023-04-21|10:23:29.783] Stopping peer for error                      module=p2p peer="Peer{MConn{135.181.223.33:26656} 5cd15e512d7502496e509fccb816391af5208b1a out}" err=EOF
Apr 21 10:23:29 rockx-mainnet-polygon-ovh-node-04 heimdalld[6607]: ERROR[2023-04-21|10:23:29.792] Stopping peer for error                      module=p2p peer="Peer{MConn{65.108.192.211:26656} 5c36ee607d13512acc57e7492887f0005b7b08f2 out}" err=EOF
Apr 21 10:23:29 rockx-mainnet-polygon-ovh-node-04 heimdalld[6607]: ERROR[2023-04-21|10:23:29.794] Stopping peer for error                      module=p2p peer="Peer{MConn{65.109.70.243:26656} 250bd045278bde695c88bc201cad25c67ee4a4ed out}" err=EOF
Apr 21 10:23:30 rockx-mainnet-polygon-ovh-node-04 heimdalld[6607]: ERROR[2023-04-21|10:23:30.019] dialing failed (attempts: 1): dial tcp 34.203.84.238:26656: i/o timeout module=pex addr=61af41fd75e0c46d6f5fbe9e20da67367e5614ee@34.203.84.238:26656`

**Comment by zhy827827** [comment]
heimdalld unable to connect to seed nodes

**Comment by 0xsajal** [comment]
Please use these heimdall seeds for mumbai and mainnet: 

Mainnet:

seeds="81c76e82fcc3dc9a0a1554a3edaa09a632795ea8@35.221.13.28:26656,a385dd467d11c4cdb0be8b51d7bfb0990f49abc3@35.199.4.13:26656,7285a532bad665f051c0aadc31054e2e61ca2b3d@3.93.224.197:26656,6f829065789e5b156cbbf076f9d133b4d7725847@3.212.183.151:26656,2a53a15ffc70ad41b6876ecbe05c50a66af01e20@3.211.248.31:26656,f4f605d60b8ffaaf15240564e58a81103510631c@159.203.9.164:26656,4fb1bc820088764a564d4f66bba1963d47d82329@44.232.55.71:26656,2eadba4be3ce47ac8db0a3538cb923b57b41c927@35.199.4.13:26656,3b23b20017a6f348d329c102ddc0088f0a10a444@35.221.13.28:26656,25f5f65a09c56e9f1d2d90618aa70cd358aa68da@35.230.116.151:26656"

seeds="daad548c0a163faae1d8d58425f97207acf923fd@35.230.116.151:26656,31b79cf4a628a4619e8e9ae95b72e4354c5a5d90@44.232.55.71:26656,0b431127d21c8970f1c353ab212be4f1ba86c3bf@184.73.124.158:26656,902484e868c6a4bace1bb3cf4b6ba1667561b158@18.228.218.160:26656,afc41bd37d549186cec915c5a4feb3071871cdc1@18.228.98.237:26656,587df41fb0198d72a9e153c608b2c0d840551429@35.182.147.162:26656"


Mumbai:

seeds="e72c0466a02ea43b2198bd3a9454b87a3ef0d77e@54.147.31.250:26656,b302d1ddb21102e794b524d05152a7834da05bd1@34.226.134.117:26656,4cd60c1d76e44b05f7dfd8bab3f447b119e87042@54.147.31.250:26656,9dfc12d9f39257cefc3d57a4d7302586e59a994e@18.213.200.99:26656,b18bbe1f3d8576f4b73d9b18976e71c65e839149@34.226.134.117:26656,76167e82b93849cd658a49bff9482a937351f71e@109.123.244.56:26656,7a6c7b5d25b13ce3448b047dbebeb1a19cc2e092@18.213.200.99:26656"

**Comment by yuliyantsvetkov** [comment]
/reopen

That does not work at all. All the seed nodes are down.
